### ISSUE TITLE
Composer 2.1.3 with PHP 8.0.8 : Cannot use positional argument after named argument 

### ISSUE THREAD

**Issue by gaetan-hexadog** [composer/composer#10010]
Hi,

I get an error each time a try to install a package using composer 2.1.3 since I update PHP to 8.0.
`PHP Fatal error:  Uncaught Error: Cannot use positional argument after named argument in phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:448`.

When I run this command (or `composer u` in any project):

```
composer global update
```

I get the following output: 

```
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
PHP Fatal error:  Uncaught Error: Cannot use positional argument after named argument in phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:448
Stack trace:
#0 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(448): call_user_func_array('array_merge', Array)
#1 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): Composer\EventDispatcher\EventDispatcher->getListeners(Object(Composer\Installer\InstallerEvent))
#2 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(150): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\InstallerEvent))
#3 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Installer.php(666): Composer\EventDispatcher\EventDispatcher->dispatchInstallerEvent('pre-operations-...', true, true, Object(Composer\DependencyResolver\LocalRepoTransaction))
#4 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Installer.php(543): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#5 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#6 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Command/UpdateCommand.php(241): Composer\Installer->run()
#7 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(312): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Command/GlobalCommand.php(111): Composer\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(835): Composer\Command\GlobalCommand->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\GlobalCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(312): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/bin/composer(64): Composer\Console\Application->run()
#20 /usr/local/Cellar/composer/2.1.3/bin/composer(24): require('phar:///usr/loc...')
#21 {main}
  thrown in phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 448

Fatal error: Uncaught Error: Cannot use positional argument after named argument in phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:448
Stack trace:
#0 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(448): call_user_func_array('array_merge', Array)
#1 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): Composer\EventDispatcher\EventDispatcher->getListeners(Object(Composer\Installer\InstallerEvent))
#2 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(150): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\InstallerEvent))
#3 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Installer.php(666): Composer\EventDispatcher\EventDispatcher->dispatchInstallerEvent('pre-operations-...', true, true, Object(Composer\DependencyResolver\LocalRepoTransaction))
#4 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Installer.php(543): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#5 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#6 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Command/UpdateCommand.php(241): Composer\Installer->run()
#7 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(312): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Command/GlobalCommand.php(111): Composer\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(835): Composer\Command\GlobalCommand->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\GlobalCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(312): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///usr/local/Cellar/composer/2.1.3/bin/composer/bin/composer(64): Composer\Console\Application->run()
#20 /usr/local/Cellar/composer/2.1.3/bin/composer(24): require('phar:///usr/loc...')
#21 {main}
  thrown in phar:///usr/local/Cellar/composer/2.1.3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 448
```

How can I get Composer 2 working with PHP 8 ? My Composer and PHP are installed through Brew.

I tried to uninstall and reinstall composer without any success.

regards

**Comment by gaetan-hexadog** [comment]
Found it.
It was due to the `repman-io/composer-plugin` which was stucked into version `1.0`.
I had to switch back to Composer 1, uninstall the plugin, switch to Composer 2 and reinstall the plugin to get it work.

```sh
composer self-update --1
composer global remove repman-io/composer-plugin
composer self-update --rollback
composer global require repman-io/composer-plugin
```

And it's working :-)
