### ISSUE TITLE
symfony recipes : composer recipes vs composer help "recipes"

### ISSUE THREAD

**Issue by Jduret** [composer/composer#10147]
I'm trying to use your composer Docker image. My project use Symfony and the Symfony/Flex Composer extension.
I use a shortcut to run composer command : 
```sh
#/usr/local/bin/composer
sudo docker run --rm --interactive --tty \
--volume $PWD:/app \
--volume ${COMPOSER_HOME:-$HOME/.composer}:/tmp \
composer "$@"
```
My issue occured when I try to call `composer recipes` under my project. 
> /docker-entrypoint.sh: exec: line 24: recipes: not found

So I open a bash in the container.
```
docker run -it --volume $PWD:/app \
--entrypoint /bin/bash composer
```
And then I ran the command : `composer recipes`
```
 bash-5.1# composer recipes

 Available recipes.

 * doctrine/annotations
  * doctrine/doctrine-bundle (update available)
 * doctrine/doctrine-migrations-bundle (update available)
 * symfony/apache-pack (update available)
 * symfony/console (update available)
 * symfony/flex
 * symfony/framework-bundle (update available)
 * symfony/maker-bundle
 * symfony/monolog-bundle (update available)
 * symfony/phpunit-bridge (update available)
 * symfony/routing (update available)
 * symfony/twig-bundle (update available)
 * symfony/validator (update available)
 * symfony/web-profiler-bundle

Run:
 * composer recipes vendor/package to see details about a recipe.
 * composer recipes:install vendor/package --force -v to update that recipe.
 ```
So the error is not from composer but from the entrypoint. 
In the entrypoint I found this : 
```sh
isCommand() {
  # Retain backwards compatibility with common CI providers,
  # see: https://github.com/composer/docker/issues/107
  if [ "$1" = "sh" ]; then
    return 1
  fi

  composer help "$1" > /dev/null 2>&1
}
```
So I ran this command  : `composer help "recipes"`
```
bash-5.1# composer help "recipes"

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "recipes" is not defined.

help [--xml] [--format FORMAT] [--raw] [--] [<command_name>]
```
Can you explain me why `composer recipes` work and `composer help "recipes"` don't ?

I've already tried the commande `composer help "recipes"` using a local composer and it works

**Comment by alcohol** [comment]
No idea if relevant or related as well, but running `composer list symfony` lists several commands from the symfony namespace, but running `composer list recipes` fails:

```
Fatal error: Uncaught ValueError: max(): Argument #1 ($value) must contain at least one element in phar:///usr/bin/composer/vendor/symfony/console/Descriptor/TextDescriptor.php:277
Stack trace:
#0 phar:///usr/bin/composer/vendor/symfony/console/Descriptor/TextDescriptor.php(277): max(Array)
#1 phar:///usr/bin/composer/vendor/symfony/console/Descriptor/TextDescriptor.php(194): Symfony\Component\Console\Descriptor\TextDescriptor->getColumnWidth(Array)
#2 phar:///usr/bin/composer/vendor/symfony/console/Descriptor/Descriptor.php(55): Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication(Object(Composer\Console\Application), Array)
#3 phar:///usr/bin/composer/vendor/symfony/console/Helper/DescriptorHelper.php(69): Symfony\Component\Console\Descriptor\Descriptor->describe(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Composer\Console\Application), Array)
#4 phar:///usr/bin/composer/vendor/symfony/console/Command/ListCommand.php(81): Symfony\Component\Console\Helper\DescriptorHelper->describe(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Composer\Console\Application), Array)
#5 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(245): Symfony\Component\Console\Command\ListCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\Command\ListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/bin/composer/bin/composer(67): Composer\Console\Application->run()
#12 /usr/bin/composer(29): require('phar:///usr/bin...')
#13 {main}
  thrown in phar:///usr/bin/composer/vendor/symfony/console/Descriptor/TextDescriptor.php on line 277
```
