### ISSUE TITLE
PHP Fatal error when trying to install dependences

### ISSUE THREAD

**Issue by dioobr** [composer/composer#10247]
PHP 8.0.9
Composer 2.1.10
macOS 10.15.7

When I run "composer i", returns:

```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php:297
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(290): Composer\Repository\PlatformRepository->initialize()
#1 phar:///usr/local/bin/composer/src/Composer/Installer.php(881): Composer\Repository\ArrayRepository->getPackages()
#2 phar:///usr/local/bin/composer/src/Composer/Installer.php(419): Composer\Installer->createRequest()
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(271): Composer\Installer->doUpdate()
#4 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(140): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#10 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run()
#11 phar:///usr/local/bin/composer/bin/composer(73): Composer\Console\Application->run()
#12 /usr/local/bin/composer(29): require('...')
#13 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 297

Fatal error: Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php:297
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(290): Composer\Repository\PlatformRepository->initialize()
#1 phar:///usr/local/bin/composer/src/Composer/Installer.php(881): Composer\Repository\ArrayRepository->getPackages()
#2 phar:///usr/local/bin/composer/src/Composer/Installer.php(419): Composer\Installer->createRequest()
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(271): Composer\Installer->doUpdate()
#4 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(140): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#10 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run()
#11 phar:///usr/local/bin/composer/bin/composer(73): Composer\Console\Application->run()
#12 /usr/local/bin/composer(29): require('...')
#13 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 297
```

composer diagnose

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.1.10
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php:297
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(290): Composer\Repository\PlatformRepository->initialize()
#1 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(108): Composer\Repository\ArrayRepository->getPackages()
#2 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(166): Composer\Repository\ArrayRepository->findPackage()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\DiagnoseCommand->execute()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/composer/bin/composer(73): Composer\Console\Application->run()
#10 /usr/local/bin/composer(29): require('...')
#11 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 297

Fatal error: Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php:297
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(290): Composer\Repository\PlatformRepository->initialize()
#1 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(108): Composer\Repository\ArrayRepository->getPackages()
#2 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(166): Composer\Repository\ArrayRepository->findPackage()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\DiagnoseCommand->execute()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/composer/bin/composer(73): Composer\Console\Application->run()
#10 /usr/local/bin/composer(29): require('...')
#11 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 297
```

composer i -vvv

```
Running 2.1.10 (2021-10-29 22:34:57) with PHP 8.0.9 on Darwin / 19.6.0
Reading ./composer.json (/Users/diogo/Sites/labs/phpunit/teste01/composer.json)
Loading config file /Users/diogo/.composer/config.json
Loading config file /Users/diogo/.composer/auth.json
Loading config file ./composer.json (/Users/diogo/Sites/labs/phpunit/teste01/composer.json)
Checked CA file /usr/local/openssl-1.1.1k/ssl/certs/cacert.pem: valid
Executing command (/Users/diogo/Sites/labs/phpunit/teste01): git branch -a --no-color --no-abbrev -v
Executing command (/Users/diogo/Sites/labs/phpunit/teste01): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/Users/diogo/Sites/labs/phpunit/teste01): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/diogo/Sites/labs/phpunit/teste01): hg branch
Executing command (/Users/diogo/Sites/labs/phpunit/teste01): fossil branch list
Executing command (/Users/diogo/Sites/labs/phpunit/teste01): fossil tag list
Executing command (/Users/diogo/Sites/labs/phpunit/teste01): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /Users/diogo/.composer/composer.json

No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php:297
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(290): Composer\Repository\PlatformRepository->initialize()
#1 phar:///usr/local/bin/composer/src/Composer/Installer.php(881): Composer\Repository\ArrayRepository->getPackages()
#2 phar:///usr/local/bin/composer/src/Composer/Installer.php(419): Composer\Installer->createRequest()
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(271): Composer\Installer->doUpdate()
#4 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(140): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#10 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run()
#11 phar:///usr/local/bin/composer/bin/composer(73): Composer\Console\Application->run()
#12 /usr/local/bin/composer(29): require('...')
#13 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 297

Fatal error: Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php:297
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(290): Composer\Repository\PlatformRepository->initialize()
#1 phar:///usr/local/bin/composer/src/Composer/Installer.php(881): Composer\Repository\ArrayRepository->getPackages()
#2 phar:///usr/local/bin/composer/src/Composer/Installer.php(419): Composer\Installer->createRequest()
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(271): Composer\Installer->doUpdate()
#4 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(140): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#10 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run()
#11 phar:///usr/local/bin/composer/bin/composer(73): Composer\Console\Application->run()
#12 /usr/local/bin/composer(29): require('...')
#13 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 297
```

**Comment by dioobr** [comment]
After check the composer source code, found that the error was happening when it tries to check ICU version. It was 58.x, updated to 69.x and recompiled PHP. It works just fine now.
