### ISSUE TITLE
FilesystemException while self-update

### ISSUE THREAD

**Issue by staabm** [composer/composer#10252]
running `composer self-update` from within a folder which did not contain any `composer.json` file resulted in a exception/error:
```
complexit@deployphp20:/deploy/motiontm/test$ composer self-update
Upgrading to version 2.1.11 (stable channel).

{
if ($output) {
$this->io->writeError("  - " . InstallOperation::format($package));
}

$this->filesystem->emptyDirectory($path);
$this->filesystem->ensureDirectoryExists($path);
$this->filesystem->rename($this->getFileName($package, $path), $path . '/' . pathinfo(p
Fatal error: Uncaught Error: Class 'Composer\Downloader\FilesystemException' not found in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php:447
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php(309): Composer\Command\SelfUpdateCommand->setLocalPhar('/usr/local/bin/...', '/home/complexit...', '/home/complexit...')
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\SelfUpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\SelfUpdateCommand), Object(Symfony\C in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php on line 447
complexit@deployphp20:/deploy/motiontm/test$ composer --version
Composer version 2.1.11 2021-11-02 12:10:25
complexit@deployphp20:/deploy/motiontm/test$ composer self-update
You are already using the latest available Composer version 2.1.11 (stable channel).
```

the update itself succeeded nevertheless as `composer --version` told me (see above).

this happened when updating 2.1.10 to 2.1.11 on a ubuntu20 lts host.

```
php -v
PHP 7.4.24 (cli) (built: Sep 23 2021 21:36:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.24, Copyright (c), by Zend Technologies
    with blackfire v1.67.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

I cannot reproduce atm.. it seems it was a one time problem.

**Comment by Seldaek** [comment]
Very weird, is the output above really what you saw in the output? 

I see the temp filename used by self-update is a fixed path and not random, so there could be concurrency issues theoretically.. Probably worth fixing that. 

Is there a chance you got multiple self-update running at the same time on your env?

**Comment by staabm** [comment]
> Very weird, is the output above really what you saw in the output?

yep.
 
> I see the temp filename used by self-update is a fixed path and not random, so there could be concurrency issues theoretically.. Probably worth fixing that.
> 
> Is there a chance you got multiple self-update running at the same time on your env?

nope, I am the only user on that machine and triggered just one.

**Comment by Seldaek** [comment]
Looks like it printed out 

https://github.com/composer/composer/blob/abf832aa49cac76bb148d926ececbdfe402a5239/src/Composer/Downloader/FileDownloader.php#L342-L348

Which sounds maybe possible to me if it tried including the FilesystemException to throw one, but the file has already been updated to the new phar, so it reads from the wrong offset in the file? Something along those lines..

What I can't make sense of is the line 309 and 447.. Neither of which make any sense for triggering a filesystem exception.

But I guess I can preload the exception and co for safety..

**Comment by staabm** [comment]
on the affected machine I just did rollback and got another error:

```
complexit@deployphp20:/deploy$ composer self-update --rollback
Rolling back to version 2021-10-05_09-47-38-2.1.9.
ardedChanges = array();

private $gitUtil;
private $cachedPackages = array();

public function __construct(IOInterface $io, Config $config, ProcessExecutor $process = null, Filesystem $fs = null)
{
parent::__construct($io, $config, $process, $fs);
$this->gitUtil =
Fatal error: Uncaught Error: Class 'Composer\Downloader\FilesystemException' not found in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php:466
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php(409): Composer\Command\SelfUpdateCommand->setLocalPhar('/usr/local/bin/...', '/home/complexit...')
#1 phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php(143): Composer\Command\SelfUpdateCommand->rollback(Object(Symfony\Component\Console\Output\ConsoleOutput), '/home/complexit...', '/usr/local/bin/...')
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\SelfUpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\C in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php on line 466
```

running another self-update leads to 
```
complexit@deployphp20:/deploy$ composer self-update
Upgrading to version 2.1.11 (stable channel).

{
if ($output) {
$this->io->writeError("  - " . InstallOperation::format($package));
}

$this->filesystem->emptyDirectory($path);
$this->filesystem->ensureDirectoryExists($path);
$this->filesystem->rename($this->getFileName($package, $path), $path . '/' . pathinfo(p
Fatal error: Uncaught Error: Class 'Composer\Downloader\FilesystemException' not found in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php:447
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php(309): Composer\Command\SelfUpdateCommand->setLocalPhar('/usr/local/bin/...', '/home/complexit...', '/home/complexit...')
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\SelfUpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\SelfUpdateCommand), Object(Symfony\C in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php on line 447
```

it seems I can somehow reproduce

**Comment by Seldaek** [comment]
OK can you maybe try now with `composer self-update --snapshot` and then `composer self-update --stable`? The first should do the weird output still I guess, the second should not hopefully.

**Comment by staabm** [comment]
hmm

```
complexit@deployphp20:/deploy$ composer self-update --snapshot
Upgrading to version 3bb78fd1ee8a254878a71cf12c275b5f8303c2b0 (snapshot channel).


Fatal error: Uncaught Error: Class 'Composer\Downloader\FilesystemException' not found in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php:466
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php(318): Composer\Command\SelfUpdateCommand->setLocalPhar('/usr/local/bin/...', '/home/complexit...', '/home/complexit...')
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\SelfUpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\SelfUpdateCommand), Object(Symfony\C in phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php on line 466
```

```
complexit@deployphp20:/deploy$ composer self-update --stable
complexit@deployphp20:/deploy$ composer --version
complexit@deployphp20:/deploy$
```

it seems the error now longer appears, but the composer command no longer works

**Comment by Seldaek** [comment]
Hmm so that's better 😆 

What's the environment? Is that a linux server or some WSL/VM weirdness?

Anything in the error log perhaps from the self-update which did the 0 bytes file?

**Comment by Seldaek** [comment]
I added a rename('/root', '/root2') in setLocalPhar just to trigger the FilesystemException and it seems to work for me:

```
$ php composer.phar self --stable
Upgrading to version 2.1.11 (stable channel).



  [Composer\Downloader\FilesystemException]
  Filesystem exception:
  Composer update failed: "/var/www/composer/composer.phar" could not be written.
  rename(/root,/root2): Permission denied


self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--set-channel-only] [--] [<version>]
```

So I am really puzzled as what is going wrong in your env..

**Comment by staabm** [comment]
> What's the environment? Is that a linux server or some WSL/VM weirdness?

I am on a ubuntu20 lts in a ESX Server (VM)

```
php -v
PHP 7.4.24 (cli) (built: Sep 23 2021 21:36:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.24, Copyright (c), by Zend Technologies
    with blackfire v1.67.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

since my previous composer got overritten, I just downloaded a fresh copy using `composer-setup.php`.
atm I cannot reproduce the initially reported problem when doing self-updates between `snapshot` and `stable`.

**Comment by Seldaek** [comment]
OK I have no idea what was going on then.. Probably was either a permission issue or a corrupt file somehow?

**Comment by mohammedALhakmy** [comment]
**[***********@nl-srv-web1097 ******************]$ composer self-update --stable
A new stable major version of Composer is available (2.6.6), run "composer self-update --2" to update to it. See also https://getcomposer.org/2
Updating to version 1.10.27 (1.x channel).
   Downloading (100%)


  [Composer\Downloader\FilesystemException]
  Filesystem exception:
  Composer update failed: "/usr/local/bin/composer1.phar" could not be written.
  rename(/usr/local/bin/composer1.phar): Failed to open stream: Read-only file system**
what is answer con
rrect?

**Comment by Seldaek** [comment]
You have no permission so you should run the command with sudo I imagine.

Also you should consider updating to Composer 2 as it says on the first line of output..

**Comment by TimWolla** [comment]
see php/php-src#17125
