### ISSUE TITLE
Class not found exception with composer 2.2

### ISSUE THREAD

**Issue by jderusse** [composer/composer#10277]
My `composer.json`:

```json
{
    "require": {
        "sentry/sentry-symfony": "^4.2"
    },
    "scripts": {
        "post-update-cmd": [
            "@auto-scripts"
        ]
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.2-dev+4589b9bb1835bbb5b149a15df5a5bb3b786281a8
PHP version: 8.0.12
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.74.0 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension not loaded, unzip present, 7-Zip not available
```

When I run this command: 

```
php ./composer.phar up
```

I get the following output: 

```
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
34 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Fatal error: Uncaught Error: Class "Symfony\Component\HttpKernel\Kernel" not found in /srv/vendor/sentry/sentry-symfony/src/aliases.php:32
Stack trace:
#0 phar:///srv/composer.phar/src/Composer/Autoload/AutoloadGenerator.php(1425): require()
#1 phar:///srv/composer.phar/src/Composer/Autoload/AutoloadGenerator.php(626): Composer\Autoload\composerRequire('39d333a989a6b17...', '/srv/vendor/sen...')
#2 phar:///srv/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(508): Composer\Autoload\AutoloadGenerator->createLoader(Array, '/srv/vendor')
#3 phar:///srv/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(455): Composer\EventDispatcher\EventDispatcher->getScriptListeners(Object(Composer\Script\Event))
#4 phar:///srv/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(172): Composer\EventDispatcher\EventDispatcher->getListeners(Object(Composer\Script\Event))
#5 phar:///srv/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#6 phar:///srv/composer.phar/src/Composer/Installer.php(371): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#7 phar:///srv/composer.phar/src/Composer/Command/UpdateCommand.php(249): Composer\Installer->run()
#8 phar:///srv/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///srv/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///srv/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///srv/composer.phar/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///srv/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///srv/composer.phar/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///srv/composer.phar/bin/composer(73): Composer\Console\Application->run()
#15 /srv/composer.phar(30): require('phar:///srv/com...')
#16 {main}
  thrown in /srv/vendor/sentry/sentry-symfony/src/aliases.php on line 32

```

note: 

1. I reproduce the issue in an empty project inside docker container (image `PHP:8`) do be sure it's not related to a plugin (ie. flex).

2. class exists in `vendor/symfony/http-kernel/Kernel.php`

3. When downgrading to stable (`./composer.phar selfupdate --stable`), the problem vanish

**Comment by alexander-schranz** [comment]
I got a similar error on sulu repository:

<details>
<summary>ErrorLog</summary>

```bash
PHP Fatal error:  Uncaught Error: Class "Doctrine\Common\Annotations\Annotation" not found in /private/tmp/skeleton/vendor/handcraftedinthealps/rest-routing-bundle/Controller/Annotations/NamePrefix.php:24
Stack trace:
#0 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1425): require()
#1 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(626): Composer\Autoload\composerRequire('afb2d0285e8b2d2...', '/private/tmp/sk...')
#2 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(508): Composer\Autoload\AutoloadGenerator->createLoader(Array, '/private/tmp/sk...')
#3 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(455): Composer\EventDispatcher\EventDispatcher->getScriptListeners(Object(Composer\Script\Event))
#4 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(172): Composer\EventDispatcher\EventDispatcher->getListeners(Object(Composer\Script\Event))
#5 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#6 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Installer.php(371): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#7 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Command/UpdateCommand.php(249): Composer\Installer->run()
#8 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/bin/composer(73): Composer\Console\Application->run()
#15 /usr/local/Cellar/composer/2.0.8/bin/composer(30): require('phar:///usr/loc...')
#16 {main}
  thrown in /private/tmp/skeleton/vendor/handcraftedinthealps/rest-routing-bundle/Controller/Annotations/NamePrefix.php on line 24

Fatal error: Uncaught Error: Class "Doctrine\Common\Annotations\Annotation" not found in /private/tmp/skeleton/vendor/handcraftedinthealps/rest-routing-bundle/Controller/Annotations/NamePrefix.php:24
Stack trace:
#0 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1425): require()
#1 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(626): Composer\Autoload\composerRequire('afb2d0285e8b2d2...', '/private/tmp/sk...')
#2 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(508): Composer\Autoload\AutoloadGenerator->createLoader(Array, '/private/tmp/sk...')
#3 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(455): Composer\EventDispatcher\EventDispatcher->getScriptListeners(Object(Composer\Script\Event))
#4 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(172): Composer\EventDispatcher\EventDispatcher->getListeners(Object(Composer\Script\Event))
#5 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#6 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Installer.php(371): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#7 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Command/UpdateCommand.php(249): Composer\Installer->run()
#8 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///usr/local/Cellar/composer/2.0.8/bin/composer/bin/composer(73): Composer\Console\Application->run()
#15 /usr/local/Cellar/composer/2.0.8/bin/composer(30): require('phar:///usr/loc...')
#16 {main}
  thrown in /private/tmp/skeleton/vendor/handcraftedinthealps/rest-routing-bundle/Controller/Annotations/NamePrefix.php on line 24
```

</details>

Reproducable:

```bash
git clone git@github.com:sulu/skeleton.git sulu-skeleton
composer self-update --snapshot
composer update
```

Same as above its away if I use the stable version of composer.

**Comment by herndlm** [comment]
fyi `git bisect` points to 8553c6d9784c9ab4ef22240725c1344728a4b279 / #10065 @nicolas-grekas

**Comment by barryvdh** [comment]
I'm getting the same error on Laravel after updating to the snapshot version.

```
[ErrorException]                                            
  Class 'Amp\Serialization\SerializationException' not found
```

And Magento2:

```
PHP Fatal error:  Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /var/www/project/app/code/Fruitcake/CustomerLoggedin/registration.php:3
Stack trace:
#0 /var/www/project/app/etc/NonComposerComponentRegistration.php(29): require_once()
#1 [internal function]: Magento\NonComposerComponentRegistration\{closure}()
#2 /var/www/project/app/etc/NonComposerComponentRegistration.php(31): array_map()
#3 /var/www/project/app/etc/NonComposerComponentRegistration.php(34): Magento\NonComposerComponentRegistration\{closure}()
#4 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1425): require('/var/www/smaakh...')
#5 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(626): Composer\Autoload\composerRequire()
#6 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(201): Composer\Autoload\AutoloadGenerator->createLoader()
#7 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(419): Composer\Plugin\PluginManager in /var/www/project/app/code/Fruitcake/CustomerLoggedin/registration.php on line 3

```
