### ISSUE TITLE
Updating composer from 2.1.14 to 2.2.0-RC1 in combination with `seld/phar-utils` leads to fatal error

### ISSUE THREAD

**Issue by boesing** [composer/composer#10378]
Hey there,

I've tried to update to composer 2.2.0-RC1 from 2.1.14 which also bumped `seld/phar-utils`.
I don't know why, but I end up getting the output shown below. The issue only occurs when `seld/phar-utils` is bumped as well.

I simply changed my composer JSON from the example below to `^2.2.0-RC1`.

My `composer.json`:

```json
{
    "config": {
        "github-protocols": ["ssh"]
    },
    "require": {
        "composer/composer": "^2.1"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Composer version: 2.1.14
PHP version: 7.4.26
PHP binary path: /usr/local/Cellar/php@7.4/7.4.26_1/bin/php
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
cURL version: 7.80.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1l
zip: extension present, unzip present, 7-Zip not available

```

When I run this command: 

```
composer update -vvv
```

I get the following output: 

```
Running 2.1.14 (2021-11-30 10:51:43) with PHP 7.4.26 on Darwin / 20.3.0
Reading ./composer.json (/Users/max/git/tools/composer/composer.json)
Loading config file /Users/max/.composer/config.json
Loading config file /Users/max/.composer/auth.json
Loading config file ./composer.json (/Users/max/git/tools/composer/composer.json)
Checked CA file /usr/local/etc/ca-certificates/cert.pem: valid
Executing command (/Users/max/git/tools/composer): git branch -a --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /Users/max/.composer/composer.json

Reading /Users/max/git/tools/composer/vendor/composer/installed.json
Reading ./composer.lock (/Users/max/git/tools/composer/composer.lock)
Loading composer repositories with package information
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/packages.json into cache
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-composer~composer.json from cache
Downloading https://repo.packagist.org/p2/composer/composer.json if modified
[304] https://repo.packagist.org/p2/composer/composer.json
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-composer~ca-bundle.json from cache
Downloading https://repo.packagist.org/p2/composer/ca-bundle.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-composer~metadata-minifier.json from cache
Downloading https://repo.packagist.org/p2/composer/metadata-minifier.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-composer~semver.json from cache
Downloading https://repo.packagist.org/p2/composer/semver.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-composer~spdx-licenses.json from cache
Downloading https://repo.packagist.org/p2/composer/spdx-licenses.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-composer~xdebug-handler.json from cache
Downloading https://repo.packagist.org/p2/composer/xdebug-handler.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-justinrainbow~json-schema.json from cache
Downloading https://repo.packagist.org/p2/justinrainbow/json-schema.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-psr~log.json from cache
Downloading https://repo.packagist.org/p2/psr/log.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-seld~jsonlint.json from cache
Downloading https://repo.packagist.org/p2/seld/jsonlint.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-seld~phar-utils.json from cache
Downloading https://repo.packagist.org/p2/seld/phar-utils.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~console.json from cache
Downloading https://repo.packagist.org/p2/symfony/console.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~filesystem.json from cache
Downloading https://repo.packagist.org/p2/symfony/filesystem.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~finder.json from cache
Downloading https://repo.packagist.org/p2/symfony/finder.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~process.json from cache
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-react~promise.json from cache
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-composer~pcre.json from cache
[304] https://repo.packagist.org/p2/composer/ca-bundle.json
[304] https://repo.packagist.org/p2/composer/metadata-minifier.json
[304] https://repo.packagist.org/p2/composer/semver.json
[304] https://repo.packagist.org/p2/composer/spdx-licenses.json
[304] https://repo.packagist.org/p2/composer/xdebug-handler.json
Downloading https://repo.packagist.org/p2/symfony/process.json if modified
Downloading https://repo.packagist.org/p2/react/promise.json if modified
Downloading https://repo.packagist.org/p2/composer/pcre.json if modified
[304] https://repo.packagist.org/p2/justinrainbow/json-schema.json
[304] https://repo.packagist.org/p2/psr/log.json
[304] https://repo.packagist.org/p2/seld/jsonlint.json
[304] https://repo.packagist.org/p2/seld/phar-utils.json
[304] https://repo.packagist.org/p2/symfony/console.json
[304] https://repo.packagist.org/p2/symfony/filesystem.json
[304] https://repo.packagist.org/p2/symfony/finder.json
[304] https://repo.packagist.org/p2/symfony/process.json
[304] https://repo.packagist.org/p2/react/promise.json
[304] https://repo.packagist.org/p2/composer/pcre.json
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-psr~log.json from cache
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~deprecation-contracts.json from cache
Downloading https://repo.packagist.org/p2/symfony/deprecation-contracts.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~polyfill-mbstring.json from cache
Downloading https://repo.packagist.org/p2/symfony/polyfill-mbstring.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~polyfill-php73.json from cache
Downloading https://repo.packagist.org/p2/symfony/polyfill-php73.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~polyfill-php80.json from cache
Downloading https://repo.packagist.org/p2/symfony/polyfill-php80.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~service-contracts.json from cache
Downloading https://repo.packagist.org/p2/symfony/service-contracts.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~string.json from cache
Downloading https://repo.packagist.org/p2/symfony/string.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~debug.json from cache
Downloading https://repo.packagist.org/p2/symfony/debug.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~polyfill-ctype.json from cache
Downloading https://repo.packagist.org/p2/symfony/polyfill-ctype.json if modified
[304] https://repo.packagist.org/p2/symfony/deprecation-contracts.json
[304] https://repo.packagist.org/p2/symfony/polyfill-mbstring.json
[304] https://repo.packagist.org/p2/symfony/polyfill-php73.json
[304] https://repo.packagist.org/p2/symfony/polyfill-php80.json
[304] https://repo.packagist.org/p2/symfony/service-contracts.json
[304] https://repo.packagist.org/p2/symfony/string.json
[304] https://repo.packagist.org/p2/symfony/debug.json
[304] https://repo.packagist.org/p2/symfony/polyfill-ctype.json
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-psr~container.json from cache
Downloading https://repo.packagist.org/p2/psr/container.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~polyfill-intl-grapheme.json from cache
Downloading https://repo.packagist.org/p2/symfony/polyfill-intl-grapheme.json if modified
Reading /Users/max/Library/Caches/composer/repo/https---repo.packagist.org/provider-symfony~polyfill-intl-normalizer.json from cache
Downloading https://repo.packagist.org/p2/symfony/polyfill-intl-normalizer.json if modified
[304] https://repo.packagist.org/p2/psr/container.json
[304] https://repo.packagist.org/p2/symfony/polyfill-intl-grapheme.json
[304] https://repo.packagist.org/p2/symfony/polyfill-intl-normalizer.json
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #1)
Dependency resolution completed in 0.005 seconds
Analyzed 1028 packages to resolve dependencies
Analyzed 2774 rules to resolve dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
Updates: seld/phar-utils:1.2.0, composer/composer:2.2.0-RC1
  - Upgrading composer/composer (2.1.14 => 2.2.0-RC1)
  - Upgrading seld/phar-utils (1.1.2 => 1.2.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Reading ./composer.lock (/Users/max/git/tools/composer/composer.lock)
Package operations: 0 installs, 2 updates, 0 removals
Updates: seld/phar-utils:1.2.0, composer/composer:2.2.0-RC1
Reading /Users/max/Library/Caches/composer/files/seld/phar-utils/143cfb38890df103dc0fa214874cf44391319f22.zip from cache
  - Loading seld/phar-utils (1.2.0) from cache
Reading /Users/max/Library/Caches/composer/files/composer/composer/4209012542cd5fe759578cb74a1f8a62104e2709.zip from cache
  - Loading composer/composer (2.2.0-RC1) from cache
  - Upgrading seld/phar-utils (1.1.2 => 1.2.0): Extracting archive
Executing async command (CWD): rm -rf '/Users/max/git/tools/composer/vendor/seld/phar-utils'
  - Upgrading composer/composer (2.1.14 => 2.2.0-RC1): Extracting archive
Executing async command (CWD): rm -rf '/Users/max/git/tools/composer/vendor/composer/composer'
Executing async command (CWD): '/usr/bin/unzip' -qq '/Users/max/git/tools/composer/vendor/composer/tmp-c7ec096272e85b619c0b60bb615d4fee' -d '/Users/max/git/tools/composer/vendor/composer/d686cf7f'
Executing async command (CWD): rm -rf '/Users/max/git/tools/composer/vendor/composer/d686cf7f'
Executing async command (CWD): '/usr/bin/unzip' -qq '/Users/max/git/tools/composer/vendor/composer/tmp-b87d1b0c13d070da940a2e425eca7952' -d '/Users/max/git/tools/composer/vendor/composer/49678fc6'
Executing async command (CWD): rm -rf '/Users/max/git/tools/composer/vendor/composer/49678fc6'
Downloading https://packagist.org/downloads/
[201] https://packagist.org/downloads/
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Util\Platform::getEnv() in /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/GithubActionError.php:39
Stack trace:
#0 /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/Application.php(345): Composer\Console\GithubActionError->emit('file_get_conten...')
#1 /Users/max/git/tools/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/max/git/tools/composer/vendor/composer/composer/bin/composer(73): Composer\Console\Application->run()
#4 /Users/max/git/tools/composer/vendor/bin/composer(92): include('/Users/max/git/... in /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/GithubActionError.php on line 39

Fatal error: Uncaught Error: Call to undefined method Composer\Util\Platform::getEnv() in /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/GithubActionError.php:39
Stack trace:
#0 /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/Application.php(345): Composer\Console\GithubActionError->emit('file_get_conten...')
#1 /Users/max/git/tools/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/max/git/tools/composer/vendor/composer/composer/bin/composer(73): Composer\Console\Application->run()
#4 /Users/max/git/tools/composer/vendor/bin/composer(92): include('/Users/max/git/... in /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/GithubActionError.php on line 39
```

And I expected this to happen:

No fatal error occurs.

**Comment by stof** [comment]
Installing `composer/composer` as a dependency can lead to weird issues in plugins when the code from the package installed in the vendor folder is loaded in the same process than the code of the phar, that probably contains an older version of composer.
Which version of composer are you using to **run** composer ?

Side note: if you use composer to manage your dependencies, you probably don't need to install the `composer/composer` package in your composer.json.

**Comment by boesing** [comment]
As per the output, at the very moment I execute `composer update`, I use `Running 2.1.14 (2021-11-30 10:51:43) with PHP 7.4.26 on Darwin / 20.3.0`.

So actually, use composer to update composer which updates the composer which runs under the hood.
I guess I should switch to the `phar` but until now, I was not really able to test non-stable versions.

So maybe I should just avoid using this setup but still wanted to raise this possible problem even tho it might be a problem on my side. 👍🏼

**Comment by stof** [comment]
Well, installing composer itself as a composer global package is indeed not the supported installation method (and is likely to cause such issue when the code of composer gets changed while it is running). Thus, it means you don't actually rely on the locked dependencies of composer, which gives you a different environment than most composer users.

The phar is the way to install composer (and there, `composer self-update` is taking care of this issue about changing composer itself while it is running, because it is specifically about that).
Thus, for your unusual setup, you probably had to download the phar anyway for the initial setup.

**Comment by Seldaek** [comment]
Yeah running composer to update composer tends to run into issues. I regularly have to use the phar to run `composer install` when switching branches on this repo otherwise dependencies switching in the middle of the process tends to create problems.

**Comment by boesing** [comment]
Thanks for the feedback.
The only reason why I've used this method was to ensure that I can install v2 & v1 simultanously (while having aliases to the v1 version).

I guess I simply switch these to phars instead.

**Comment by stof** [comment]
@boesing you can have multiple phars installed locally too.
