### ISSUE TITLE
composer v2.2.0 install fail on magento2-module with allowed plugin

### ISSUE THREAD

**Issue by MateusDadalto** [composer/composer#10390]
My `composer.json`:

```json
{
    "name": "mateusd/demo-project",
    "type": "magento2-module",
    "license": "UNLICENSED",
    "autoload": {
        "psr-4": {
            "Mateusd\\Demo\\": ""
        },
        "files": [
            "registration.php"
        ]
    },
    "require": {
        "magento/framework": "^103.0",
        "magento/module-quote-graph-ql": "^100.0",
        "webonyx/graphql-php": "^0.13.8"
    },
    "require-dev": {
        "squizlabs/php_codesniffer": "^3.6",
        "magento/magento-coding-standard": "^6",
        "phpunit/phpunit": "^9.5",
        "fooman/phpstan-magento2-magic-methods": "^0.7.3"
    },
    "repositories": {
        "magento": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    },
    "config": {
        "allow-plugins": {
            "phpstan/extension-installer": true
        }
    }
}
```

Output of `composer diagnose`:

```
.PHP Fatal error:  Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /home/mateus/Documents/graycore/projects/composer/registration.php:5
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1422): require()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(249): Composer\Autoload\composerRequire()
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(474): Composer\Plugin\PluginManager->registerPackage()
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(102): Composer\Plugin\PluginManager->loadRepository()
#4 phar:///usr/local/bin/composer/src/Composer/Factory.php(439): Composer\Plugin\PluginManager->loadInstalledPlugins()
#5 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(444): Composer\Factory::create()
#7 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65 in /home/mateus/Documents/graycore/projects/composer/registration.php on line 5

Fatal error: Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /home/mateus/Documents/graycore/projects/composer/registration.php:5
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1422): require()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(249): Composer\Autoload\composerRequire()
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(474): Composer\Plugin\PluginManager->registerPackage()
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(102): Composer\Plugin\PluginManager->loadRepository()
#4 phar:///usr/local/bin/composer/src/Composer/Factory.php(439): Composer\Plugin\PluginManager->loadInstalledPlugins()
#5 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(444): Composer\Factory::create()
#7 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65 in /home/mateus/Documents/graycore/projects/composer/registration.php on line 5
```

When I run this command: 

```
composer install -vvv
```

I get the following output: 

```
Running 2.2.0 (2021-12-22 11:03:27) with PHP 7.4.26 on Linux / 5.11.0-41-generic
Reading ./composer.json (/home/mateus/Documents/graycore/projects/composer/composer.json)
Loading config file /home/mateus/.config/composer/auth.json
Loading config file ./composer.json (/home/mateus/Documents/graycore/projects/composer/composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/mateus/Documents/graycore/projects/composer): git branch -a --no-color --no-abbrev -v
Reading /home/mateus/.config/composer/composer.json
Loading config file /home/mateus/.config/composer/auth.json
Loading config file /home/mateus/.config/composer/composer.json (/home/mateus/.config/composer/composer.json)
Loading config file /home/mateus/.config/composer/auth.json
Reading /home/mateus/.config/composer/auth.json
Reading /home/mateus/Documents/graycore/projects/composer/vendor/composer/installed.json
PHP Fatal error:  Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /home/mateus/Documents/graycore/projects/composer/registration.php:5
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1422): require()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(249): Composer\Autoload\composerRequire()
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(474): Composer\Plugin\PluginManager->registerPackage()
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(102): Composer\Plugin\PluginManager->loadRepository()
#4 phar:///usr/local/bin/composer/src/Composer/Factory.php(439): Composer\Plugin\PluginManager->loadInstalledPlugins()
#5 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(444): Composer\Factory::create()
#7 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65 in /home/mateus/Documents/graycore/projects/composer/registration.php on line 5

Fatal error: Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /home/mateus/Documents/graycore/projects/composer/registration.php:5
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1422): require()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(249): Composer\Autoload\composerRequire()
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(474): Composer\Plugin\PluginManager->registerPackage()
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(102): Composer\Plugin\PluginManager->loadRepository()
#4 phar:///usr/local/bin/composer/src/Composer/Factory.php(439): Composer\Plugin\PluginManager->loadInstalledPlugins()
#5 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(444): Composer\Factory::create()
#7 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65 in /home/mateus/Documents/graycore/projects/composer/registration.php on line 5
```

And I expected this to happen:
I expected it worked the same way `composer install` works on v2.1.14

**Comment by MateusDadalto** [comment]
I've setup a demo repo to show this issue happening https://github.com/MateusDadalto/composer-demo

**Comment by stof** [comment]
Please run `composer self-update --snapshot` to get the latest snapshot build of composer and try again. I'm quite sure that this is the same issue than #10382 and so #10386 should fix it.

**Comment by MateusDadalto** [comment]
@stof Yep, it worked :sweat_smile: 
I'll close it then, thanks!
