### ISSUE TITLE
Can't do anything with composer

### ISSUE THREAD

**Issue by isaactsl** [composer/composer#10544]
Output of `composer`:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Composer\XdebugHandler\putenv() in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php:93
Stack trace:
#0 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Status.php(48): Composer\XdebugHandler\Process::setEnv()
#1 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php(83): Composer\XdebugHandler\Status->__construct()
#2 phar:///usr/bin/composer/bin/composer(16): Composer\XdebugHandler\XdebugHandler->__construct()
#3 /usr/bin/composer(24): require('...')
#4 {main}
  thrown in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php on line 93

Fatal error: Uncaught Error: Call to undefined function Composer\XdebugHandler\putenv() in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php:93
Stack trace:
#0 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Status.php(48): Composer\XdebugHandler\Process::setEnv()
#1 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php(83): Composer\XdebugHandler\Status->__construct()
#2 phar:///usr/bin/composer/bin/composer(16): Composer\XdebugHandler\XdebugHandler->__construct()
#3 /usr/bin/composer(24): require('...')
#4 {main}
  thrown in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php on line 93
```

I get the following output: 

```
same ^
```

**Comment by herndlm** [comment]
I assume this happens only in a specific project? Can you provide a `composer.json` to replicate it? Also, which composer version are you using?

I think there should be an issue template that asks these questions and it would help the maintainers much if you can provide that data.

**Comment by isaactsl** [comment]
No, I can't use composer command in / dir as well. 
This is `composer.json` in my project:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^9.0",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.3.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

This happened after upgrading PHP 7 to PHP 8. Current version: 8.0.14

**Comment by Seldaek** [comment]
Looks like the putenv function is missing but it should be part of core php so unless you have a strange custom built php with disabled core extensions, I would check the php.ini for disable_functions see if it has getenv there for some odd reason

**Comment by Seldaek** [comment]
Alternatively you can try to run this and share the full output maybe it helps

"COMPOSER_ALLOW_XDEBUG=1 composer diagnose -vvv"

**Comment by isaactsl** [comment]
> Looks like the putenv function is missing but it should be part of core php so unless you have a strange custom built php with disabled core extensions, I would check the php.ini for disable_functions see if it has putenv there for some odd reason

I checked settings, putenv really has been disabled! Now it works! Thanks!!! 👍
