### ISSUE TITLE
Return value of `CompositeRepository::findPackage()` have changed in 2.3.0

### ISSUE THREAD

**Issue by boesing** [composer/composer#10622]
Hey there,

I've quickly checked out composer v2.3.0 and ended up in an fatal error when working with a composer plugin which uses the `CompositeRepository` to find a package by its name.

I doubt that it is plugin related as we do not have any influence on what is actually returned from that composite repository.

### Here is the related code which leads to the fatal error
https://github.com/laminas/laminas-component-installer/blob/4a882e650d8a280b2f33b65b493e25d9e0bccbd3/src/PackageProvider/PackageProviderDetectionFactory.php#L52

### The fatal error

```
PHP Fatal error:  Uncaught TypeError: Return value of Composer\Repository\CompositeRepository::findPackage() must be an instance of Composer\Package\BasePackage or null, bool returned in phar:///Users/max/.bin/composer/src/Composer/Repository/CompositeRepository.php:84
Stack trace:
#0 /project/vendor/laminas/laminas-component-installer/src/PackageProvider/PackageProviderDetectionFactory.php(69): Composer\Repository\CompositeRepository->findPackage('mobilfunk-hardw...', '*')
#1 /project/vendor/laminas/laminas-component-installer/src/ComponentInstaller.php(228): Laminas\ComponentInstaller\PackageProvider\PackageProviderDetectionFactory->detect(Object(Composer\Installer\PackageEvent), 'mobilfunk-hardw...')
#2 [internal function]: Laminas\ComponentInstaller\ComponentInstaller->onPostPackageInstall(Object(Composer\Installer\PackageEvent))
#3 phar:///Users/max/.bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(199): call_user_func(Array, Object(Composer\Installer\PackageEve in phar:///Users/max/.bin/composer/src/Composer/Repository/CompositeRepository.php on line 84
```

Happy to be of help if you need further details.

**Comment by Seldaek** [comment]
Thanks for pinpointing it, easy fix :)
