### ISSUE TITLE
[2.3.0RC1] Return value must be of type string, bool returned in /usr/share/php/Composer/Platform/Runtime.php:101

### ISSUE THREAD

**Issue by remicollet** [composer/composer#10631]
When [awscrt](https://pecl.php.net/package/awscrt) extension is installed

```
$ composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information

Fatal error: Uncaught TypeError: Composer\Platform\Runtime::getExtensionVersion(): Return value must be of type string, bool returned in /usr/share/php/Composer/Platform/Runtime.php:101
Stack trace:
#0 /usr/share/php/Composer/Repository/PlatformRepository.php(196): Composer\Platform\Runtime->getExtensionVersion('awscrt')
#1 /usr/share/php/Composer/Repository/ArrayRepository.php(311): Composer\Repository\PlatformRepository->initialize()
#2 /usr/share/php/Composer/Installer.php(899): Composer\Repository\ArrayRepository->getPackages()
#3 /usr/share/php/Composer/Installer.php(428): Composer\Installer->createRequest(Object(Composer\Package\RootPackage), Object(Composer\Repository\PlatformRepository), NULL)
#4 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#5 /usr/share/php/Composer/Command/InstallCommand.php(137): Composer\Installer->run()
#6 /usr/share/php/Composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /usr/share/php/Composer/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/share/php/Composer/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /usr/share/php/Composer/Console/Application.php(332): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /usr/share/php/Composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/share/php/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/bin/composer(84): Composer\Console\Application->run()
#13 {main}
  thrown in /usr/share/php/Composer/Platform/Runtime.php on line 101

```

And 

```
$ php -r 'var_dump(phpversion("awscrt"));'
bool(false)

```

**Comment by Seldaek** [comment]
Thanks for the exotic find :)

**Comment by laurinkeithdavis** [comment]
```
C:\inetpub\test>php test.php
﻿
curl

cURL support => enabled
cURL Information => 7.80.0
Age => 9
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => No
SPNEGO => Yes
SSL => Yes
SSPI => Yes
TLS-SRP => No
HTTP2 => Yes
GSSAPI => No
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => No
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-pc-win32
SSL Version => OpenSSL/1.1.1l (Schannel)
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => c:\PHP\cacert.pem => c:\PHP\cacert.pem
```

**Comment by wasinr** [comment]
> @laurinkeithdavis ok thanks, see the commits linked above, please try with `composer self-update --snapshot` if it fixes it for you.

Thank for this solution.
