### ISSUE TITLE
Crash on composer remove with Composer 2.3.0-RC1

### ISSUE THREAD

**Issue by hmazter** [composer/composer#10634]
My `composer.json`:

```json
{
    "name": "kristoffer/composer-test",
    "require-dev": {
        "spatie/laravel-ignition": "^1.0"
    }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.3.0-RC1
PHP version: 8.1.4
PHP binary path: /opt/homebrew/Cellar/php/8.1.4/bin/php
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021
cURL version: 7.82.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1m
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer remove spatie/laravel-ignition --dev -vvv
```

I get the following output:

```
Running 2.3.0-RC1 (2022-03-16 09:25:31) with PHP 8.1.4 on Darwin / 21.4.0
Reading ./composer.json (/Users/kristoffer/code/composer-test/composer.json)
Loading config file /Users/kristoffer/.composer/auth.json
Loading config file ./composer.json (/Users/kristoffer/code/composer-test/composer.json)
Checked CA file /opt/homebrew/etc/ca-certificates/cert.pem: valid
Executing command (/Users/kristoffer/code/composer-test): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Executing command (/Users/kristoffer/code/composer-test): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/Users/kristoffer/code/composer-test): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/kristoffer/code/composer-test): hg branch
Executing command (/Users/kristoffer/code/composer-test): fossil branch list
Executing command (/Users/kristoffer/code/composer-test): fossil tag list
Executing command (/Users/kristoffer/code/composer-test): svn info --xml
Reading /Users/kristoffer/.composer/composer.json
Loading config file /Users/kristoffer/.composer/auth.json
Loading config file /Users/kristoffer/.composer/composer.json (/Users/kristoffer/.composer/composer.json)
Loading config file /Users/kristoffer/.composer/auth.json
Reading /Users/kristoffer/.composer/auth.json
Reading /Users/kristoffer/code/composer-test/vendor/composer/installed.json
Reading /Users/kristoffer/.composer/vendor/composer/installed.json
Skipped loading "composer/package-versions-deprecated" (installed globally) as it is not in config.allow-plugins
./composer.json has been updated
Reading ./composer.json (/Users/kristoffer/code/composer-test/composer.json)
Loading config file /Users/kristoffer/.composer/auth.json
Loading config file ./composer.json (/Users/kristoffer/code/composer-test/composer.json)
Executing command (/Users/kristoffer/code/composer-test): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Executing command (/Users/kristoffer/code/composer-test): git describe --exact-match --tags
Executing command (/Users/kristoffer/code/composer-test): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/kristoffer/code/composer-test): hg branch
Executing command (/Users/kristoffer/code/composer-test): fossil branch list
Executing command (/Users/kristoffer/code/composer-test): fossil tag list
Executing command (/Users/kristoffer/code/composer-test): svn info --xml
Reading /Users/kristoffer/.composer/composer.json
Loading config file /Users/kristoffer/.composer/auth.json
Loading config file /Users/kristoffer/.composer/composer.json (/Users/kristoffer/.composer/composer.json)
Loading config file /Users/kristoffer/.composer/auth.json
Reading /Users/kristoffer/.composer/auth.json
Reading /Users/kristoffer/code/composer-test/vendor/composer/installed.json
Reading /Users/kristoffer/.composer/vendor/composer/installed.json
Skipped loading "composer/package-versions-deprecated" (installed globally) as it is not in config.allow-plugins

Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in phar:///usr/local/bin/composer/src/Composer/Command/RemoveCommand.php:238
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Command/RemoveCommand.php(238): array_keys(NULL)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\RemoveCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\RemoveCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(332): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/local/bin/composer/bin/composer(83): Composer\Console\Application->run()
#8 /usr/local/bin/composer(29): require('phar:///usr/loc...')
#9 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Command/RemoveCommand.php on line 238
```

And I expected this to happen:
I expect the command to remove the package from `composer.json` and `composer.lock` and not crash.

**Comment by Seldaek** [comment]
Thanks, already fixed in https://github.com/composer/composer/commit/ca3b8744144ec223aa87f90aec7aa7c7be0b73bc though :) You can use snapshots for the latest & greatest code `composer self-update --snapshot`

**Comment by hmazter** [comment]
Sorry, did not occur to test the lastest snapshot, just made sure I was on the last `--preview`
