### ISSUE TITLE
(Windows) Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource

### ISSUE THREAD

**Issue by foremtehan** [composer/composer#10640]
At this time none of the composer commands works for me.

I'm using laravel 9 in windows env:

```
Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php:71
Stack trace:
#0 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php(71): fclose(false)
#1 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php(194): Symfony\Component\Process\Pipes\WindowsPipes->__construct(false, NULL)
#2 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Process.php(1231): Symfony\Component\Process\Pipes\WindowsPipes::create(Object(Symfony\Component\Process\Process), NULL)
#3 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Process.php(258): Symfony\Component\Process\Process->getDescriptors()
#4 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Process.php(196): Symfony\Component\Process\Process->start(Array)
#5 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/ProcessExecutor.php(136): Symfony\Component\Process\Process->run(Array)
#6 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/ProcessExecutor.php(74): Composer\Util\ProcessExecutor->doExecute('git branch -a -...', 'C:\\xampp\\htdocs...', false, NULL)
#7 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Package/Version/VersionGuesser.php(140): Composer\Util\ProcessExecutor->execute('git branch -a -...', NULL, 'C:\\xampp\\htdocs...')
#8 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Package/Version/VersionGuesser.php(75): Composer\Package\Version\VersionGuesser->guessGitVersion(Array, 'C:\\xampp\\htdocs...')
#9 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Package/Loader/RootPackageLoader.php(91): Composer\Package\Version\VersionGuesser->guessVersion(Array, 'C:\\xampp\\htdocs...')
#10 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php(403): Composer\Package\Loader\RootPackageLoader->load(Array, 'Composer\\Packag...', 'C:\\xampp\\htdocs...')
#11 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php(643): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, true, 'C:\\xampp\\htdocs...', true, true)
#12 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php(445): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, true, true)
#13 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/BaseCommand.php(65): Composer\Console\Application->getComposer(false, true, true)
#14 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/BaseCommand.php(150): Composer\Command\BaseCommand->getComposer(false, true, true)
#15 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php(211): Composer\Command\BaseCommand->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\SelfUpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compone
nt\Console\Output\ConsoleOutput))
#18 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer(83): Composer\Console\Application->run()
#22 C:\ProgramData\ComposerSetup\bin\composer.phar(29): require('phar://C:/Progr...')
#23 {main}
  thrown in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php on line 71

```

**Comment by foremtehan** [comment]
restarting the pc did the trick, dont know what cause this

**Comment by Seldaek** [comment]
If you can reproduce it again please try with `composer self-update --snapshot` to see if the latest version of Composer fixes it. In the meantime closing as we really cannot do much here without a repro case.

**Comment by foremtehan** [comment]
none of the composer commands will work if such a error happen even `composer self-update --snapshot`

**Comment by timyourivh** [comment]
Tip for not having to restart your pc:

1. Open task manager
2. Click "more details" (if you haven't already)
3. Go to the "Details" tab
4. Kill all `php.exe` instances (can be easily found by just typing php)

This will force all applications using php to restart their php instance.

**Comment by foremtehan** [comment]
@timyourivh i have the same problem right now, I type `php` in detail tab but there is no php process here

**Comment by foremtehan** [comment]
Okay i know what it is. I was running a headless chrome and it was using php, so i close them i issue solved.
