### ISSUE TITLE
Composer 2.3 PATH unavailable causing error with Preg::isMatch

### ISSUE THREAD

**Issue by jasonvarga** [composer/composer#10662]
In our CMS, Statamic, we use Composer within our admin panel to allow users to update via the browser.
We use Symfony Process to execute Composer commands using whatever composer binary is in the vendor directory.

When running Composer 2.3 (and composer/pcre 3) to perform a `composer require`, it fails with the following stack trace.

The actual command being run behind the scenes is:

```
/path/to/php -d memory_limit=-1 vendor/bin/composer --no-ansi require statamic/cms 3.3.2 --update-with-dependencies
```

```
./composer.json has been updated
Running composer update statamic/cms --with-dependencies

Fatal error: Uncaught TypeError: Composer\Pcre\Preg::isMatch(): Argument #2 ($subject) must be of type string, bool given, called in /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 580 and defined in /Users/jason/Code/statamic/three/sandbox/vendor/composer/pcre/src/Preg.php:233
Stack trace:
#0 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(580): Composer\Pcre\Preg::isMatch('{(^|:)/Users/ja...', false)
#1 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(188): Composer\EventDispatcher\EventDispatcher->ensureBinDirIsInPath()
#2 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(122): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/Installer.php(269): Composer\EventDispatcher\EventDispatcher->dispatchScript('pre-update-cmd', true)
#4 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/Command/RequireCommand.php(425): Composer\Installer->run()
#5 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/Command/RequireCommand.php(288): Composer\Command\RequireCommand->doUpdate(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Composer\IO\ConsoleIO), Array, 'require', 'require-dev')
#6 /Users/jason/Code/statamic/three/sandbox/vendor/symfony/console/Command/Command.php(291): Composer\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/jason/Code/statamic/three/sandbox/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/jason/Code/statamic/three/sandbox/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\RequireCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/Console/Application.php(332): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/jason/Code/statamic/three/sandbox/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/jason/Code/statamic/three/sandbox/vendor/composer/composer/bin/composer(84): Composer\Console\Application->run()
#13 /Users/jason/Code/statamic/three/sandbox/vendor/bin/composer(117): include('/Users/jason/Co...')
#14 {main}
  thrown in /Users/jason/Code/statamic/three/sandbox/vendor/composer/pcre/src/Preg.php on line 233
```

The issue appears to be that `Platform::getEnv('PATH')` returns `false` in the browser (or at least in our implementation).

(On the command line, it gets the `PATH` just fine.)

Since adding the `string` typehint to `Preg::isMatch()` in [this commit](https://github.com/composer/pcre/commit/2e56743e50b72279aeb01ed2c9fcbf9f9d7a92d6#diff-bb14c3a990a362b214b58d517ae83ac1d860f15846030e075042d63e904238e6R243) it now fails because `false` is being passed in.

Previously, I guess it would silently fail? I'm not sure what `ensureBinDirIsInPath` was attempting to do, but everything seemed fine before.

Please let me know what other information I can provide. Thanks!

**Comment by Seldaek** [comment]
Thanks for the report
