### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer/src/Composer/Config.php:192

### ISSUE THREAD

**Issue by Ahummeling** [composer/composer#10910]
Hi, after running `composer self-update --snapshot` along with a regular system update (`apt upgrade`), I seem to be consistently crashing composer. I was unable to an existing issue for this, if one already exists please let me know and sorry for the trouble.

My `composer.json`:
This error occurs regardless of cwd and its contents it seems. Please let me know if there's some global composer.json file that exists somewhere, so I can include it.
```json
```

Output of `composer diagnose`:

```
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer/src/Composer/Config.php:192
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Config.php(192): array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(189): Composer\Config->merge()
#2 phar:///usr/local/bin/composer/src/Composer/Factory.php(325): Composer\Factory::createConfig()
#3 phar:///usr/local/bin/composer/src/Composer/Factory.php(615): Composer\Factory->createComposer()
#4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(470): Composer\Factory::create()
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(412): Composer\Console\Application->getComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#10 /usr/local/bin/composer(29): require('...')
#11 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Config.php on line 192

Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer/src/Composer/Config.php:192
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Config.php(192): array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(189): Composer\Config->merge()
#2 phar:///usr/local/bin/composer/src/Composer/Factory.php(325): Composer\Factory::createConfig()
#3 phar:///usr/local/bin/composer/src/Composer/Factory.php(615): Composer\Factory->createComposer()
#4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(470): Composer\Factory::create()
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(412): Composer\Console\Application->getComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#10 /usr/local/bin/composer(29): require('...')
#11 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Config.php on line 192
```

When I run this command: 
Crash seems to occur before arguments are parsed 
```
composer
```

I get the following output: 
```
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer/src/Composer/Config.php:192
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Config.php(192): array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(189): Composer\Config->merge()
#2 phar:///usr/local/bin/composer/src/Composer/Factory.php(325): Composer\Factory::createConfig()
#3 phar:///usr/local/bin/composer/src/Composer/Factory.php(615): Composer\Factory->createComposer()
#4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(470): Composer\Factory::create()
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(412): Composer\Console\Application->getComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#10 /usr/local/bin/composer(29): require('...')
#11 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Config.php on line 192

Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer/src/Composer/Config.php:192
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Config.php(192): array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(189): Composer\Config->merge()
#2 phar:///usr/local/bin/composer/src/Composer/Factory.php(325): Composer\Factory::createConfig()
#3 phar:///usr/local/bin/composer/src/Composer/Factory.php(615): Composer\Factory->createComposer()
#4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(470): Composer\Factory::create()
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(412): Composer\Console\Application->getComposer()
#6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#10 /usr/local/bin/composer(29): require('...')
#11 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Config.php on line 192
```

And I expected this to happen:

I suppose I'd expect the output one would normally see when running `composer` or `composer list`, not a PHP fatal error.

Interestingly, I am able to run `composer --version` and `composer -vvv --version`, yielding the following output:
```
composer --version -vvv
Running 2.3.7 (2022-06-06 16:43:28) with PHP 8.1.7 on Linux / 5.18.0-1-amd64
Composer version 2.3.7 2022-06-06 16:43:28
```

**Comment by beeyev** [comment]
I have the same problem,it appeared today

**Comment by mathiasonea** [comment]
Same here, but I didn't update composer. I am running `2.2.7`
How come, this is happening even on not updated instances?

**Comment by Ahummeling** [comment]
Oh yes that makes sense.
Perhaps throwing a RuntimeException, rather than triggering a PHP Fatal error would make more sense in this case?
