### ISSUE TITLE
Uncaught Error: Call to undefined function Composer\Console\disk_free_space() in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php:417

### ISSUE THREAD

**Issue by webprogrammierer** [composer/composer#10936]
I get this error message after the command 

php composer.phar install

```

> post-install-cmd: Drupal\Composer\Plugin\Scaffold\Plugin->postCmd
Scaffolding files for drupal/core:
  - Copy [web-root]/.htaccess from assets/scaffold/files/htaccess
PHP Fatal error:  Uncaught Error: Call to undefined function Composer\Console\disk_free_space() in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php:417
Stack trace:
#0 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#1 phar:///web/my-project.com/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#2 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#3 phar:///web/my-project.com/composer.phar/bin/composer(88): Composer\Console\Application->run()
#4 /web/my-project.com/composer.phar(29): require('...')
#5 {main}
  thrown in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php on line 417

Fatal error: Uncaught Error: Call to undefined function Composer\Console\disk_free_space() in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php:417 Stack trace:
#0 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#1 phar:///web/my-project.com/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#2 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#3 phar:///web/my-project.com/composer.phar/bin/composer(88): Composer\Console\Application->run()
#4 /web/my-project.com/composer.phar(29): require('...')
#5 {main}
  thrown in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php on line 417
```
  
I also get this after this command 

php composer.phar --selfupdate

```
PHP Fatal error:  Uncaught Error: Call to undefined function Composer\Console\disk_free_space() in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php:417
Stack trace:
#0 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#1 phar:///web/my-project.com/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#2 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#3 phar:///web/my-project.com/composer.phar/bin/composer(88): Composer\Console\Application->run()
#4 /web/my-project.com/composer.phar(29): require('...')
#5 {main}
  thrown in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php on line 417

Fatal error: Uncaught Error: Call to undefined function Composer\Console\disk_free_space() in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php:417 Stack trace:
#0 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(353): Composer\Console\Application->hintCommonErrors()
#1 phar:///web/my-project.com/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#2 phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#3 phar:///web/my-project.com/composer.phar/bin/composer(88): Composer\Console\Application->run()
#4 /web/my-project.com/composer.phar(29): require('...')
#5 {main}
  thrown in phar:///web/my-project.com/composer.phar/src/Composer/Console/Application.php on line 417
  
  
```
  

PHP version: PHP 8.1.3
Composer version: Composer version 2.3.9 2022-07-05 16:52:1

How can I solve this problem?

**Comment by Seldaek** [comment]
Next release will avoid calling disk_free_space if not possible.. But I guess the root cause here is that you have the function present in disable_functions in php.ini. I don't know why as this is a rather harmless function, maybe your web host did this for some reason.

**Comment by Seldaek** [comment]
https://github.com/composer/composer/releases/tag/2.3.10 is now released

**Comment by webprogrammierer** [comment]
Great! Thank your very much.
