### ISSUE TITLE
Composer doesn't gracefully handle config.json being unreadable

### ISSUE THREAD

**Issue by dkarlovi** [composer/composer#11077]
My `composer.json`:

N/A

Output of `composer diagnose`:

```
PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, bool given in /usr/share/php/Composer/Json/JsonFile.php:194
Stack trace:
#0 /usr/share/php/Composer/Json/JsonFile.php(194): json_decode()
#1 /usr/share/php/Composer/Factory.php(721): Composer\Json\JsonFile->validateSchema()
#2 /usr/share/php/Composer/Factory.php(186): Composer\Factory::validateJsonSchema()
#3 /usr/share/php/Composer/Factory.php(330): Composer\Factory::createConfig()
#4 /usr/share/php/Composer/Factory.php(625): Composer\Factory->createComposer()
#5 /usr/share/php/Composer/Console/Application.php(498): Composer\Factory::create()
#6 /usr/share/php/Composer/Console/Application.php(443): Composer\Console\Application->getComposer()
#7 /usr/share/php/Composer/Console/Application.php(388): Composer\Console\Application->hintCommonErrors()
#8 /usr/share/php/Composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#9 /usr/share/php/Composer/Console/Application.php(138): Symfony\Component\Console\Application->run()
#10 /usr/bin/composer(89): Composer\Console\Application->run()
#11 {main}
  thrown in /usr/share/php/Composer/Json/JsonFile.php on line 194

```

When I run this command: 

I get the following output: 

Same as above

And I expected this to happen:

Warn about being unable to read $COMPOSER_HOME/config.json

## Reproducer

```
$ chmod 000 ~/.composer/config.json
$ composer diagnose
```

**Comment by ciaranmcnulty** [comment]
Looks like Factory validates the file before creating a JsonConfigSource  - if the file is manipulated or read later it gets validated https://github.com/composer/composer/blame/main/src/Composer/Config/JsonConfigSource.php#L217

**Comment by ferdiusa** [comment]
The commit by Seldaek used is_readable instead of Filesystem::isReadable and will not work on network shares (SMB). see [#8231](https://github.com/composer/composer/issues/8231). Please update to Filesystem::isReadable and verify again, thank you!
