### ISSUE TITLE
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255

### ISSUE THREAD

**Issue by kiuchi512** [composer/composer#11192]
My ```composer.json```
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```
when I run this command:
```composer install```
```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - doctrine/instantiator is locked to version 1.0.5 and an update of this package was not requested.
    - doctrine/instantiator 1.0.5 requires php >=5.3,<8.0-DEV -> your php version (8.0.25) does not satisfy that requirement.
  Problem 2
    - phpspec/prophecy is locked to version v1.6.0 and an update of this package was not requested.
    - phpspec/prophecy v1.6.0 requires php ^5.3|^7.0 -> your php version (8.0.25) does not satisfy that requirement.
  Problem 3
    - doctrine/instantiator 1.0.5 requires php >=5.3,<8.0-DEV -> your php version (8.0.25) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 2.3.8 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.0.5].
    - phpunit/phpunit-mock-objects is locked to version 2.3.8 and an update of this package was not requested.

```
when I run this command:
```composer update```
```
> php artisan clear-compiled
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 798

Deprecated: Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 798
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 853

Deprecated: Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 853
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 798

Deprecated: Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 798
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 853

Deprecated: Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 853
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php:798
Stack trace:
#0 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(798): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Method Reflecti...', '/Users/kiuchiko...', 798)
#1 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(778): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('App\\Exceptions\\...', Array)
#3 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(230): Illuminate\Foundation\Application->make('App\\Exceptions\\...', Array)
#5 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#6 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#7 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#8 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#9 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#11 {main}
  thrown in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 798
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php:798
Stack trace:
#0 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(798): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Method Reflecti...', '/Users/kiuchiko...', 798)
#1 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(778): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('App\\Exceptions\\...', Array)
#3 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(230): Illuminate\Foundation\Application->make('App\\Exceptions\\...', Array)
#5 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#6 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#7 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#8 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#9 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#11 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#12 {main}
  thrown in /Users/kiuchikoutarou/laravel/quickstart/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 798
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255
```
I conducted a lot of solutions to solve this problem, but they didn't work. Please help me. Thank you for spending your time to help me.

**Comment by Seldaek** [comment]
Looks like you have an outdated dependency.. Maybe try to update laravel/framework to a version compatible with your PHP version with --no-scripts to make sure the artisan command is not run before the update.
