### ISSUE TITLE
Local symlinked path repository not up-to-date with installed.json

### ISSUE THREAD

**Issue by llaville** [composer/composer#11527]
Hello,

I'm currently developing a Composer plugin (compatible 2.3 or greater) and found probably an issue with symlinked path local repository.

Here are my directory structure : 

/shared/backups/bartlett/manifests => main composer plugin source code 
/shared/backups/bartlett/manifests/demo/.tools => a demonstration composer usage with symlinked path repository

On main composer plugin, I've updated constraints to be compatible plugin API 2.3

<details>

<summary>composer.json</summary>

```json
{
    "name": "bartlett/manifests",
    "description": "Composer plugin that creates manifests for a PHP Archive (PHAR)",
    "type": "composer-plugin",
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Bartlett\\Manifests\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Bartlett\\Manifests\\Tests\\": "tests/"
        }
    },
    "authors": [
        {
            "name": "Laurent Laville",
            "role": "Lead Developer"
        }
    ],
    "prefer-stable": true,
    "minimum-stability": "stable",
    "require": {
        "php": "^7.2.5 || ^8.0",
        "ext-json": "*",
        "composer-plugin-api": "^2.3"
    },
    "require-dev": {
        "bamarni/composer-bin-plugin": "^1.8",
        "composer/composer": "^2.3",
        "symfony/phpunit-bridge": "^5.4 || ^6.0"
    },
    "suggest": {
        "ext-simplexml": "Needed to support XML format with CycloneDX builder/loader",
        "ext-libxml": "Needed to support XML format with CycloneDX builder/loader",
        "cyclonedx/cyclonedx-library": "Needed to support SBOM CycloneDX format",
        "phar-io/manifest": "Needed to support PHIVE format"
    },
    "config": {
        "optimize-autoloader": false,
        "sort-packages": true,
        "allow-plugins": {
            "bamarni/composer-bin-plugin": true
        }
    },
    "extra": {
        "bamarni-bin": {
            "bin-links": true,
            "forward-command": false,
            "target-directory": "vendor-bin"
        },
        "class": "Bartlett\\Manifests\\Plugin",
        "branch-alias": {
            "dev-master": "1.x-dev"
        }
    }
}
```

</details>

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.30.2
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.8
PHP version: 8.0.27
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
cURL version: 7.74.0 libz 1.2.11 ssl OpenSSL/1.1.1n
zip: extension present, unzip present, 7-Zip not available
```

But when I update the demonstration folder (demo/.tools) with `composer update -vvv --no-plugins` command, I got following 

<details>

<summary>command results</summary>

```
Running 2.5.8 (2023-06-09 17:13:21) with PHP 8.0.27 on Linux / 5.15.90.1-microsoft-standard-WSL2
Reading ./composer.json (/shared/backups/bartlett/manifests/demo/.tools/composer.json)
Loading config file ./composer.json (/shared/backups/bartlett/manifests/demo/.tools/composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/shared/backups/bartlett/manifests/demo/.tools): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Failed to initialize global composer: Composer could not find the config file: /home/devilbox/.composer/composer.json

Reading /shared/backups/bartlett/manifests/demo/.tools/vendor/composer/installed.json
Reading ./composer.lock (/shared/backups/bartlett/manifests/demo/.tools/composer.lock)
Loading composer repositories with package information
Executing command (CWD): git --version
Executing command (/shared/backups/bartlett/manifests/): git log -n1 --pretty=%H --no-show-signature
Executing command (/shared/backups/bartlett/manifests/): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Built pool.
Running pool optimizer.
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Analyzed 135 packages to resolve dependencies
Analyzed 139 rules to resolve dependencies
Nothing to modify in lock file
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
Reading /home/devilbox/.composer/cache/repo/https---repo.packagist.org/packages.json from cache
Downloading https://repo.packagist.org/packages.json if modified
[200] https://repo.packagist.org/packages.json
Info from https://repo.packagist.org: #StandWithUkraine
Writing /home/devilbox/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Downloading https://repo.packagist.org/p2/bartlett/manifests.json
[404] https://repo.packagist.org/p2/bartlett/manifests.json
Downloading https://packagist.org/api/security-advisories/
[200] https://packagist.org/api/security-advisories/
No security vulnerability advisories found
```

</details>

And I expected this to happen a fresh `demo/.tools/vendor/composer/installed.json` file corresponding to this `demo/.tools/composer.lock`

<details>

<summary>demo/.tools/composer.lock</summary>

```json
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "0403b5330a44c99b0227b266c83bb108",
    "packages": [],
    "packages-dev": [
        {
            "name": "bartlett/manifests",
            "version": "dev-master",
            "dist": {
                "type": "path",
                "url": "../..",
                "reference": "b1ad9e670b63a85f8fa1b2bc8b34365431c9e7fe"
            },
            "require": {
                "composer-plugin-api": "^2.3",
                "ext-json": "*",
                "php": "^7.2.5 || ^8.0"
            },
            "require-dev": {
                "bamarni/composer-bin-plugin": "^1.8",
                "composer/composer": "^2.3",
                "symfony/phpunit-bridge": "^5.4 || ^6.0"
            },
            "suggest": {
                "cyclonedx/cyclonedx-library": "Needed to support SBOM CycloneDX format",
                "ext-libxml": "Needed to support XML format with CycloneDX builder/loader",
                "ext-simplexml": "Needed to support XML format with CycloneDX builder/loader",
                "phar-io/manifest": "Needed to support PHIVE format"
            },
            "type": "composer-plugin",
            "extra": {
                "bamarni-bin": {
                    "bin-links": true,
                    "forward-command": false,
                    "target-directory": "vendor-bin"
                },
                "class": "Bartlett\\Manifests\\Plugin",
                "branch-alias": {
                    "dev-master": "1.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Bartlett\\Manifests\\": "src/"
                }
            },
            "autoload-dev": {
                "psr-4": {
                    "Bartlett\\Manifests\\Tests\\": "tests/"
                }
            },
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Laurent Laville",
                    "role": "Lead Developer"
                }
            ],
            "description": "Composer plugin that creates manifests for a PHP Archive (PHAR)",
            "transport-options": {
                "relative": true
            }
        }
    ],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": {
        "bartlett/manifests": 20
    },
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": [],
    "plugin-api-version": "2.3.0"
}
```

</details>

With the corresponding 

<details>

<summary>demo/.tools/composer.json</summary>

```json
{
    "name": "tools/composer-plugin",
    "description": "Demo for Composer Plugin Global like usage",
    "license": "MIT",
    "require": {
    },
    "require-dev": {
        "bartlett/manifests": "@dev"
    },
    "repositories": [
        {
            "type": "path",
            "url": "../../",
            "symlink": true
        }
    ],
    "config": {
        "allow-plugins": {
            "bartlett/manifests": true
        },
        "optimize-autoloader": true
    }
}
```

/details>

But the expected constraints of main composer plugin (path repo symlinked) is not applied (and keep old previous constraints)

<details>

<summary>demo/.tools/vendor/composer/installed.json</summary>

```json
{
    "packages": [
        {
            "name": "bartlett/manifests",
            "version": "dev-master",
            "version_normalized": "dev-master",
            "dist": {
                "type": "path",
                "url": "../..",
                "reference": "b1ad9e670b63a85f8fa1b2bc8b34365431c9e7fe"
            },
            "require": {
                "composer-plugin-api": "^2.2.0",
                "ext-json": "*",
                "php": "^5.3.2 || ^7.0 || ^8.0"
            },
            "require-dev": {
                "composer/composer": "^2.2",
                "symfony/phpunit-bridge": "^4.0 || ^5.0 || ^6.0"
            },
            "suggest": {
                "cyclonedx/cyclonedx-library": "Needed to support SBOM CycloneDX format",
                "ext-libxml": "Needed to support XML format with CycloneDX builder/loader",
                "ext-simplexml": "Needed to support XML format with CycloneDX builder/loader"
            },
            "type": "composer-plugin",
            "extra": {
                "class": "Bartlett\\Manifests\\Plugin",
                "branch-alias": {
                    "dev-master": "1.x-dev"
                }
            },
            "installation-source": "dist",
            "autoload": {
                "psr-4": {
                    "Bartlett\\Manifests\\": "src/"
                }
            },
            "autoload-dev": {
                "psr-4": {
                    "Bartlett\\Manifests\\Tests\\": "tests/"
                }
            },
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Laurent Laville",
                    "role": "Lead Developer"
                }
            ],
            "description": "Composer plugin that creates manifests for a PHP Archive (PHAR)",
            "transport-options": {
                "relative": true
            },
            "install-path": "../bartlett/manifests"
        }
    ],
    "dev": true,
    "dev-package-names": [
        "bartlett/manifests"
    ]
}
```

</details>

**Comment by llaville** [comment]
But the expected constraints of main composer plugin (path repo symlinked) is not applied (and keep old previous constraints)

<details>

<summary>demo/.tools/vendor/composer/installed.json</summary>

```json
{
    "packages": [
        {
            "name": "bartlett/manifests",
            "version": "dev-master",
            "version_normalized": "dev-master",
            "dist": {
                "type": "path",
                "url": "../..",
                "reference": "b1ad9e670b63a85f8fa1b2bc8b34365431c9e7fe"
            },
            "require": {
                "composer-plugin-api": "^2.2.0",
                "ext-json": "*",
                "php": "^5.3.2 || ^7.0 || ^8.0"
            },
            "require-dev": {
                "composer/composer": "^2.2",
                "symfony/phpunit-bridge": "^4.0 || ^5.0 || ^6.0"
            },
            "suggest": {
                "cyclonedx/cyclonedx-library": "Needed to support SBOM CycloneDX format",
                "ext-libxml": "Needed to support XML format with CycloneDX builder/loader",
                "ext-simplexml": "Needed to support XML format with CycloneDX builder/loader"
            },
            "type": "composer-plugin",
            "extra": {
                "class": "Bartlett\\Manifests\\Plugin",
                "branch-alias": {
                    "dev-master": "1.x-dev"
                }
            },
            "installation-source": "dist",
            "autoload": {
                "psr-4": {
                    "Bartlett\\Manifests\\": "src/"
                }
            },
            "autoload-dev": {
                "psr-4": {
                    "Bartlett\\Manifests\\Tests\\": "tests/"
                }
            },
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Laurent Laville",
                    "role": "Lead Developer"
                }
            ],
            "description": "Composer plugin that creates manifests for a PHP Archive (PHAR)",
            "transport-options": {
                "relative": true
            },
            "install-path": "../bartlett/manifests"
        }
    ],
    "dev": true,
    "dev-package-names": [
        "bartlett/manifests"
    ]
}
```

</details>

**Comment by llaville** [comment]
**I've finally found origin of this issue !**


I resume my local folders (with only files/directories that are important to understand)

```
.
├── ./composer.json
├── ./composer.lock
├── ./demo
│   └── ./demo/.tools
│       ├── ./demo/.tools/composer.json
│       ├── ./demo/.tools/composer.lock
│       ├── ./demo/.tools/dummy.php
│       └── ./demo/.tools/vendor
├── ./src
├── ./vendor
│   ├── ./vendor/autoload.php
│   ├── ./vendor/composer
│   │   ├── ./vendor/composer/autoload_classmap.php
│   │   ├── ./vendor/composer/autoload_files.php
│   │   ├── ./vendor/composer/autoload_namespaces.php
│   │   ├── ./vendor/composer/autoload_psr4.php
│   │   ├── ./vendor/composer/autoload_real.php
│   │   ├── ./vendor/composer/autoload_static.php
│   │   ├── ./vendor/composer/ca-bundle
│   │   ├── ./vendor/composer/ClassLoader.php
│   │   ├── ./vendor/composer/class-map-generator
│   │   ├── ./vendor/composer/composer
│   │   ├── ./vendor/composer/installed.json
│   │   ├── ./vendor/composer/installed.php
│   │   ├── ./vendor/composer/InstalledVersions.php
│   │   ├── ./vendor/composer/LICENSE
│   │   ├── ./vendor/composer/metadata-minifier
│   │   ├── ./vendor/composer/pcre
│   │   ├── ./vendor/composer/platform_check.php
│   │   ├── ./vendor/composer/semver
│   │   ├── ./vendor/composer/spdx-licenses
│   │   └── ./vendor/composer/xdebug-handler
└── ./vendor-bin
 
```

Here is the script I used to demonstrate it `demo/.tools/dummy.php` : the context is the same as previous (a symlinked path repo)

```php
<?php

require_once dirname(__DIR__, 2) . '/vendor/autoload.php';

class Callbacks
{
    private $rm;

    public function __construct(\Composer\Repository\RepositoryManager $rm)
    {
        $this->rm = $rm;
    }

    public function getRepositoryStack(): array
    {
        $repositories = [];

        foreach ($this->rm->getRepositories() as $rep) {
            $repositories[\get_debug_type($rep)] = $rep->getRepoName();
        }
        
        return $repositories;
    }

    public function getPackageByRepository(): array
    {
        $results = [];

        foreach ($this->rm->getRepositories() as $rep) {
            if ($rep instanceof \Composer\Repository\ComposerRepository) {
                $packages = ['...too much to display ...'];
            } elseif ($rep instanceof \Composer\Repository\PlatformRepository) {
                $packages = [
                    'php' => \phpversion(),
                    'composer' => $rep->findPackage('composer', '^2.3')->getVersion(),
                    'composer-plugin-api' => $rep->findPackage('composer-plugin-api', '^2.3')->getVersion(),
                    'composer-runtime-api' => $rep->findPackage('composer-runtime-api', '^2.0')->getVersion()
                ];
            } else {
                $packages = \array_map(
                    function ($pkg) {
                        return [$pkg->getPrettyString() => $this->getPackageConstraints($pkg)];
                    },
                    $rep->getPackages()
                );
            }
            $results[\get_debug_type($rep) . ' ' . $rep->getRepoName()] = $packages;
        }
        return $results;
    }

    public function getPackageConstraints($pkg): array
    {
        $links = ['non-dev requirements' => [], 'dev requirements' => []];
        foreach ($pkg->getRequires() as $link) {
            $links['non-dev requirements'][] = (string) $link;
        }
        foreach ($pkg->getDevRequires() as $link) {
            $links['dev requirements'][] = (string) $link;
        }
        return $links;
    }

    public function resolvePackage(string $name, string $constraint, bool $locally = false): array
    {
        if ($locally) {
            $repo = $this->rm->getLocalRepository();
        } else {
            $repo = new \Composer\Repository\CompositeRepository($this->rm->getRepositories());
        }

        $package = $repo->findPackage($name, $constraint);

        if ($package === null) {
            return [];
        }
        return [
            $name => (string) $package,
            'constraints' => $this->getPackageConstraints($package),
            'repository' => [\get_debug_type($repo), $repo->getRepoName()],
        ];
    }
}

$localConfig = __DIR__ . '/composer.json';

$composer = (new \Composer\Factory())->createComposer(
    new \Composer\IO\NullIO(),
    $localConfig,
    false,
    null,
    true,
    false
);

$rootPackage = $composer->getPackage();

$rootRepo = new \Composer\Repository\RootPackageRepository($rootPackage);

$localRepo = $composer->getRepositoryManager()->getLocalRepository();

$composerLocker = $composer->getLocker();
$lockRepo = $composerLocker->getLockedRepository(true);

$platformRepo = new \Composer\Repository\PlatformRepository([], []);

$rm = $composer->getRepositoryManager();
$rm->prependRepository($rootRepo);
$rm->prependRepository($platformRepo);
//$rm->addRepository($lockRepo);
$rm->addRepository($localRepo);

$callbacks = new Callbacks($rm);

// [1]
\var_dump($callbacks->getPackageByRepository());
// [2]
\var_dump($callbacks->getRepositoryStack());
// [3]
\var_dump($callbacks->resolvePackage('bartlett/manifests', '@dev'));
// [4]
\var_dump($callbacks->resolvePackage('bartlett/manifests', '@dev', true));

```

Important differences are between [4] (that used the `installed.json` outdated copy) and [3] (file not used)
So results depends of how we implemented package resolver on a user solution : 

Searching on (installed) local repository is not enough (because `installed.json` file may be outdated)
[2]
```
array(5) {
  ["Composer\Repository\PlatformRepository"]=>
  string(13) "platform repo"
  ["Composer\Repository\RootPackageRepository"]=>
  string(17) "root package repo"
  ["Composer\Repository\PathRepository"]=>
  string(18) "path repo (../../)"
  ["Composer\Repository\ComposerRepository"]=>
  string(42) "composer repo (https://repo.packagist.org)"
  ["Composer\Repository\InstalledFilesystemRepository"]=>
  string(42) "installed array repo (defining 2 packages)"
}
```

[3]
```
array(3) {
  ["bartlett/manifests"]=>
  string(70) "bartlett/manifests-1.9999999.9999999.9999999-dev (alias of dev-master)"
  ["constraints"]=>
  array(2) {
    ["non-dev requirements"]=>
    array(3) {
      [0]=>
      string(64) "bartlett/manifests requires php ([>= 7.2.5.0-dev < 9.0.0.0-dev])"
      [1]=>
      string(40) "bartlett/manifests requires ext-json (*)"
      [2]=>
      string(80) "bartlett/manifests requires composer-plugin-api ([>= 2.3.0.0-dev < 3.0.0.0-dev])"
    }
    ["dev requirements"]=>
    array(3) {
      [0]=>
      string(106) "bartlett/manifests requires (for development) bamarni/composer-bin-plugin ([>= 1.8.0.0-dev < 2.0.0.0-dev])"
      [1]=>
      string(96) "bartlett/manifests requires (for development) composer/composer ([>= 2.3.0.0-dev < 3.0.0.0-dev])"
      [2]=>
      string(101) "bartlett/manifests requires (for development) symfony/phpunit-bridge ([>= 5.4.0.0-dev < 7.0.0.0-dev])"
    }
  }
  ["repository"]=>
  array(2) {
    [0]=>
    string(39) "Composer\Repository\CompositeRepository"
    [1]=>
    string(157) "composite repo (platform repo, root package repo, path repo (../../), composer repo (https://repo.packagist.org), installed array repo (defining 2 packages))"
  }
}
```

[4]
```
array(3) {
  ["bartlett/manifests"]=>
  string(70) "bartlett/manifests-1.9999999.9999999.9999999-dev (alias of dev-master)"
  ["constraints"]=>
  array(2) {
    ["non-dev requirements"]=>
    array(3) {
      [0]=>
      string(80) "bartlett/manifests requires composer-plugin-api ([>= 2.2.0.0-dev < 3.0.0.0-dev])"
      [1]=>
      string(40) "bartlett/manifests requires ext-json (*)"
      [2]=>
      string(100) "bartlett/manifests requires php ([[>= 5.3.2.0-dev < 6.0.0.0-dev] || [>= 7.0.0.0-dev < 9.0.0.0-dev]])"
    }
    ["dev requirements"]=>
    array(2) {
      [0]=>
      string(96) "bartlett/manifests requires (for development) composer/composer ([>= 2.2.0.0-dev < 3.0.0.0-dev])"
      [1]=>
      string(101) "bartlett/manifests requires (for development) symfony/phpunit-bridge ([>= 4.0.0.0-dev < 7.0.0.0-dev])"
    }
  }
  ["repository"]=>
  array(2) {
    [0]=>
    string(49) "Composer\Repository\InstalledFilesystemRepository"
    [1]=>
    string(42) "installed array repo (defining 2 packages)"
  }
}
```
 
Previously I used only the `$localRepo = $composer->getRepositoryManager()->getLocalRepository();` or the `$lockRepo = $composerLocker->getLockedRepository(true);` version.

Now I recommend to use a `Composer\Repository\CompositeRepository`

**Comment by llaville** [comment]
BTW, I've also noticed by using the `Composer\Repository\CompositeRepository` that we cannot `getPackages()` directly when there is a ComposerRepositoty into stack 

```php
<?php

require_once dirname(__DIR__, 2) . '/vendor/autoload.php';

$localConfig = __DIR__ . '/composer.json';

$composer = (new \Composer\Factory())->createComposer(
    new \Composer\IO\NullIO(),
    $localConfig,
    false,
    null,
    true,
    false
);

$rm = $composer->getRepositoryManager();

$repo = new \Composer\Repository\CompositeRepository($rm->getRepositories());

\var_dump($repo->getPackages());
```
Raise a LogicException
```
Fatal error: Uncaught LogicException: Composer repositories that have lazy providers and no available-packages list can not load the complete list of packages, use getPackageNames instead. in /shared/backups/bartlett/manifests/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php:342
Stack trace:
#0 /shared/backups/bartlett/manifests/vendor/composer/composer/src/Composer/Repository/CompositeRepository.php(147): Composer\Repository\ComposerRepository->getPackages()
#1 /shared/backups/bartlett/manifests/demo/.tools/repos.php(20): Composer\Repository\CompositeRepository->getPackages()
#2 {main}
  thrown in /shared/backups/bartlett/manifests/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php on line 342
```

**Comment by Seldaek** [comment]
Not sure what I can do to help you here.. the LocalRepository should always be up to date with whatever is installed, but the problem here seems to be that the dist reference of the path repository package does not change. Did you do a git commit in the path repo when you changed the composer.json? By default if it is not committed it will not change the ref and thus not do an update. Changing the reference mode to `config` explicitly will override that to always just take a hash of the composer.json as reference (which has different tradeoffs, and will not update if the git reference changes, so that's ok for symlinks but for non-symlinked installs this is suboptimal)

e.g. 

```
{
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/my-package",
            "options": {
                "reference": "config"
            }
        }
    ]
}
```

**Comment by llaville** [comment]
Perfectly. This solution fixed my issue ! Thanks a lot.
Reason is, I didn't commit any changes on local since I've modified my packages constraints

**Comment by llaville** [comment]
Hello @Seldaek

It does not related to a symlinked path repository, but I'd like your point of view about this use case : 

Today I've upgraded my [fork](https://github.com/llaville/composer-unused) of [composer-unused/composer-unused](https://github.com/composer-unused/composer-unused) that contains a `composer.lock` into GitHub repository.

As I've not run `composer update` command, just after synchronized my fork, I've a difference between  `vendor/composer/installed.json` and `composer.lock` versions installed.
Can we do something to warn about these differences ?

**Comment by Seldaek** [comment]
After pulling changes to composer.lock you should run `composer install` to sync up? I don't know how it being a fork or whatever changes that fact?

**Comment by llaville** [comment]
I know the user process to sync up the fork. Here I would like to alert that if programmers like me used the Composer RepositoryManager with repos following order (installed (local repo)) then lock repo, they may be in trouble.

 I've an idea, but I want your point of view if it's the best way !

Update the `Composer\Repository\InstalledFilesystemRepository::isFresh` (to check if composer.lock is more recent than installed.json version)

```
    public function isFresh()
    {
        //return !$this->file->exists();
        $exists = $this->file->exists();

        $composerLock = \dirname($this->file->getPath(), 3) . '/composer.lock';

        if (\file_exists($composerLock) && $exists && \filemtime($this->file->getPath()) < \filemtime($composerLock)) {
            return false;
        }
        return !$exists;
    }
```

**Comment by Seldaek** [comment]
But isFresh is:

```
    /**
     * @return bool true if packages were never installed in this repository
     */
    public function isFresh();
```

So your change would break that contract.

Plus it would be very tight coupling with filenames etc.

So I'm not a fan overall.

Sorry but this all sounds like some weird edge cases for you writing your plugin, and maybe they should be fixed there?

**Comment by llaville** [comment]
> So I'm not a fan overall.
> 
> Sorry but this all sounds like some weird edge cases for you writing your plugin, and maybe they should be fixed there?

OK, understood !

Oh, and as you've [already replied](https://github.com/composer/composer/issues/11527#issuecomment-1615869427) to main goal of this report, I'll close it now.

Once again, thanks a lot for support !
