### ISSUE TITLE
[Snapshot version] Unhandled promise rejection TransportException

### ISSUE THREAD

**Issue by PhilETaylor** [composer/composer#11563]
(yes I know, don't run snapshot in production ;-) someone has to though :) ) 

So there seems to be an issue with an `Unhandled promise rejection with Composer\Downloader\TransportException` in the snapshot version. 

I initially saw this when my private repo had no FUNDING.yml and so composer threw an exception, but in typing up this issue report I was able to generate this stack trace with a different message but the same Unhandled promise rejection with Composer\Downloader\TransportException.

The error `No valid composer.json was found in any branch or tag of https://github.com/PhilETaylor/no-funding-yml, could not load a package from it` is the correct error (for this reproducer) but I should not see a stack trace before that. 

In the real world the message was (a private repo, that has no `.github/FUNDING.yml` file)

```
Unhandled promise rejection with Composer\Downloader\TransportException: The "https://api.github.com/repos/PhilETaylor/base/contents/.github/FUNDING.yml" file could not be downloaded (HTTP/2 404 ):
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#get-repository-content"} in phar:///Users/phil/Sites/myBackups.guru/composer.phar/src/Composer/Util/Http/CurlDownloader.php:630
Stack trace:

<snip huge stack trace, is the same as the one in the reproducer below>
```

How I replicate this:

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"


php composer.phar -V
Composer version 2.5.8 2023-06-09 17:13:21


php composer.phar self-up --snapshot
Upgrading to version f752a9e3584de3f559d2fc41c6bd9a6d2daf5c44 (snapshot channel).

```

```
{
    "license": "whatever",
    "type": "project",
    "require": {
        "philetaylor/no-funding-yml": "*"

    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/PhilETaylor/no-funding-yml"
        }
    ]
    
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.philetaylor/no-funding-yml : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK git version 2.41.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.6-dev+f752a9e3584de3f559d2fc41c6bd9a6d2daf5c44
PHP version: 8.2.8
PHP binary path: /opt/homebrew/Cellar/php/8.2.8/bin/php
OpenSSL version: OpenSSL 3.1.1 30 May 2023
cURL version: 8.2.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/3.1.1
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
php composer.phar install 
```

I get the following output: 

```
Unhandled promise rejection with Composer\Downloader\TransportException: The "https://api.github.com/repos/PhilETaylor/no-funding-yml/git/refs/heads?per_page=100" file could not be downloaded (HTTP/2 409 ):
{"message":"Git Repository is empty.","documentation_url":"https://docs.github.com/rest/git/refs#get-a-reference"} in phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Util/Http/CurlDownloader.php:630
Stack trace:
#0 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Util/Http/CurlDownloader.php(442): Composer\Util\Http\CurlDownloader->failResponse(Array, Object(Composer\Util\Http\CurlResponse), 'HTTP/2 409 ')
#1 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Util/HttpDownloader.php(389): Composer\Util\Http\CurlDownloader->tick()
#2 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Util/HttpDownloader.php(360): Composer\Util\HttpDownloader->countActiveJobs(3)
#3 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Util/HttpDownloader.php(111): Composer\Util\HttpDownloader->wait(3)
#4 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Repository/Vcs/VcsDriver.php(170): Composer\Util\HttpDownloader->get('https://api.git...', Array)
#5 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Repository/Vcs/GitHubDriver.php(447): Composer\Repository\Vcs\VcsDriver->getContents('https://api.git...')
#6 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Repository/Vcs/GitHubDriver.php(376): Composer\Repository\Vcs\GitHubDriver->getContents('https://api.git...')
#7 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Repository/VcsRepository.php(320): Composer\Repository\Vcs\GitHubDriver->getBranches()
#8 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Repository/ArrayRepository.php(308): Composer\Repository\VcsRepository->initialize()
#9 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Repository/ArrayRepository.php(62): Composer\Repository\ArrayRepository->getPackages()
#10 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/DependencyResolver/PoolBuilder.php(385): Composer\Repository\ArrayRepository->loadPackages(Array, Array, Array, Array)
#11 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/DependencyResolver/PoolBuilder.php(239): Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading(Object(Composer\DependencyResolver\Request), Array)
#12 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Repository/RepositorySet.php(317): Composer\DependencyResolver\PoolBuilder->buildPool(Array, Object(Composer\DependencyResolver\Request))
#13 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Installer.php(470): Composer\Repository\RepositorySet->createPool(Object(Composer\DependencyResolver\Request), Object(Composer\IO\ConsoleIO), Object(Composer\EventDispatcher\EventDispatcher), NULL)
#14 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Installer.php(288): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#15 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Command/InstallCommand.php(146): Composer\Installer->run()
#16 phar:///Users/phil/Sites/composer-replication/composer.phar/vendor/symfony/console/Command/Command.php(298): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///Users/phil/Sites/composer-replication/composer.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///Users/phil/Sites/composer-replication/composer.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Console/Application.php(378): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///Users/phil/Sites/composer-replication/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 phar:///Users/phil/Sites/composer-replication/composer.phar/src/Composer/Console/Application.php(141): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 phar:///Users/phil/Sites/composer-replication/composer.phar/bin/composer(88): Composer\Console\Application->run()
#23 /Users/phil/Sites/composer-replication/composer.phar(30): require('phar:///Users/p...')
#24 {main}

In VcsRepository.php line 420:

  No valid composer.json was found in any branch or tag of https://github.com/PhilETaylor/no-funding-yml, could not load a package from it.


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
```

And I expected this to happen:

In the reproducer: Yes sure give me an error that "No valid composer.json was found" but handle the exception/promise correctly so no stack trace shows

In my realworld: Silently ignore the fact no FUNDING.yml was found.

**Comment by WyriHaximus** [comment]
> (yes I know, don't run snapshot in production ;-) someone has to though :) )

Thank you for running snapshot in production :+1: 
 
> So there seems to be an issue with an `Unhandled promise rejection with Composer\Downloader\TransportException` in the snapshot version.

That specific error is why, we introduced it to make sure errors bubble up when a promise has an unhandled rejection.  So if in this cause that request is made and, for whatever reason, the error coming out of that request is ignored/go below the radar it will bubble up.

**Comment by Seldaek** [comment]
Yeah it's great to see the new mechanism doing its thing. I'll have to further dig into what's exactly triggering this though :)

**Comment by PhilETaylor** [comment]
Sorry - Im a bad contributor :), Ive spent no time trying to understand the internals or providing a PR, but thought you might want the report early in the dev-cycle to look into. 

> Thank you for running snapshot in production

I mean, er, locally :) on my main rock solid dev MacOS in daily use, as my main composer command :) not actually in "production" haha. Im crazy, not insane :)

**Comment by WyriHaximus** [comment]
> Yeah it's great to see the new mechanism doing its thing. I'll have to further dig into what's exactly triggering this though :)

Same! Let us know if you need a hand.

> > Thank you for running snapshot in production
> 
> I mean, er, locally :) on my main rock solid dev MacOS in daily use, as my main composer command :)

Well, that is composer's production environment :wink: .

**Comment by Seldaek** [comment]
Thanks a bunch for the repro case, it helped a great deal get this resolved quickly (once I finally got to look into it..)

**Comment by PhilETaylor** [comment]
Works perfectly now - thanks! 



```
 composer self-up --snapshot
Storing "snapshot" as default update channel for the next self-update run.
Upgrading to version bbd2c9613e9359480173a4504488327bb1e22347 (snapshot channel).

Use composer self-update --rollback to return to version 2.5.8

composer update

Updating dependencies
Lock file operations: 0 installs, 13 updates, 0 removals
  - Upgrading league/uri-interfaces (dev-master d733f5f => dev-master 4a3209f)
  - Upgrading nette/utils (v3.2.x-dev a4175c6 => v3.2.x-dev 3b648e7)
  - Upgrading rector/rector (dev-main 4650cf5 => dev-main 5c920d9)
  - Upgrading roave/security-advisories (dev-latest c16c8b6 => dev-latest 05cbd34)
  - Upgrading symfony/console (6.4.x-dev 0870356 => 6.4.x-dev 934459f)
  - Upgrading symfony/framework-bundle (6.4.x-dev fe4833c => 6.4.x-dev d2a830e)
  - Upgrading symfony/mailer (6.4.x-dev 5369200 => 6.4.x-dev 70b7234)
  - Upgrading symfony/messenger (6.4.x-dev b3c6071 => 6.4.x-dev 5ace2b8)
  - Upgrading symfony/notifier (6.4.x-dev 4067521 => 6.4.x-dev cc1c229)
  - Upgrading symfony/security-core (6.4.x-dev f238619 => 6.4.x-dev 354c668)
  - Upgrading symfony/security-csrf (6.4.x-dev 628e9db => 6.4.x-dev b284134)
  - Upgrading symfony/security-http (6.4.x-dev ae31675 => 6.4.x-dev 7c3050e)
  - Upgrading symfony/translation (6.4.x-dev 918dd68 => 6.4.x-dev dcda32b)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 13 updates, 0 removals
  - Downloading symfony/console (6.4.x-dev 934459f)
  - Downloading symfony/security-core (6.4.x-dev 354c668)
  - Downloading symfony/security-http (6.4.x-dev 7c3050e)
  - Downloading symfony/security-csrf (6.4.x-dev b284134)
  - Downloading symfony/framework-bundle (6.4.x-dev d2a830e)
  - Downloading symfony/translation (6.4.x-dev dcda32b)
  - Downloading symfony/mailer (6.4.x-dev 70b7234)
  - Downloading nette/utils (v3.2.x-dev 3b648e7)
  - Downloading league/uri-interfaces (dev-master 4a3209f)
  - Downloading rector/rector (dev-main 5c920d9)
  - Downloading symfony/notifier (6.4.x-dev cc1c229)
  - Downloading symfony/messenger (6.4.x-dev 5ace2b8)
  - Upgrading symfony/console (6.4.x-dev 0870356 => 6.4.x-dev 934459f): Extracting archive
  - Upgrading symfony/security-core (6.4.x-dev f238619 => 6.4.x-dev 354c668): Extracting archive
  - Upgrading symfony/security-http (6.4.x-dev ae31675 => 6.4.x-dev 7c3050e): Extracting archive
  - Upgrading symfony/security-csrf (6.4.x-dev 628e9db => 6.4.x-dev b284134): Extracting archive
  - Upgrading symfony/framework-bundle (6.4.x-dev fe4833c => 6.4.x-dev d2a830e): Extracting archive
  - Upgrading symfony/translation (6.4.x-dev 918dd68 => 6.4.x-dev dcda32b): Extracting archive
  - Upgrading symfony/mailer (6.4.x-dev 5369200 => 6.4.x-dev 70b7234): Extracting archive
  - Upgrading nette/utils (v3.2.x-dev a4175c6 => v3.2.x-dev 3b648e7): Extracting archive
  - Upgrading league/uri-interfaces (dev-master d733f5f => dev-master 4a3209f): Extracting archive
  - Upgrading rector/rector (dev-main 4650cf5 => dev-main 5c920d9): Extracting archive
  - Upgrading roave/security-advisories (dev-latest c16c8b6 => dev-latest 05cbd34)
  - Upgrading symfony/notifier (6.4.x-dev 4067521 => 6.4.x-dev cc1c229): Extracting archive
  - Upgrading symfony/messenger (6.4.x-dev b3c6071 => 6.4.x-dev 5ace2b8): Extracting archive
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
170 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
