### ISSUE TITLE
Symlink problem in local repository on Windows

### ISSUE THREAD

**Issue by Sabiil** [composer/composer#11618]
Say I have local repository with 3 packages in it:
- First
- Second
- Engine

First and Second packages use Engine as dependence.  

First package composer.json:

![Screenshot_2](https://github.com/composer/composer/assets/15968188/e169edbe-a79c-4306-8711-56190905c09b)

`{
    "name": "tb/first",
    "type": "library",
    "autoload": {
        "psr-4": {
            "Tb\\First\\": "src/"
        }
    },
    "minimum-stability": "dev",
    "require": {
        "tb/engine": "*"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./../../tb/*",
            "options": {
                "symlink": true
            }
        }
    ]
}`

Second package composer.json

![Screenshot_3](https://github.com/composer/composer/assets/15968188/b3386264-8c58-4f80-801e-9766cc7b278d)

`{
    "name": "tb/second",
    "type": "library",
    "autoload": {
        "psr-4": {
            "Tb\\Second\\": "src/"
        }
    },
    "minimum-stability": "dev",
    "require": {
        "tb/engine": "*"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./../../tb/*",
            "options": {
                "symlink": true
            }
        }
    ]
}
`

Engine composer.json

![Screenshot_4](https://github.com/composer/composer/assets/15968188/4675b9a1-2f84-482f-86ca-1cb5282e44c9)

`{
    "name": "tb/engine",
    "type": "library",
    "autoload": {
        "psr-4": {
            "Tb\\Engine\\": "src/"
        }
    },
    "minimum-stability": "dev",
    "require": {}
}
`

Then I have project, which uses First and Second packages as dependences.
My `composer.json`:

![Screenshot_5](https://github.com/composer/composer/assets/15968188/2a646dce-ac86-4de5-ab26-4bab717c5451)

`{
    "name": "tb/try",
    "type": "project",
    "minimum-stability": "dev",
    "require": {
        "php": ">=8.1",
        "tb/first": "*",
        "tb/second": "*"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./../_packages/tb/*", 
            "options": {
                "symlink": false
            }
        }
    ]
}
`

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.tb/first : unbound version constraints (*) should be avoided
require.tb/second : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK git version 2.41.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952 
OK
Checking composer version: OK
Composer version: 2.6-dev+75ae504b2c8a7ee8533c69788c3bbdbf3740e610
PHP version: 8.1.6
PHP binary path: P:\Program Portable\php-8.1.6\php.exe
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
cURL version: 7.77.0 libz 1.2.12 ssl OpenSSL/1.1.1n
zip: extension present, unzip not available, 7-Zip not available
```

When I run this command in my project: 

```
composer update
```

I get the following output: 

```
PS P:\Program Portable\OpenServer\domains\_playground\try> composer update
Loading composer repositories with package information
PS P:\Program Portable\OpenServer\domains\_playground\try> composer update -vvv
Running 2.6-dev+75ae504b2c8a7ee8533c69788c3bbdbf3740e610 (2023-09-03 12:09:16) with PHP 8.1.6 on Windows NT / 10.0
Reading ./composer.json (P:\Program Portable\OpenServer\domains\_playground\try\composer.json)
Loading config file C:/Users/1/AppData/Roaming/Composer/config.json
Loading config file C:/Users/1/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json (P:\Program Portable\OpenServer\domains\_playground\try\composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt does not exist or it is not a file.
Checked directory /etc/ssl/certs/ca-certificates.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/ca-bundle.pem does not exist or it is not a file.
Checked directory /etc/ssl/ca-bundle.pem does not exist or it is not a directory.
Checked CA file /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a file.
Checked directory /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a directory.
Checked CA file /usr/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.       
Checked CA file /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.       
Checked CA file /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/cert.pem does not exist or it is not a file.
Checked directory /etc/ssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/ssl/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/ssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/openssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl@1.1/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/openssl@1.1/cert.pem does not exist or it is not a directory.
Checked CA file /etc/pki/tls/certs does not exist or it is not a file.
Checked directory /etc/pki/tls/certs does not exist or it is not a directory.
Checked CA file /etc/ssl/certs does not exist or it is not a file.
Checked directory /etc/ssl/certs does not exist or it is not a directory.
Checked CA file /etc/ssl does not exist or it is not a file.
Checked directory /etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/share/certs does not exist or it is not a file.
Checked directory /usr/local/share/certs does not exist or it is not a directory.
Checked CA file /usr/ssl/certs does not exist or it is not a file.
Checked directory /usr/ssl/certs does not exist or it is not a directory.
Checked CA file /opt/local/share/curl does not exist or it is not a file.
Checked directory /opt/local/share/curl does not exist or it is not a directory.
Checked CA file /usr/local/share/curl does not exist or it is not a file.
Checked directory /usr/local/share/curl does not exist or it is not a directory.
Checked CA file /usr/share/ssl/certs does not exist or it is not a file.
Checked directory /usr/share/ssl/certs does not exist or it is not a directory.
Checked CA file /etc/ssl does not exist or it is not a file.
Checked directory /etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/ssl does not exist or it is not a file.
Checked directory /usr/local/etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl does not exist or it is not a file.
Checked directory /usr/local/etc/openssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl@1.1 does not exist or it is not a file.
Checked directory /usr/local/etc/openssl@1.1 does not exist or it is not a directory.
Checked CA file P:\Users\Stan\AppData\Local\Temp\opeF682.tmp: valid
Executing command (P:\Program Portable\OpenServer\domains\_playground\try): git branch -a --no-color --no-abbrev -v
Executing command (P:\Program Portable\OpenServer\domains\_playground\try): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (P:\Program Portable\OpenServer\domains\_playground\try): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (P:\Program Portable\OpenServer\domains\_playground\try): hg branch
Executing command (P:\Program Portable\OpenServer\domains\_playground\try): fossil branch list
Executing command (P:\Program Portable\OpenServer\domains\_playground\try): fossil tag list
Executing command (P:\Program Portable\OpenServer\domains\_playground\try): svn info --xml
Failed to initialize global composer: Composer could not find the config file: C:/Users/1/AppData/Roaming/Composer/composer.json

Loading composer repositories with package information
Executing command (P:\Program Portable\OpenServer\domains\_playground\_packages\tb\engine\): git branch -a --no-color --no-abbrev -v
Executing async command (P:\Program Portable\OpenServer\domains\_playground\_packages\tb\engine\): git rev-list master..composer
Executing command (P:\Program Portable\OpenServer\domains\_playground\_packages\tb\first\): git branch -a --no-color --no-abbrev -v
Executing async command (P:\Program Portable\OpenServer\domains\_playground\_packages\tb\first\): git rev-list master..composer
Executing command (P:\Program Portable\OpenServer\domains\_playground\_packages\tb\second\): git branch -a --no-color --no-abbrev -v
Executing async command (P:\Program Portable\OpenServer\domains\_playground\_packages\tb\second\): git rev-list master..composer
Built pool.
Running pool optimizer.
Pool optimizer completed in 0.000 seconds
Found 56 package versions referenced in your dependency graph. 3 (5%) were optimized away.
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Analyzed 53 packages to resolve dependencies
Analyzed 54 rules to resolve dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
Installs: tb/engine:dev-composer, tb/first:dev-composer, tb/second:dev-composer
  - Locking tb/engine (dev-composer)
  - Locking tb/first (dev-composer)
  - Locking tb/second (dev-composer)
Writing lock file
Installing dependencies from lock file (including require-dev)
Reading ./composer.lock (P:\Program Portable\OpenServer\domains\_playground\try\composer.lock)
Package operations: 3 installs, 0 updates, 0 removals
Installs: tb/engine:dev-composer, tb/first:dev-composer, tb/second:dev-composer
  - Installing tb/engine (dev-composer): Mirroring from ./../_packages/tb/engine
  - Installing tb/first (dev-composer): Mirroring from ./../_packages/tb/first    Install of tb/first failed
  - Installing tb/second (dev-composer): Mirroring from ./../_packages/tb/second    Install of tb/second failed
Unhandled promise rejection with ArgumentCountError: Too few arguments to function React\Promise\Promise::React\Promise\{closure}(), 0 passed in phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php on line 660 and exactly 1 expected in phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php:277
Stack trace:
#0 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(660): React\Promise\Promise::React\Promise\{closure}()
#1 phar://P:/composer/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
#2 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(661): React\Promise\Internal\FulfilledPromise->then()
#3 phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php(288): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
#4 phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php(37): React\Promise\Promise->call()
#5 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(663): React\Promise\Promise->__construct()
#6 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(221): Composer\Installer\InstallationManager->runCleanup()
#7 phar://P:/composer/composer.phar/src/Composer/Installer.php(791): Composer\Installer\InstallationManager->execute()
#8 phar://P:/composer/composer.phar/src/Composer/Installer.php(616): Composer\Installer->doInstall()
#9 phar://P:/composer/composer.phar/src/Composer/Installer.php(290): Composer\Installer->doUpdate()
#10 phar://P:/composer/composer.phar/src/Composer/Command/UpdateCommand.php(247): Composer\Installer->run()
#11 phar://P:/composer/composer.phar/vendor/symfony/console/Command/Command.php(298): Composer\Command\UpdateCommand->execute()
#12 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#13 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 phar://P:/composer/composer.phar/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#15 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#16 phar://P:/composer/composer.phar/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#17 phar://P:/composer/composer.phar/bin/composer(88): Composer\Console\Application->run()
#18 P:\composer\composer.phar(30): require('...')
#19 {main}
Unhandled promise rejection with ArgumentCountError: Too few arguments to function React\Promise\Promise::React\Promise\{closure}(), 0 passed in phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php on line 660 and exactly 1 expected in phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php:277
Stack trace:
#0 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(660): React\Promise\Promise::React\Promise\{closure}()
#1 phar://P:/composer/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
#2 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(661): React\Promise\Internal\FulfilledPromise->then()
#3 phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php(288): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
#4 phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php(37): React\Promise\Promise->call()
#5 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(663): React\Promise\Promise->__construct()
#6 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(221): Composer\Installer\InstallationManager->runCleanup()
#7 phar://P:/composer/composer.phar/src/Composer/Installer.php(791): Composer\Installer\InstallationManager->execute()
#8 phar://P:/composer/composer.phar/src/Composer/Installer.php(616): Composer\Installer->doInstall()
#9 phar://P:/composer/composer.phar/src/Composer/Installer.php(290): Composer\Installer->doUpdate()
#10 phar://P:/composer/composer.phar/src/Composer/Command/UpdateCommand.php(247): Composer\Installer->run()
#11 phar://P:/composer/composer.phar/vendor/symfony/console/Command/Command.php(298): Composer\Command\UpdateCommand->execute()
#12 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#13 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 phar://P:/composer/composer.phar/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#15 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#16 phar://P:/composer/composer.phar/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#17 phar://P:/composer/composer.phar/bin/composer(88): Composer\Console\Application->run()
#18 P:\composer\composer.phar(30): require('...')
#19 {main}
Unhandled promise rejection with ArgumentCountError: Too few arguments to function React\Promise\Promise::React\Promise\{closure}(), 0 passed in phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php on line 660 and exactly 1 expected in phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php:277
Stack trace:
#0 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(660): React\Promise\Promise::React\Promise\{closure}()
#1 phar://P:/composer/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
#2 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(661): React\Promise\Internal\FulfilledPromise->then()
#3 phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php(288): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
#4 phar://P:/composer/composer.phar/vendor/react/promise/src/Promise.php(37): React\Promise\Promise->call()
#5 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(663): React\Promise\Promise->__construct()
#6 phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php(221): Composer\Installer\InstallationManager->runCleanup()
#7 phar://P:/composer/composer.phar/src/Composer/Installer.php(791): Composer\Installer\InstallationManager->execute()
#8 phar://P:/composer/composer.phar/src/Composer/Installer.php(616): Composer\Installer->doInstall()
#9 phar://P:/composer/composer.phar/src/Composer/Installer.php(290): Composer\Installer->doUpdate()
#10 phar://P:/composer/composer.phar/src/Composer/Command/UpdateCommand.php(247): Composer\Installer->run()
#11 phar://P:/composer/composer.phar/vendor/symfony/console/Command/Command.php(298): Composer\Command\UpdateCommand->execute()
#12 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#13 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 phar://P:/composer/composer.phar/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#15 phar://P:/composer/composer.phar/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#16 phar://P:/composer/composer.phar/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#17 phar://P:/composer/composer.phar/bin/composer(88): Composer\Console\Application->run()
#18 P:\composer\composer.phar(30): require('...')
#19 {main}

In Filesystem.php line 588:

  [Symfony\Component\Filesystem\Exception\IOException]
  Unable to guess "P:/Program Portable/OpenServer/domains/_playground/_packages/tb/first\vendor\tb\engine" file type.  


Exception trace:
  at phar://P:/composer/composer.phar/vendor/symfony/filesystem/Filesystem.php:588
 Symfony\Component\Filesystem\Filesystem->mirror() at phar://P:/composer/composer.phar/src/Composer/Downloader/PathDownloader.php:151
 Composer\Downloader\PathDownloader->install() at phar://P:/composer/composer.phar/src/Composer/Downloader/DownloadManager.php:273
 Composer\Downloader\DownloadManager->install() at phar://P:/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:281
 Composer\Installer\LibraryInstaller->installCode() at phar://P:/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:152
 Composer\Installer\LibraryInstaller->install() at phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:464
 Composer\Installer\InstallationManager->install() at phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:378
 Composer\Installer\InstallationManager->Composer\Installer\{closure}() at phar://P:/composer/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:379
 Composer\Installer\InstallationManager->executeBatch() at phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:319
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar://P:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar://P:/composer/composer.phar/src/Composer/Installer.php:791
 Composer\Installer->doInstall() at phar://P:/composer/composer.phar/src/Composer/Installer.php:616
 Composer\Installer->doUpdate() at phar://P:/composer/composer.phar/src/Composer/Installer.php:290
 Composer\Installer->run() at phar://P:/composer/composer.phar/src/Composer/Command/UpdateCommand.php:247
 Composer\Command\UpdateCommand->execute() at phar://P:/composer/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://P:/composer/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar://P:/composer/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar://P:/composer/composer.phar/src/Composer/Console/Application.php:382
 Composer\Console\Application->doRun() at phar://P:/composer/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://P:/composer/composer.phar/src/Composer/Console/Application.php:145
 Composer\Console\Application->run() at phar://P:/composer/composer.phar/bin/composer:88
 require() at P:\composer\composer.phar:30

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]
```

![Screenshot_6](https://github.com/composer/composer/assets/15968188/3852e49b-6dd8-4b2b-96a6-75df1e0ba514)

![Screenshot_7](https://github.com/composer/composer/assets/15968188/71a8b723-b408-42dc-bd02-3e6a570c6eb5)

And I expected this to happen:

I expect that all dependences will be placed in vendor folder.

Thank you!

**Comment by Seldaek** [comment]
Should be fixed by #11620

**Comment by Sabiil** [comment]
`Composer version 2.6-dev+3bc72f75cbfc43b25ba4fb6013449b69cf29fc66 (2.6-dev) 2023-09-13 16:17:28`

The same configuration and the same problem, when I run command:

```composer update```

![Screenshot_5](https://github.com/composer/composer/assets/15968188/d2adacd9-5a89-4785-8f1c-3fea6232162e)


```
PS P:\Program Portable\OpenServer\domains\_playground\try\dist> composer update --verbose
Loading composer repositories with package information
Updating dependencies
Dependency resolution completed in 0.000 seconds
Analyzed 53 packages to resolve dependencies
Analyzed 54 rules to resolve dependencies
Lock file operations: 1 install, 0 updates, 0 removals
Installs: tb/second:dev-composer
  - Locking tb/second (dev-composer)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
Installs: tb/first:dev-composer, tb/second:dev-composer
  - Installing tb/first (dev-composer): Mirroring from ./../../_packages/tb/first    Install of tb/first failed
  - Installing tb/second (dev-composer): Mirroring from ./../../_packages/tb/second    Install of tb/second failed
    0 [--->------------------------] < 1 sec
In Filesystem.php line 588:

  [Symfony\Component\Filesystem\Exception\IOException]
  Unable to guess "P:/Program Portable/OpenServer/domains/_playground/_packages/tb/first\vendor\tb\engine" file type.  


Exception trace:
  at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/filesystem/Filesystem.php:588
 Symfony\Component\Filesystem\Filesystem->mirror() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Downloader/PathDownloader.php:151
 Composer\Downloader\PathDownloader->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Downloader/DownloadManager.php:273
 Composer\Downloader\DownloadManager->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/LibraryInstaller.php:281
 Composer\Installer\LibraryInstaller->installCode() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/LibraryInstaller.php:152
 Composer\Installer\LibraryInstaller->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:464
 Composer\Installer\InstallationManager->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:378
 Composer\Installer\InstallationManager->Composer\Installer\{closure}() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:379
 Composer\Installer\InstallationManager->executeBatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:319
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:791
 Composer\Installer->doInstall() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:616
 Composer\Installer->doUpdate() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:290
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/UpdateCommand.php:247
 Composer\Command\UpdateCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:382
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:145
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:88
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:30

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]
```

**Comment by Seldaek** [comment]
I think you can workaround the problem by using `"options": { "symlink": true } ` instead of `false` in the top level project. The problem as far as I can tell is that you have junctions in `_playground/_packages/tb/first\vendor\tb\engine` pointing to `_playground/_packages/tb/engine`, as these used symlinks to install, but then you try to do a copy and the symfony Filesystem class does not handle junctions gracefully [here](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Filesystem/Filesystem.php#L576C1-L583C21) and then it throws.
