### ISSUE TITLE
Missing check if filter PHP extension is available

### ISSUE THREAD

**Issue by rioderelfte** [composer/composer#11642]
I needed to use composer with a local development build of PHP, where most of the extensions are disabled.

For `mbstring`/`iconv` I got a nice error message from composer about the missing extensions:

```
$ ~/projects/php/php-src/sapi/cli/php /opt/homebrew/bin/composer install
The iconv OR mbstring extension is required and both are missing.
Install either of them or recompile php without --disable-iconv.
Aborting.
```

However for the `filter` extension, I didn't get a nice error message:

```
$ ~/projects/php/php-src/sapi/cli/php /opt/homebrew/bin/composer install

Fatal error: Uncaught Error: Call to undefined function JsonSchema\Uri\filter_var() in phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php:82
Stack trace:
#0 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(100): JsonSchema\Uri\UriResolver->resolve('phar:///opt/hom...', 'internal://prov...')
#1 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(72): JsonSchema\SchemaStorage->expandRefs(Object(stdClass), 'internal://prov...')
#2 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(58): JsonSchema\SchemaStorage->addSchema('internal://prov...', Object(stdClass))
#3 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(78): JsonSchema\Validator->validate(Object(stdClass), Object(stdClass))
#4 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Json/JsonFile.php(253): JsonSchema\Validator->check(Object(stdClass), Object(stdClass))
#5 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Json/JsonFile.php(213): Composer\Json\JsonFile::validateJsonSchema('./composer.json', Object(stdClass), 1, 'phar:///opt/hom...')
#6 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Factory.php(315): Composer\Json\JsonFile->validateSchema(1)
#7 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Factory.php(623): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), './composer.json', true, '/Users/florian/...', true, false)
#8 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Console/Application.php(501): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, true, false)
#9 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Console/Application.php(446): Composer\Console\Application->getComposer(false, true)
#10 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Console/Application.php(400): Composer\Console\Application->hintCommonErrors(Object(Error), Object(Symfony\Component\Console\Output\ConsoleOu
tput))
#11 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compone
nt\Console\Output\ConsoleOutput))
#12 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co
mponent\Console\Output\ConsoleOutput))
#13 phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/bin/composer(88): Composer\Console\Application->run()
#14 /opt/homebrew/Cellar/composer/2.6.2/bin/composer(29): require('phar:///opt/hom...')
#15 {main}
  thrown in phar:///opt/homebrew/Cellar/composer/2.6.2/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php on line 82
```

The `filter` extension is enabled by default and I don't think it is disabled anywhere but in development builds. So I am not sure if it really makes sense to add a check if the extension is missing. So please feel free to just close this issue if you think it does not make sense to add this check.

**Comment by Seldaek** [comment]
`composer diagnose` would warn you, and the [installer](https://getcomposer.org/download/) also would warn you, so IMO it's fine as is. We have some extra checks in our [bootstrap](https://github.com/composer/composer/blob/main/bin/composer#L28-L37) just for common errors which might be hard to debug then, but filter usually is enabled everywhere so I don't think it justifies adding it there.
