### ISSUE TITLE
Type error on PHP 8.4

### ISSUE THREAD

**Issue by ADmad** [composer/composer#12051]
https://github.com/cakephp/cakephp/actions/runs/10018186550/job/27693267939?pr=17740#step:13:49

Not sure if the issue is with composer or PHP itself considering PHP 8.4 is still in early development.

<details>
    <summary>My `composer.json`:</summary>

```json
{
    "name": "cakephp/cakephp",
    "type": "library",
    "description": "The CakePHP framework",
    "keywords": [
        "framework",
        "mvc",
        "rapid-development",
        "conventions over configuration",
        "dry",
        "orm",
        "form",
        "validation",
        "psr-7"
    ],
    "homepage": "https://cakephp.org",
    "license": "MIT",
    "authors": [
        {
            "name": "CakePHP Community",
            "homepage": "https://github.com/cakephp/cakephp/graphs/contributors"
        }
    ],
    "require": {
        "php": ">=8.1",
        "ext-intl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "cakephp/chronos": "^3.0.2",
        "composer/ca-bundle": "^1.2",
        "laminas/laminas-diactoros": "^3.0",
        "laminas/laminas-httphandlerrunner": "^2.6",
        "league/container": "^4.2",
        "psr/container": "^1.1 || ^2.0",
        "psr/http-client": "^1.0.2",
        "psr/http-factory": "^1.0.2",
        "psr/http-message": "^1.1 || ^2.0",
        "psr/http-server-handler": "^1.0.2",
        "psr/http-server-middleware": "^1.0.2",
        "psr/log": "^3.0",
        "psr/simple-cache": "^2.0 || ^3.0"
    },
    "replace": {
        "cakephp/cache": "self.version",
        "cakephp/collection": "self.version",
        "cakephp/console": "self.version",
        "cakephp/core": "self.version",
        "cakephp/database": "self.version",
        "cakephp/datasource": "self.version",
        "cakephp/event": "self.version",
        "cakephp/form": "self.version",
        "cakephp/http": "self.version",
        "cakephp/i18n": "self.version",
        "cakephp/log": "self.version",
        "cakephp/orm": "self.version",
        "cakephp/utility": "self.version",
        "cakephp/validation": "self.version"
    },
    "require-dev": {
        "cakephp/cakephp-codesniffer": "^5.0",
        "http-interop/http-factory-tests": "^2.0",
        "mikey179/vfsstream": "^1.6.10",
        "mockery/mockery": "^1.6",
        "paragonie/csp-builder": "^2.3 || ^3.0",
        "phpstan/phpstan": "1.11.*",
        "phpstan/extension-installer": "^1.3",
        "symplify/phpstan-rules": "^12.4",
        "phpunit/phpunit": "^10.5.5 || ^11.1.3"
    },
    "suggest": {
        "ext-curl": "To enable more efficient network calls in Http\\Client.",
        "ext-openssl": "To use Security::encrypt() or have secure CSRF token generation.",
        "lib-ICU": "To use locale-aware features in the I18n and Database packages",
        "paragonie/csp-builder": "CSP builder, to use the CSP Middleware"
    },
    "provide": {
        "psr/container-implementation": "^2.0",
        "psr/http-client-implementation": "^1.0",
        "psr/http-factory-implementation": "^1.0",
        "psr/http-server-handler-implementation": "^1.0",
        "psr/http-server-middleware-implementation": "^1.0",
        "psr/log-implementation": "^3.0",
        "psr/simple-cache-implementation": "^3.0"
    },
    "config": {
        "lock": false,
        "process-timeout": 900,
        "sort-packages": true,
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "phpstan/extension-installer": true
        }
    },
    "autoload": {
        "psr-4": {
            "Cake\\": "src/"
        },
        "files": [
            "src/Core/functions.php",
            "src/Error/functions.php",
            "src/Collection/functions.php",
            "src/I18n/functions.php",
            "src/ORM/bootstrap.php",
            "src/Routing/functions.php",
            "src/Utility/bootstrap.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Cake\\PHPStan\\": "tests/PHPStan/",
            "Cake\\Test\\": "tests/",
            "TestApp\\": "tests/test_app/TestApp/",
            "TestApp\\Test\\": "tests/test_app/TestApp/tests/",
            "TestPlugin\\": "tests/test_app/Plugin/TestPlugin/src/",
            "TestPlugin\\Test\\": "tests/test_app/Plugin/TestPlugin/tests/",
            "TestPluginTwo\\": "tests/test_app/Plugin/TestPluginTwo/src/",
            "Company\\TestPluginThree\\": "tests/test_app/Plugin/Company/TestPluginThree/src/",
            "Company\\TestPluginThree\\Test\\": "tests/test_app/Plugin/Company/TestPluginThree/tests/",
            "Named\\": "tests/test_app/Plugin/Named/src/"
        }
    },
    "scripts": {
        "check": [
            "@cs-check",
            "@test"
        ],
        "cs-check": "phpcs --colors --parallel=16 -p",
        "cs-fix": "phpcbf --colors --parallel=16 -p",
        "phpstan": "phpstan analyse",
        "psalm": "tools/psalm --show-info=false",
        "stan": [
            "@phpstan",
            "@psalm"
        ],
        "phpstan-tests": "phpstan analyze -c tests/phpstan.neon",
        "phpstan-baseline": "phpstan --generate-baseline",
        "psalm-baseline": "tools/psalm  --set-baseline=psalm-baseline.xml",
        "stan-setup": "phive install",
        "lowest": "validate-prefer-lowest",
        "lowest-setup": "composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction && cp composer.json composer.backup && composer require --dev dereuromark/composer-prefer-lowest && mv composer.backup composer.json",
        "test": "phpunit",
        "test-coverage": "phpunit --coverage-clover=clover.xml"
    },
    "support": {
        "issues": "https://github.com/cakephp/cakephp/issues",
        "forum": "https://stackoverflow.com/tags/cakephp",
        "irc": "irc://irc.freenode.org/cakephp",
        "source": "https://github.com/cakephp/cakephp"
    }
}
```
</details>

When I run this command: 

```
composer update --ignore-platform-req=php
```

I get the following output: 

```
Error: Composer\Platform\Runtime::invoke(): Argument #1 ($callable) must be of type callable, array given, called in phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php on line 341

In Runtime.php line 45:
                                                                               
  [TypeError]                                                                  
  Composer\Platform\Runtime::invoke(): Argument #1 ($callable) must be of typ  
  e callable, array given, called in phar:///usr/local/bin/composer/src/Compo  
  ser/Repository/PlatformRepository.php on line 341                            
                                                                               

Exception trace:
  at phar:///usr/local/bin/composer/src/Composer/Platform/Runtime.php:45
 Composer\Platform\Runtime->invoke() at phar:///usr/local/bin/composer/src/Composer/Repository/PlatformRepository.php:341
 Composer\Repository\PlatformRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:308
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/Installer.php:983
 Composer\Installer->createRequest() at phar:///usr/local/bin/composer/src/Composer/Installer.php:493
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:298
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:251
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:394
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:148
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:93
 require() at /usr/local/bin/composer:29
```

**Comment by ADmad** [comment]
Even though the class existence check for `ResourceBundle` succeeds, PHP says `['ResourceBundle', 'create']` is not a valid callable.

**Comment by shinsenter** [comment]
I also got a bunch of deprecated notices:

```
<warning>Deprecation Notice: JsonSchema\SchemaStorage::__construct(): Implicitly marking parameter $uriResolver as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php:19</warning>
<warning>Stack trace:</warning>
<warning> phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:427</warning>
<warning> phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Factory.php:85</warning>
<warning> phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/BaseConstraint.php:43</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php:252</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php:213</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Factory.php:316</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Factory.php:629</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Console/Application.php:550</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Console/Application.php:675</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Console/Application.php:274</warning>
<warning> phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171</warning>
<warning> phar:///usr/local/bin/composer/src/Composer/Console/Application.php:148</warning>
<warning> phar:///usr/local/bin/composer/bin/composer:93</warning>
<warning> /usr/local/bin/composer:29</warning>


Fatal error: Uncaught TypeError: Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash(): Argument #1 ($text) must be of type string, null given, called in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 47 and defined in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php:55
Stack trace:
#0 phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php(47): Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash(NULL)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(880): Symfony\Component\Console\Formatter\OutputFormatter::escape(NULL)
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(840): Symfony\Component\Console\Application->doRenderThrowable(Object(ErrorException), Object(Symfony\Component\Console\Output\StreamOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(154): Symfony\Component\Console\Application->renderThrowable(Object(ErrorException), Object(Symfony\Component\Console\Output\StreamOutput))
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(177): Symfony\Component\Console\Application->{closure:Symfony\Component\Console\Application::run():152}(Object(ErrorException))
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(148): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/local/bin/composer/bin/composer(93): Composer\Console\Application->run()
#7 /usr/local/bin/composer(29): require('...')
#8 {main}
  thrown in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 55
```

**Comment by Seldaek** [comment]
@ADmad can you check if you put this in a test.php script if it fails?

```
<?php

var_dump(class_exists('ResourceBundle'));

function foo(callable $f) {
    return $f('root', 'ICUDATA', false);
}

var_dump(foo(['ResourceBundle', 'create']));
```

And if so, I'd say it needs to be reported to the php-src repo because this code works on 8.3.

**Comment by LordSimal** [comment]
```
/var/www/html # php -v
PHP 8.4.0beta3 (cli) (built: Aug 16 2024 22:08:56) (NTS)
Copyright (c) The PHP Group
Built by https://github.com/docker-library/php
Zend Engine v4.4.0-dev, Copyright (c) Zend Technologies

/var/www/html # cat test.php 
<?php

var_dump(class_exists('ResourceBundle'));

function foo(callable $f) {
    return $f('root', 'ICUDATA', false);
}

var_dump(foo(['ResourceBundle', 'create']));

/var/www/html # php -f test.php 
bool(false)

Fatal error: Uncaught TypeError: foo(): Argument #1 ($f) must be of type callable, array given, called in /var/www/html/test.php on line 9 and defined in /var/www/html/test.php:5
Stack trace:
#0 /var/www/html/test.php(9): foo(Array)
#1 {main}
  thrown in /var/www/html/test.php on line 5
```

**Comment by ADmad** [comment]
So issue was that installing PHP using `shivammathur/setup-php` we were using a specific version `intl-72.1`. Apparently PHP 8.4 doesn't like INTL 72.1, using just `intl` got rid of the error.

Sorry for not noticing this earlier. Thank you for your time @Seldaek.

**Comment by Seldaek** [comment]
No worries. Glad you figured it out.
