### ISSUE TITLE
composer install not possible -   Call to undefined function Symfony\Component\Process\Pipes\stream_select()

### ISSUE THREAD

**Issue by vacy** [composer/composer#12061]
Hello devs,

i have a new install and run into basic runtime errors with composer as listed below with the call to undefined function.
To be frank, its not clean new install. I had it already running a year ago, was about to install another pkg and ran into this problems.
So i removed composer to bootstrap stuff, but can't figure out what is going wrong.

Got php 8.2.21 on for my rocky linux 9.4

Installed composer in these ways to check if things change:
2.7.7
- from remis repository
- and from your website 
- also tried dev snapshot 17f4984601835c549af73c847794743c960ec51c

I do not get any difference whether i am running this global or in a local directory as root or regular user.

My `composer.json`:

empty

Output of `composer diagnose`:

```
↳ composer diagnose
25.07.2024 20:10:48

Checking platform settings: OK
Checking git settings:
In AbstractPipes.php line 124:

  [Error]
  Call to undefined function Symfony\Component\Process\Pipes\stream_select()


Exception trace:
  at /usr/share/php/Composer/vendor/symfony/process/Pipes/AbstractPipes.php:124
 Symfony\Component\Process\Pipes\AbstractPipes->write() at /usr/share/php/Composer/vendor/symfony/process/Pipes/UnixPipes.php:105
 Symfony\Component\Process\Pipes\UnixPipes->readAndWrite() at /usr/share/php/Composer/vendor/symfony/process/Process.php:1439
 Symfony\Component\Process\Process->readPipes() at /usr/share/php/Composer/vendor/symfony/process/Process.php:1362
 Symfony\Component\Process\Process->updateStatus() at /usr/share/php/Composer/vendor/symfony/process/Process.php:368
 Symfony\Component\Process\Process->start() at /usr/share/php/Composer/vendor/symfony/process/Process.php:253
 Symfony\Component\Process\Process->run() at /usr/share/php/Composer/Util/ProcessExecutor.php:144
 Composer\Util\ProcessExecutor->runProcess() at /usr/share/php/Composer/Util/ProcessExecutor.php:189
 Composer\Util\ProcessExecutor->doExecute() at /usr/share/php/Composer/Util/ProcessExecutor.php:83
 Composer\Util\ProcessExecutor->execute() at /usr/share/php/Composer/Command/DiagnoseCommand.php:257
 Composer\Command\DiagnoseCommand->checkGit() at /usr/share/php/Composer/Command/DiagnoseCommand.php:112
 Composer\Command\DiagnoseCommand->execute() at /usr/share/php/Composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /usr/share/php/Composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:394
 Composer\Console\Application->doRun() at /usr/share/php/Composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:148
 Composer\Console\Application->run() at /usr/bin/composer:94

diagnose

PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Process\Pipes\stream_select() in /usr/share/php/Composer/vendor/symfony/process/Pipes/AbstractPipes.php:124
Stack trace:
#0 /usr/share/php/Composer/vendor/symfony/process/Pipes/UnixPipes.php(105): Symfony\Component\Process\Pipes\AbstractPipes->write()
#1 /usr/share/php/Composer/vendor/symfony/process/Process.php(1439): Symfony\Component\Process\Pipes\UnixPipes->readAndWrite()
#2 /usr/share/php/Composer/vendor/symfony/process/Process.php(1362): Symfony\Component\Process\Process->readPipes()
#3 /usr/share/php/Composer/vendor/symfony/process/Process.php(869): Symfony\Component\Process\Process->updateStatus()
#4 /usr/share/php/Composer/vendor/symfony/process/Process.php(921): Symfony\Component\Process\Process->isRunning()
#5 /usr/share/php/Composer/vendor/symfony/process/Process.php(219): Symfony\Component\Process\Process->stop()
#6 [internal function]: Symfony\Component\Process\Process->__destruct()
#7 {main}
  thrown in /usr/share/php/Composer/vendor/symfony/process/Pipes/AbstractPipes.php on line 124

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Process\Pipes\stream_select() in /usr/share/php/Composer/vendor/symfony/process/Pipes/AbstractPipes.php:124
Stack trace:
#0 /usr/share/php/Composer/vendor/symfony/process/Pipes/UnixPipes.php(105): Symfony\Component\Process\Pipes\AbstractPipes->write()
#1 /usr/share/php/Composer/vendor/symfony/process/Process.php(1439): Symfony\Component\Process\Pipes\UnixPipes->readAndWrite()
#2 /usr/share/php/Composer/vendor/symfony/process/Process.php(1362): Symfony\Component\Process\Process->readPipes()
#3 /usr/share/php/Composer/vendor/symfony/process/Process.php(869): Symfony\Component\Process\Process->updateStatus()
#4 /usr/share/php/Composer/vendor/symfony/process/Process.php(921): Symfony\Component\Process\Process->isRunning()
#5 /usr/share/php/Composer/vendor/symfony/process/Process.php(219): Symfony\Component\Process\Process->stop()
#6 [internal function]: Symfony\Component\Process\Process->__destruct()
#7 {main}
  thrown in /usr/share/php/Composer/vendor/symfony/process/Pipes/AbstractPipes.php on line 124

```

**Comment by xabbuh** [comment]
It looks like somehow your PHP doesn't have the [stream functions](https://www.php.net/manual/en/book.stream.php) installed.

**Comment by vacy** [comment]
maybe... for some reason... i mistakenly added stream_select to the disabled_functions... we won't talk about it, do we?

thank you
