### ISSUE TITLE
Fatal error: Uncaught Exception: Unable to open file D:\software\wamp64\www\mediawiki-1.36.4/extensions/Cargo/extension.json: filemtime(): stat failed for D:\software\wamp64\www\mediawiki-1.36.4/extensions/Cargo/extension.json in D:\software\wamp64\www\mediawiki-1.36.4\includes\registration\ExtensionRegistry.php:184 Stack trace: #0 D:\software\wamp64\www\mediawiki-1.36.4\includes\GlobalFunctions.php(52): ExtensionRegistry->queue('D:\\software\\wam...') #1 D:\software\wamp64\www\mediawiki-1.36.4\LocalSettings.php(148): wfLoadExtension('Cargo') #2 D:\software\wamp64\www\mediawiki-1.36.4\includes\Setup.php(145): require_once('D:\\software\\wam...') #3 D:\software\wamp64\www\mediawiki-1.36.4\maintenance\doMaintenance.php(90): require_once('D:\\software\\wam...') #4 D:\software\wamp64\www\mediawiki-1.36.4\maintenance\update.php(264): require_once('D:\\software\\wam...') #5 {main}   thrown in D:\software\wamp64\www\mediawiki-1.36.4\includes\registration\ExtensionRegistry.php on line 184

### ISSUE THREAD

**Issue by isqianqian** [composer/composer#12080]
How to solve this error?

**Comment by uuf6429** [comment]
@isqianqian how is the problem title longer than the problem description??
By the way, that's not a composer problem, the error is clearly coming from mediawikie..so you should ask there.
