### ISSUE TITLE
How to solve this issue in composer initialization.

### ISSUE THREAD

**Issue by newcharmingdev7** [composer/composer#12174]
C:\xampp\htdocs\Stephane>composer install

PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): CreateProcess failed, error code - 0' in phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:975
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): Cr...', 'phar://C:/compo...', 975, Array)
#1 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(975): proc_open('mode CON', Array, NULL, NULL, NULL, Array)
#2 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(748): Symfony\Component\Console\Application->getConsoleMode()
#3 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(714): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException(Object(ErrorException) in phar://C:/composer/composer.phar/vendor/symfony/console/Application.php on line 975

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): CreateProcess failed, error code - 0' in phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:975
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): Cr...', 'phar://C:/compo...', 975, Array)
#1 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(975): proc_open('mode CON', Array, NULL, NULL, NULL, Array)
#2 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(748): Symfony\Component\Console\Application->getConsoleMode()
#3 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(714): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar://C:/composer/composer.phar/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException(Object(ErrorException) in phar://C:/composer/composer.phar/vendor/symfony/console/Application.php on line 975

**Comment by Seldaek** [comment]
I've never seen this so really not sure what causes this, but can you check whether it's just the `proc_open('mode CON')` that fails by running Composer like this (assuming you run in cmd.exe)?

```
set COLUMNS=100
set LINES=30
composer install -vvv
```

Or for powershell:

```
$env:COLUMNS = '100';
$env:LINES = '30';
composer install -vvv
```

That should hopefully make it skip the failing bit here, but it'll still use proc_open for other things..
