### ISSUE TITLE
composer update failure

### ISSUE THREAD

**Issue by remco-pc** [composer/composer#12221]
Ran my composer update command in the right directory and got this error:

```bash
The repository at "/Application" does not have the correct ownership and git refuses to use it:

fatal: detected dubious ownership in repository at '/Application'
To add an exception for this directory, call:

        git config --global --add safe.directory /Application

Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading raxon/framework (dev-main 067e5d4 => dev-main a2feb98)
  - Upgrading raxon/parse (dev-main 50b3ba4 => dev-main 4aba0d4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading raxon/framework (dev-main a2feb98)
  - Syncing raxon/parse (dev-main 4aba0d4) into cache
  - Upgrading raxon/framework (dev-main 067e5d4 => dev-main a2feb98): Extracting archive
    Update of raxon/framework failed
Unhandled promise rejection with RuntimeException: Failed to extract raxon/framework as the installation was aborted by another package operation. in phar:///usr/bin/composer/src/Composer/Downloader/ZipDownloader.php:183
Stack trace:
#0 phar:///usr/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Downloader\ZipDownloader->Composer\Downloader\{closure}()
#1 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(173): React\Promise\Internal\FulfilledPromise->then()
#2 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#3 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle()
#4 phar:///usr/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}()
#5 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\FulfilledPromise->then()
#6 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#7 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle()
#8 [internal function]: React\Promise\Promise::React\Promise\{closure}()
#9 phar:///usr/bin/composer/src/Composer/Util/ProcessExecutor.php(367): call_user_func()
#10 phar:///usr/bin/composer/src/Composer/Util/Loop.php(90): Composer\Util\ProcessExecutor->countActiveJobs()
#11 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(670): Composer\Util\Loop->wait()
#12 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(224): Composer\Installer\InstallationManager->runCleanup()
#13 phar:///usr/bin/composer/src/Composer/Installer.php(839): Composer\Installer\InstallationManager->execute()
#14 phar:///usr/bin/composer/src/Composer/Installer.php(649): Composer\Installer->doInstall()
#15 phar:///usr/bin/composer/src/Composer/Installer.php(298): Composer\Installer->doUpdate()
#16 phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php(281): Composer\Installer->run()
#17 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\UpdateCommand->execute()
#18 phar:///usr/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#19 phar:///usr/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#20 phar:///usr/bin/composer/src/Composer/Console/Application.php(396): Symfony\Component\Console\Application->doRun()
#21 phar:///usr/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#22 phar:///usr/bin/composer/src/Composer/Console/Application.php(136): Symfony\Component\Console\Application->run()
#23 phar:///usr/bin/composer/bin/composer(93): Composer\Console\Application->run()
#24 /usr/bin/composer(29): require('...')
#25 {main}

In GitDownloader.php line 248:

  Failed to execute git show-ref --head -d

  fatal: detected dubious ownership in repository at '/Application/vendor/raxon/parse'
  To add an exception for this directory, call:

        git config --global --add safe.directory /Application/vendor/raxon/parse


update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--patch-only] [-i|--interactive] [--root-reqs] [--bump-after-update [BUMP-AFTER-UPDATE]] [--] [<packages>...]
```

running:

```bash
git config --global --add safe.directory /Application
```

```bash
composer update
```

```bash
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Downloading raxon/framework (dev-main a2feb98)
  - Syncing raxon/parse (dev-main 4aba0d4) into cache
  - Installing raxon/framework (dev-main a2feb98): Extracting archive
    Install of raxon/framework failed
Unhandled promise rejection with RuntimeException: Failed to extract raxon/framework as the installation was aborted by another package operation. in phar:///usr/bin/composer/src/Composer/Downloader/ZipDownloader.php:183
Stack trace:
#0 phar:///usr/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Downloader\ZipDownloader->Composer\Downloader\{closure}()
#1 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(173): React\Promise\Internal\FulfilledPromise->then()
#2 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#3 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle()
#4 phar:///usr/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}()
#5 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\FulfilledPromise->then()
#6 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#7 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle()
#8 [internal function]: React\Promise\Promise::React\Promise\{closure}()
#9 phar:///usr/bin/composer/src/Composer/Util/ProcessExecutor.php(367): call_user_func()
#10 phar:///usr/bin/composer/src/Composer/Util/Loop.php(90): Composer\Util\ProcessExecutor->countActiveJobs()
#11 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(670): Composer\Util\Loop->wait()
#12 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(224): Composer\Installer\InstallationManager->runCleanup()
#13 phar:///usr/bin/composer/src/Composer/Installer.php(839): Composer\Installer\InstallationManager->execute()
#14 phar:///usr/bin/composer/src/Composer/Installer.php(649): Composer\Installer->doInstall()
#15 phar:///usr/bin/composer/src/Composer/Installer.php(298): Composer\Installer->doUpdate()
#16 phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php(281): Composer\Installer->run()
#17 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\UpdateCommand->execute()
#18 phar:///usr/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#19 phar:///usr/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#20 phar:///usr/bin/composer/src/Composer/Console/Application.php(396): Symfony\Component\Console\Application->doRun()
#21 phar:///usr/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#22 phar:///usr/bin/composer/src/Composer/Console/Application.php(136): Symfony\Component\Console\Application->run()
#23 phar:///usr/bin/composer/bin/composer(93): Composer\Console\Application->run()
#24 /usr/bin/composer(29): require('...')
#25 {main}

In GitDownloader.php line 248:

  Failed to execute git show-ref --head -d

  fatal: detected dubious ownership in repository at '/Application/vendor/raxon/parse'
  To add an exception for this directory, call:

        git config --global --add safe.directory /Application/vendor/raxon/parse


update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--patch-only] [-i|--interactive] [--root-reqs] [--bump-after-update [BUMP-AFTER-UPDATE]] [--] [<packages>...]

```

```bash
git config --global --add safe.directory /Application/vendor/raxon/parse
```

```bash
composer update
```

```bash
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Downloading raxon/framework (dev-main a2feb98)
  - Syncing raxon/parse (dev-main 4aba0d4) into cache
  - Installing raxon/framework (dev-main a2feb98): Extracting archive
  - Upgrading raxon/parse (dev-main 50b3ba4 => dev-main 4aba0d4): Checking out 4aba0d455d from cache
Generating autoload files
25 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
```

Why the hell are you detecting the ownership of a .git repository ? Kiss (keep it simple stupid) none of your concerns !

https://github.com/raxon-org/framework/issues/1

**Comment by Seldaek** [comment]
Yeah why git added this feature I do not know. We're just trying to give you a hint how to fix it. The error `  fatal: detected dubious ownership in repository at '/Application/vendor/raxon/parse'` comes from git.

**Comment by d3vpasha** [comment]
Any update on this issue ? I think the problem comes from the fact that composer calls git to get some dependencies from git repositories. The issue might be with the fact that the user used for git clone is not the user with whom you execute the composer command.

**Comment by remco-pc** [comment]
@d3vpasha in my case i am running as root in a docker container. I think it should be www-data, but can someone point this out ?
