### ISSUE TITLE
Problem with installing Composer by Homebrew

### ISSUE THREAD

**Issue by iBobik** [composer/composer#3255]
Hi, I tried to install Composer by Homebrew as recommended [here](https://getcomposer.org/doc/00-intro.md#globally-on-osx-via-homebrew-), but it does not work.

Here is output of what I tried:

```
Bobik-MacBook-Pro:drupal-7 Bobik$ brew update
brew tap homebrew/homebrew-php
brew tap homebrew/dupes
brew tap homebrew/versions
brew install php55-intl
brew install homebrew/php/composer
Updated Homebrew from a916da27 to ee9769fe.
==> New Formulae
argyll-cms    csfml         espeak        syncthing     yubico-piv-tool
bokken        cwm           sync_gateway      ttylog
==> Updated Formulae
android-ndk       fontforge         libmemcached      readline
android-sdk       gcc           libtins       remctl
app-engine-java-sdk   gettext           libunistring      scrypt
apt-cacher-ng         git-cola          libvirt       sfml
aspcud            go-app-engine-32      lmdb          spiped
avrdude           go-app-engine-64      logstash          sqlitebrowser
bind              google-app-engine     mecab-ko          squid
binutils          gpsd          mongodb       svtplay-dl
boot2docker       gradle            mpd           tarsnap
cayley            graphicsmagick        mpdviz        tig
cgvg              gringo            nmap          unrar
clasp             groonga           node          vim
cmocka            gtk+3         open-sp       virtualhost.sh
cowpatty          httrack           passenger         yaws
dart              icecast           percona-server    youtube-dl
eigen             imagemagick       pianobar          zookeeper
elixir            jam           pkg-config        zsh
encfs             juju          postgresql
fits              jython            profanity
fleetctl          libcouchbase      rcssserver
==> Deleted Formulae
openfst        opengrm-ngram  rcsslogplayer  rcssmonitor
Bobik-MacBook-Pro:drupal-7 Bobik$ brew tap homebrew/homebrew-php
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 6970, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 6970 (delta 16), reused 4 (delta 3)
Receiving objects: 100% (6970/6970), 1.39 MiB | 435.00 KiB/s, done.
Resolving deltas: 100% (4532/4532), done.
Checking connectivity... done.
Tapped 420 formulae
Bobik-MacBook-Pro:drupal-7 Bobik$ brew tap homebrew/dupes
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 1324, done.
remote: Total 1324 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1324/1324), 264.20 KiB | 256.00 KiB/s, done.
Resolving deltas: 100% (714/714), done.
Checking connectivity... done.
Tapped 39 formulae
Bobik-MacBook-Pro:drupal-7 Bobik$ brew tap homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
remote: Counting objects: 2323, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 2323 (delta 1), reused 0 (delta 0)
Receiving objects: 100% (2323/2323), 754.88 KiB | 338.00 KiB/s, done.
Resolving deltas: 100% (1320/1320), done.
Checking connectivity... done.
Tapped 160 formulae
Bobik-MacBook-Pro:drupal-7 Bobik$ brew install php55-intl
Error: No available formula for php55-intl 
Searching taps...
Bobik-MacBook-Pro:drupal-7 Bobik$ brew install homebrew/php/composer
composer: Missing PHP53, PHP54, PHP55 or PHP56 from homebrew-php. Please install one of them before continuing
Error: An unsatisfied requirement failed this build.
Bobik-MacBook-Pro:drupal-7 Bobik$ brew install composer
composer: Missing PHP53, PHP54, PHP55 or PHP56 from homebrew-php. Please install one of them before continuing
Error: An unsatisfied requirement failed this build.
Bobik-MacBook-Pro:drupal-7 Bobik$ brew install php55
==> Installing dependencies for php55: freetype, gettext, icu4c, jpeg, unixodbc, ho
==> Installing php55 dependency: freetype
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/freetype-2.5.3_1.mave
######################################################################## 100,0%
==> Pouring freetype-2.5.3_1.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/freetype/2.5.3_1: 60 files, 2,5M
==> Installing php55 dependency: gettext
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/gettext-0.19.2.maveri
######################################################################## 100,0%
==> Pouring gettext-0.19.2.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X provides similar software, and installing this software in
parallel can cause all kinds of trouble.

OS X provides the BSD gettext library and some software gets confused if both are in the library path.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.2: 1920 files, 18M
==> Installing php55 dependency: icu4c
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/icu4c-53.1.mavericks.
######################################################################## 100,0%
==> Pouring icu4c-53.1.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts; see: https://github.com/Homebrew/homebrew/issues/issue/167

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include

==> Summary
🍺  /usr/local/Cellar/icu4c/53.1: 241 files, 57M
==> Installing php55 dependency: jpeg
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/jpeg-8d.mavericks.bot
######################################################################## 100,0%
==> Pouring jpeg-8d.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 780K
==> Installing php55 dependency: unixodbc
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/unixodbc-2.3.2.maveri
######################################################################## 100,0%
==> Pouring unixodbc-2.3.2.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/unixodbc/2.3.2: 31 files, 1012K
==> Installing php55 dependency: homebrew/dupes/zlib
==> Downloading http://zlib.net/zlib-1.2.8.tar.gz
######################################################################## 100,0%
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/zlib/1.2.8
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/zlib/lib
    CPPFLAGS: -I/usr/local/opt/zlib/include

==> Summary
🍺  /usr/local/Cellar/zlib/1.2.8: 9 files, 392K, built in 27 seconds
==> Installing php55 dependency: libtool
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libtool-2.4.2.maveric
######################################################################## 100,0%
==> Pouring libtool-2.4.2.mavericks.bottle.2.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.2: 66 files, 2,2M
==> Installing php55
==> Downloading http://www.php.net/get/php-5.5.16.tar.bz2/from/this/mirror
######################################################################## 100,0%
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.16 --localstatedir=/usr/local/var --s
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for pkg-config... no
configure: error: Cannot find OpenSSL's <evp.h>

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': Class is not a module (TypeError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:390:in `<class:HTTP>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:384:in `<module:Net>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:25:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/https.rb:21:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Library/Homebrew/utils.rb:308:in `open'
    from /usr/local/Library/Homebrew/utils.rb:350:in `issues_matching'
    from /usr/local/Library/Homebrew/utils.rb:378:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:162:in `fetch_issues'
    from /usr/local/Library/Homebrew/exceptions.rb:158:in `issues'
    from /usr/local/Library/Homebrew/exceptions.rb:197:in `dump'
    from /usr/local/Library/brew.rb:158:in `rescue in <main>'
    from /usr/local/Library/brew.rb:66:in `<main>'
Bobik-MacBook-Pro:drupal-7 Bobik$ brew install composer
composer: Missing PHP53, PHP54, PHP55 or PHP56 from homebrew-php. Please install one of them before continuing
Error: An unsatisfied requirement failed this build.
Bobik-MacBook-Pro:drupal-7 Bobik$ brew install php55-intl
Error: No available formula for php55-intl 
Searching taps...
Bobik-MacBook-Pro:drupal-7 Bobik$
```

**Comment by karlbecker** [comment]
Just a note that it looks like `brew install composer --ignore-dependencies` no longer works - as the docs only mention `curl` now, that's probably the only way now.
