### ISSUE TITLE
Invalid ZIP error for a few weeks now

### ISSUE THREAD

**Issue by avindra** [composer/composer#4332]
Hi,

We haven't been able to download from dist for several weeks (maybe months) now. We are  forced to use source, which takes quite long because composer doesn't clone with depth=1. Can someone help debug?

```
$ composer update -vvv
Reading ./composer.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/oracle/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/oracle/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /home/oracle/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/p-provider-2014-10.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/p-provider-2015-04.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json from cache
Downloading http://packagist.org/p/provider-latest$3b07827820eaa10695f2f89e76cc76d61d41a1f1a79232a70b5065890f07bd34.json
Writing /home/oracle/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-phpmailer$phpmailer.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-easybook$geshi.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-erusev$parsedown.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-filp$whoops.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-guzzlehttp$guzzle.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-guzzlehttp$psr7.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-guzzlehttp$promises.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-psr$http-message.json from cache
Reading /home/oracle/.composer/cache/repo/https---packagist.org/provider-symfony$process.json from cache
Analyzed 564 packages to resolve dependencies
Analyzed 67 rules to resolve dependencies
  - Installing phpmailer/phpmailer (v5.2.10)
Downloading https://api.github.com/repos/PHPMailer/PHPMailer/zipball/07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7
    Downloading: 100%
Writing /home/oracle/.composer/cache/files/phpmailer/phpmailer/07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7.zip into cache
    Extracting archive
Executing command (CWD): unzip '/app/myapp/vendor/phpmailer/phpmailer/1ae2dec0ddd65b714d123948d48c89f6' -d '/app/myapp/vendor/composer/c4aeedaf' && chmod -R u+w '/app/myapp/vendor/composer/c4aeedaf'
    Invalid zip file, retrying...
  - Installing phpmailer/phpmailer (v5.2.10)
Downloading https://api.github.com/repos/PHPMailer/PHPMailer/zipball/07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7
    Downloading: 100%
Writing /home/oracle/.composer/cache/files/phpmailer/phpmailer/07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7.zip into cache
    Extracting archive
Executing command (CWD): unzip '/app/myapp/vendor/phpmailer/phpmailer/1ae2dec0ddd65b714d123948d48c89f6' -d '/app/myapp/vendor/composer/c4aeedaf' && chmod -R u+w '/app/myapp/vendor/composer/c4aeedaf'
    Invalid zip file, retrying...
  - Installing phpmailer/phpmailer (v5.2.10)
Downloading https://api.github.com/repos/PHPMailer/PHPMailer/zipball/07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7
    Downloading: 100%
Writing /home/oracle/.composer/cache/files/phpmailer/phpmailer/07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7.zip into cache
    Extracting archive
Executing command (CWD): unzip '/app/myapp/vendor/phpmailer/phpmailer/1ae2dec0ddd65b714d123948d48c89f6' -d '/app/myapp/vendor/composer/c4aeedaf' && chmod -R u+w '/app/myapp/vendor/composer/c4aeedaf'
    Failed to download phpmailer/phpmailer from dist: '/app/myapp/vendor/phpmailer/phpmailer/1ae2dec0ddd65b714d123948d48c89f6' is not a zip archive.
    Now trying to download from source
  - Installing phpmailer/phpmailer (v5.2.10)
    Cloning 07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7
Executing command (CWD): git clone --no-checkout 'git://github.com/PHPMailer/PHPMailer.git' '/app/myapp/vendor/phpmailer/phpmailer' && cd '/app/myapp/vendor/phpmailer/phpmailer' && git remote add composer 'git://github.com/PHPMailer/PHPMailer.git' && git fetch composer
Executing command (/app/myapp/vendor/phpmailer/phpmailer): git remote set-url --push origin 'git@github.com:PHPMailer/PHPMailer.git'
Executing command (/app/myapp/vendor/phpmailer/phpmailer): git branch -r
Executing command (/app/myapp/vendor/phpmailer/phpmailer): git checkout 'v5.2.10' --
Executing command (/app/myapp/vendor/phpmailer/phpmailer): git reset --hard '07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7' --

    REASON: Required by root: Install command rule (install phpmailer/phpmailer v5.2.10)
```

**Comment by Seldaek** [comment]
The last error line indicates that ZipArchive::open() failed with ZipArchive::ER_NOZIP as return value. Why is a big question.. you should be able to inspect `/app/myapp/vendor/phpmailer/phpmailer/1ae2dec0ddd65b714d123948d48c89f6` after composer is done to see what's wrong with that file. You can compare it to a copy you download from https://api.github.com/repos/PHPMailer/PHPMailer/zipball/07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7 to see what went wrong in transit.. probably it gets truncated or modified somehow and then becomes corrupted.

**Comment by avindra** [comment]
Actually that file just doesn't exist after composer is done.

Strangely enough, I am using composer for the first time on Windows (was using Linux previously), and I am witnessing the same behavior on Windows.

**Comment by avindra** [comment]
Using PHP 5.6.12. I'm not sure if this PHP bug (recently marked as resolved in PHP 5.6.12) is related or not:

https://bugs.php.net/bug.php?id=70019

**Comment by Seldaek** [comment]
Ah right it is being downloaded in the vendor dir so the git clone fallback will wipe the file before doing the clone. Maybe you can interrupt it just before it does `Now trying to download from source` to get access to the zip and see what's up, or the easiest is probably to install composer from source and then you can put a die; statement in the ZipDownloader.php before line 76 I guess that's where it throws.

**Comment by simesy** [comment]
@avindra did you resolve this?

**Comment by avindra** [comment]
This still isn't resolved, although the error I am seeing now looks different with ```Composer version 1.0-dev (79ac2cac82cfdc5460fa378b758d9322d5422893) 2016-02-04 12:40:23```:

```
$ composer install -vvv
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Reading ./composer.json
Loading config file /home/user/.composer/config.json
Loading config file /home/user/.composer/auth.json
Loading config file ./composer.json
Executing command (/app/myapp): git describe --exact-match --tags
Executing command (/app/myapp): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/user/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Analyzed 71 packages to resolve dependencies
Analyzed 109 rules to resolve dependencies
  - Installing easybook/geshi (v1.0.8.15)
Downloading https://api.github.com/repos/easybook/geshi/zipball/54387de80bc7ee50397ffae39234626a48d2d45f
    Downloading: Connecting...    Download failed, retrying...
Downloading https://api.github.com/repos/easybook/geshi/zipball/54387de80bc7ee50397ffae39234626a48d2d45f
    Downloading: Connecting...    Download failed, retrying...
Downloading https://api.github.com/repos/easybook/geshi/zipball/54387de80bc7ee50397ffae39234626a48d2d45f
    Downloading: Connecting...
Failed: [Composer\Downloader\TransportException] 502: The "https://api.github.com/repos/easybook/geshi/zipball/54387de80bc7ee50397ffae39234626a48d2d45f" file could not be downloaded (HTTP/1.1 302 Found)
    Failed to download easybook/geshi from dist: The "https://api.github.com/repos/easybook/geshi/zipball/54387de80bc7ee50397ffae39234626a48d2d45f" file could not be downloaded (HTTP/1.1 302 Found)
    Now trying to download from source
  - Installing easybook/geshi (v1.0.8.15)
    Cloning 54387de80bc7ee50397ffae39234626a48d2d45f
````


Now, it looks like there's a 302 indicating that the zipball was found, but it fails to follow the redirect, it seems.

**Comment by Seldaek** [comment]
That is odd.. on <5.6 we now handle redirects manually but 5.6+ should handle redirects on its own. Do you have a proxy that might be doing odd things to your traffic? I think you'd have to debug this a bit more  yourself like looking at exact headers returned in RemoteFilesystem class etc.

**Comment by Scentyoo** [comment]
Hello, I have the same problem and errors like @avindra On older composer versions (sometime before christmas) I had no problems. I sit behind a corporate proxy and must define
`SET HTTP_PROXY=http://user:pass@company-proxy.com:8080`
`SET HTTPS_PROXY=http://user:pass@company-proxy.com:8080`
Maybe it is because I have to use `http://` for the `HTTPS_PROXY` ?

**Comment by Scentyoo** [comment]
I just found out, that the new php version 5.6. causes these problems. I installed on my PC where composer worked the new php version and then composer downloaded the source instead of dist.

**Comment by avindra** [comment]
FYI, this still isn't fixed:

```
Updating dependencies (including require-dev)
  - Installing phpmailer/phpmailer (v5.2.14)
    Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...    Failed to download phpmailer/phpmailer from dist: The "https://api.github.com/repos/PHPMailer/PHPMailer/zipball/e774bc9152de85547336e22b8926189e582ece95" file could not be downloaded (HTTP/1.1 302 Found)
    Now trying to download from source
  - Installing phpmailer/phpmailer (v5.2.14)
    Cloning e774bc9152de85547336e22b8926189e582ece95
```

**Comment by Seldaek** [comment]
OK sorry, what can we do though? Can you try again with the very latest composer and -vvv? I added some output about proxy URLs used. Are you using a proxy at all? If not then that won't help I guess :)

**Comment by Scentyoo** [comment]
Hello! As I mentioned `Checking HTTPS proxy support for request_fulluri: FAIL` is the problem. And it only happens since PHP 5.6.

**Comment by Seldaek** [comment]
@Scentyoo did you try to set HTTPS_PROXY_REQUEST_FULLURI=0 and then run composer diag again? https://getcomposer.org/doc/03-cli.md#https-proxy-request-fulluri

**Comment by Scentyoo** [comment]
I just tried (with 0 and false):
```
SET HTTP_PROXY=http://user:pass@company-proxy.com:8080
SET HTTPS_PROXY=http://user:pass@company-proxy.com:8080
SET HTTPS_PROXY_REQUEST_FULLURI=0
```
But it still fails (everything else is OK):
```
Checking HTTPS proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded (HTTP/1.1 302 Found))
```
@Seldaek What is the differce between PHP 5.5 and PHP 5.6 in handling the requests over proxy? And does my `HTTPS_PROXY` where I have to use `http` has any impact?

**Comment by Seldaek** [comment]
Please give the full output of a command that fails (ideally a real command, but I guess diagnose is ok too) when you run it with `-vvv`. Without that it's very hard to help. And I think if your proxy uses http on both it's ok as long as the proxy supports SSL eventually.. 

I'd think it should work with 5.6 and fail under, the other way is weird. There is a difference in that we handle redirects manually pre-5.6 and let php deal with them 5.6+. But php's behavior should work fine.

**Comment by Scentyoo** [comment]
```
composer diag -vvv
Checking CA file C:\Users\xxxxxx\AppData\Local\Temp\composer-cacert-xxxxxx.pem
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://packagist.org/packages.json using proxy tcp://company-proxy.com:8080
OK
Checking https connectivity to packagist: Downloading https://packagist.org/packages.json using proxy tcp://company-proxy.com:8080
OK
Checking HTTP proxy: Downloading https://packagist.org/packages.json using proxy tcp://company-proxy.com:8080
Downloading https://packagist.org/p/provider-2013$1e5638116dc94e6c7daadf10261204569279d78420396beb9d2aba8c717e112e.json using proxy tcp://company-proxy.com:8080
OK
Checking HTTP proxy support for request_fulluri: Downloading http://packagist.org/packages.json using proxy tcp://company-proxy.com:8080
OK
Checking HTTPS proxy support for request_fulluri: Downloading https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0 using proxy tcp://company-proxy.com:8080
Downloading https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0 using proxy tcp://company-proxy.com:8080
FAIL
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded (HTTP/1.1 302 Found))
Checking github.com oauth access: Downloading https://api.github.com/ using proxy tcp://company-proxy.com:8080
OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: xxxxxxxxxxxx
Dev Public Key Fingerprint: xxxxxxxxxxxx
OK
Checking composer version: Downloading https://getcomposer.org/version using proxy tcp://company-proxy.com:8080
OK
```

**Comment by Seldaek** [comment]
OK so it tries this twice.. weird, not sure why that is:

```
Downloading https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0 using proxy tcp://company-proxy.com:8080
Downloading https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0 using proxy tcp://company-proxy.com:8080
```

Anyway unfortunately this doesn't give me any more clue as to what is going on or why it'd fail for github requests on 5.6. It's always pretty hard to figure out proxy issues as they are environment specific.

**Comment by Scentyoo** [comment]
I believe it is hard with proxy settings... But if you have any tests I can do, please tell me. In which component of the code is this test `HTTPS proxy support for request_fulluri` performed? Am I able to extract part of the code to debug on my own PC?

**Comment by avindra** [comment]
I am also behind a proxy, but I can't see how the proxy is causing this...

**Comment by Seldaek** [comment]
Well I also can't see how, but I don't see why it would work for everyone else but not you two behind proxies. Proxies have led to many weird issues in the past. Unfortunately unless you do a lot of debugging on your own to figure out what is going on it is quite hard for us to help.

All the relevant code for proxy handling is in https://github.com/composer/composer/blob/master/src/Composer/Util/StreamContextFactory.php - then we use that for doing a file_get_content with context.

**Comment by wzrdtales** [comment]
This seems to be a bug with php itself and some special proxies. Just implement curl as alternative and set everything up to prefer curl if it is available over file_get_contents. It is faster and way more stable as it is used in thousands of other projects.

To examine this problem one would probably only need to debug through https://github.com/php/php-src/blob/1c295d4a9ac78fcc2f77d6695987598bb7abcb83/ext/standard/http_fopen_wrapper.c

**Comment by wzrdtales** [comment]
Also looked a bit into it right now as there are problems with one of the proxies. Strange is that at this point:
https://github.com/composer/composer/blob/master/src/Composer/Downloader/FileDownloader.php#L143-L145

We get an 502 (bad gateway) status code, but the error message itself tells the 302 from the header of the request which is correct, it is actually reporting a wrong status code there.

```php
Reading ./composer.json
Loading config file /home/tobi/.composer/config.json
Loading config file /home/tobi/.composer/auth.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/home/tobi/deploy/laravel): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/tobi/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/tobi/deploy/laravel/vendor/composer/installed.json
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.009 seconds
Analyzed 169 packages to resolve dependencies
Analyzed 408 rules to resolve dependencies
  - Installing doctrine/annotations (v1.2.7)
Downloading 
Error code from $e->code = 502
https://api.github.com/repos/doctrine/annotations/zipball/f25c8aab83e0c3e976fd7d19875f198ccf2f7535 using proxy tcp://10.1.1.190:8080
    Downloading: Failed       
exception 'Composer\Downloader\TransportException' with message 'The "https://api.github.com/repos/doctrine/annotations/zipball/f25c8aab83e0c3e976fd7d19875f198ccf2f7535" file could not be downloaded (HTTP/1.1 302 Found)' in /home/tobi/composer/src/Composer/Util/RemoteFilesystem.php:338
Stack trace:
#0 /home/tobi/composer/src/Composer/Util/RemoteFilesystem.php(84): Composer\Util\RemoteFilesystem->get('api.github.com', 'https://api.git...', Array, '/home/tobi/depl...', true)
#1 /home/tobi/composer/src/Composer/Downloader/FileDownloader.php(139): Composer\Util\RemoteFilesystem->copy('api.github.com', 'https://api.git...', '/home/tobi/depl...', true, Array)
#2 /home/tobi/composer/src/Composer/Downloader/FileDownloader.php(91): Composer\Downloader\FileDownloader->doDownload(Object(Composer\Package\CompletePackage), '/home/tobi/depl...', 'https://api.git...')
#3 /home/tobi/composer/src/Composer/Downloader/ArchiveDownloader.php(36): Composer\Downloader\FileDownloader->download(Object(Composer\Package\CompletePackage), '/home/tobi/depl...')
#4 /home/tobi/composer/src/Composer/Downloader/ZipDownloader.php(65): Composer\Downloader\ArchiveDownloader->download(Object(Composer\Package\CompletePackage), '/home/tobi/depl...')
#5 /home/tobi/composer/src/Composer/Downloader/DownloadManager.php(213): Composer\Downloader\ZipDownloader->download(Object(Composer\Package\CompletePackage), '/home/tobi/depl...')
#6 /home/tobi/composer/src/Composer/Installer/LibraryInstaller.php(176): Composer\Downloader\DownloadManager->download(Object(Composer\Package\CompletePackage), '/home/tobi/depl...')
#7 /home/tobi/composer/src/Composer/Installer/LibraryInstaller.php(90): Composer\Installer\LibraryInstaller->installCode(Object(Composer\Package\CompletePackage))
#8 /home/tobi/composer/src/Composer/Installer/InstallationManager.php(152): Composer\Installer\LibraryInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#9 /home/tobi/composer/src/Composer/Installer/InstallationManager.php(139): Composer\Installer\InstallationManager->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#10 /home/tobi/composer/src/Composer/Installer.php(569): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#11 /home/tobi/composer/src/Composer/Installer.php(228): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array, true)
#12 /home/tobi/composer/src/Composer/Command/InstallCommand.php(134): Composer\Installer->run()
#13 /home/tobi/composer/vendor/symfony/console/Command/Command.php(259): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/tobi/composer/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/tobi/composer/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/tobi/composer/src/Composer/Console/Application.php(181): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/tobi/composer/vendor/symfony/console/Application.php(123): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/tobi/composer/src/Composer/Console/Application.php(99): Symfony\Component\Console\Application->run(NULL, Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/tobi/composer/bin/composer(44): Composer\Console\Application->run()
#20 {main}    Download failed, retrying...
```

**Comment by avindra** [comment]
For others encountering this issue, I would  recommend installing [prestissimo](http://github.com/hirak/prestissimo), which parallelizes downloads and doesn't have this issue. It's a pretty good workaround until this is fixed in core.

**Comment by Seldaek** [comment]
Curious if this works any better with latest version of Composer? As we now handle redirects manually even on php 5.6+ it might help but not sure if the issue was in the redirect handling or not.

**Comment by avindra** [comment]
Latest version handles much better. Great work all on the stability!
