### ISSUE TITLE
No valid composer.json was found in any branch or tag of ...

### ISSUE THREAD

**Issue by PhillippOhlandt** [composer/composer#5287]
Hey,

I use the source of composer to get all available versions for a given repository.

Here is my class:

```
namespace App\Services;

use Composer\Config\JsonConfigSource;
use Composer\Factory;
use Composer\IO\NullIO;
use Composer\Json\JsonFile;
use Composer\Repository\VcsRepository;

class Composer
{
    protected $io;

    protected $config;

    public function __construct()
    {
        $this->io = new NullIO();
        $this->config = Factory::createConfig($this->io);
        $file = new JsonFile(config_path().'/github.json');

        if ($file->exists()) {
            $this->config->merge(array('config' => $file->read()));
        }
        $this->config->setAuthConfigSource(new JsonConfigSource($file, true));
    }

    public function getVersionsFromRepository($url)
    {
        $repository = new VcsRepository(['url' => $url], $this->io, $this->config);

        $versions = $repository->getPackages();

        $data = [];

        foreach ($versions as $version) {
            $item = [];

            $item['version'] = $version->getPrettyVersion();
            $item['requirements'] = collect($version->getRequires())->map(function($item){
                return $item->getPrettyConstraint();
            });

            $data[$version->getStability()][$version->getPrettyVersion()] = $item;
        }

        foreach($data as &$stability){
            ksort($stability);
            $stability = array_reverse($stability);
        }

        return $data;
    }
}
```

I run that for around 24 repositories in a laravel queue with background queue workers.

Sometimes it fails for a repository with the following log entry:

```
[2016-05-05 13:00:21] production.ERROR: Composer\Repository\InvalidRepositoryException: No valid composer.json was found in any branch or tag of http://github.com/damnlie/bolt-theme-readonly, could not load a package from it. in /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Repository/VcsRepository.php:271
Stack trace:
#0 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php(181): Composer\Repository\VcsRepository->initialize()
#1 /home/forge/boltthem.es/releases/20160505114805/app/Services/Composer.php(33): Composer\Repository\ArrayRepository->getPackages()
#2 /home/forge/boltthem.es/releases/20160505114805/app/Jobs/ImportOrUpdateTheme.php(61): App\Services\Composer->getVersionsFromRepository('http://github.c...')
#3 [internal function]: App\Jobs\ImportOrUpdateTheme->handle()
#4 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#5 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9467): Illuminate\Container\Container->call(Array)
#6 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ImportOrUpdateTheme))
#7 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9619): call_user_func(Object(Closure), Object(App\Jobs\ImportOrUpdateTheme))
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ImportOrUpdateTheme))
#9 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9601): call_user_func(Object(Closure), Object(App\Jobs\ImportOrUpdateTheme))
#10 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9474): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ImportOrUpdateTheme), Object(Closure))
#12 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#13 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(53): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#14 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\BeanstalkdJob->fire()
#15 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), '1', 0)
#16 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop('beanstalkd', 'default', 0, '10', '1')
#17 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon('beanstalkd', 'default', 0, '10', '1')
#18 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('beanstalkd', 'default', 0, 128, '10', '1')
#19 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker('beanstalkd', 'default', 0, 128, true)
#20 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#21 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#22 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#23 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /home/forge/boltthem.es/releases/20160505114805/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}
```

As I said, that just happens sometimes, not always.
Could it be an issue with GitHub being buggy?

**Comment by Seldaek** [comment]
Sounds like temporary network glitch for sure.

**Comment by PhillippOhlandt** [comment]
@Seldaek Ok, thanks for the quick answer. Would it help when I avoid running 3 queue workers at the same time?

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
