### ISSUE TITLE
Could not authenticate against github.com in ...

### ISSUE THREAD

**Issue by PhillippOhlandt** [composer/composer#5288]
Hey,

I use the source of composer to get all available versions for a given repository.

Here is my class:

```
namespace App\Services;

use Composer\Config\JsonConfigSource;
use Composer\Factory;
use Composer\IO\NullIO;
use Composer\Json\JsonFile;
use Composer\Repository\VcsRepository;

class Composer
{
    protected $io;

    protected $config;

    public function __construct()
    {
        $this->io = new NullIO();
        $this->config = Factory::createConfig($this->io);
        $file = new JsonFile(config_path().'/github.json');

        if ($file->exists()) {
            $this->config->merge(array('config' => $file->read()));
        }
        $this->config->setAuthConfigSource(new JsonConfigSource($file, true));
    }

    public function getVersionsFromRepository($url)
    {
        $repository = new VcsRepository(['url' => $url], $this->io, $this->config);

        $versions = $repository->getPackages();

        $data = [];

        foreach ($versions as $version) {
            $item = [];

            $item['version'] = $version->getPrettyVersion();
            $item['requirements'] = collect($version->getRequires())->map(function($item){
                return $item->getPrettyConstraint();
            });

            $data[$version->getStability()][$version->getPrettyVersion()] = $item;
        }

        foreach($data as &$stability){
            ksort($stability);
            $stability = array_reverse($stability);
        }

        return $data;
    }
}
```

I run that for around 24 repositories in a laravel queue with background queue workers.

Sometimes it fails with the following log entry:

```
[2016-05-05 13:00:22] production.ERROR: Composer\Downloader\TransportException: Could not authenticate against github.com in /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:556
Stack trace:
#0 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php(524): Composer\Util\RemoteFilesystem->promptAuthAndRetry(403, 'HTTP/1.1 403 Fo...')
#1 [internal function]: Composer\Util\RemoteFilesystem->callbackGet(10, 2, 'HTTP/1.1 403 Fo...', 403, 0, 0)
#2 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php(278): file_get_contents('https://api.git...', false, Resource id #441)
#3 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php(99): Composer\Util\RemoteFilesystem->get('github.com', 'https://api.git...', Array, NULL, false)
#4 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Repository/Vcs/VcsDriver.php(107): Composer\Util\RemoteFilesystem->getContents('github.com', 'https://api.git...', false)
#5 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Repository/Vcs/GitHubDriver.php(295): Composer\Repository\Vcs\VcsDriver->getContents('https://api.git...')
#6 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Repository/Vcs/GitHubDriver.php(214): Composer\Repository\Vcs\GitHubDriver->getContents('https://api.git...')
#7 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Repository/VcsRepository.php(140): Composer\Repository\Vcs\GitHubDriver->getTags()
#8 /home/forge/boltthem.es/releases/20160505114805/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php(181): Composer\Repository\VcsRepository->initialize()
#9 /home/forge/boltthem.es/releases/20160505114805/app/Services/Composer.php(33): Composer\Repository\ArrayRepository->getPackages()
#10 /home/forge/boltthem.es/releases/20160505114805/app/Jobs/ImportOrUpdateTheme.php(61): App\Services\Composer->getVersionsFromRepository('https://github....')
#11 [internal function]: App\Jobs\ImportOrUpdateTheme->handle()
#12 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#13 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9467): Illuminate\Container\Container->call(Array)
#14 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ImportOrUpdateTheme))
#15 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9619): call_user_func(Object(Closure), Object(App\Jobs\ImportOrUpdateTheme))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ImportOrUpdateTheme))
#17 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9601): call_user_func(Object(Closure), Object(App\Jobs\ImportOrUpdateTheme))
#18 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(9474): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ImportOrUpdateTheme), Object(Closure))
#20 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#21 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(53): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#22 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\BeanstalkdJob->fire()
#23 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), '1', 0)
#24 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop('beanstalkd', 'default', 0, '10', '1')
#25 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon('beanstalkd', 'default', 0, '10', '1')
#26 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('beanstalkd', 'default', 0, 128, '10', '1')
#27 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker('beanstalkd', 'default', 0, 128, true)
#28 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#29 /home/forge/boltthem.es/releases/20160505114805/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#30 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#31 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/forge/boltthem.es/releases/20160505114805/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/forge/boltthem.es/releases/20160505114805/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /home/forge/boltthem.es/releases/20160505114805/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 {main}
```

When I tested it for the first time on my local machine I had to accept GitHubs public key. Because I can't do that manually inside my queue workers, I created a `config` file inside `~/.ssh` with the following content to prevent host key checking:

```
Host github.com
    StrictHostKeyChecking no
```

That seems to work fine, but I still get the above error, **sometimes**.

Any idea what could be the reason for that and how to solve it?

**Comment by kamilsk** [comment]
https://developer.github.com/v3/#rate-limiting
```
HTTP/1.1 403 Forbidden
Date: Tue, 20 Aug 2013 14:50:41 GMT
Status: 403 Forbidden
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1377013266

{
   "message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
   "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by PhillippOhlandt** [comment]
@kamilsk I have a token, so that can't be the problem. In the third line of my constructor, you can see that I load a `github.json` file. It has the following content:

```
{
  "github-oauth": {
    "github.com": "902aba9309610047470b8c77301427XXXXXXXXXX"
  }
}
```

**Comment by kamilsk** [comment]
Could you provide response's headers when the error was repeated?

```

**Comment by kamilsk** [comment]
Could you provide some headers when the error persists?
```
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4966
X-RateLimit-Reset: 1372700873
```

Or could you provide more details about response (just try xdebug for this)?

**Comment by kamilsk** [comment]
For your token you can check the limit by this: https://developer.github.com/v3/rate_limit/

**Comment by PhillippOhlandt** [comment]
Sorry, I can't really give more info about this. It only happens in production and only on the queue workers. All fine locally. All I have is this log. 

But I checked the rate limit with the token I use:

```
{
  "resources": {
    "core": {
      "limit": 5000,
      "remaining": 4238,
      "reset": 1462458685
    },
    "search": {
      "limit": 30,
      "remaining": 30,
      "reset": 1462456553
    }
  },
  "rate": {
    "limit": 5000,
    "remaining": 4238,
    "reset": 1462458685
  }
}
```

**Comment by PhillippOhlandt** [comment]
@kamilsk Ok I debugged it now and it seems like composer doesn't use my token.

I played the dumping game in `Composer\Util\RemoteFilesystem` in the `get()` method.

When I do a `dump($http_response_header);` in the catch block on line `297` I get the following:

```
array:19 [
  0 => "HTTP/1.1 403 Forbidden"
  1 => "Server: GitHub.com"
  2 => "Date: Mon, 23 May 2016 18:45:35 GMT"
  3 => "Content-Type: application/json; charset=utf-8"
  4 => "Connection: close"
  5 => "Status: 403 Forbidden"
  6 => "X-RateLimit-Limit: 60"
  7 => "X-RateLimit-Remaining: 0"
  8 => "X-RateLimit-Reset: 1464031368"
  9 => "X-GitHub-Media-Type: github.v3; format=json"
  10 => "Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"
  11 => "Access-Control-Allow-Origin: *"
  12 => "Content-Security-Policy: default-src 'none'"
  13 => "Strict-Transport-Security: max-age=31536000; includeSubdomains; preload"
  14 => "X-Content-Type-Options: nosniff"
  15 => "X-Frame-Options: deny"
  16 => "X-XSS-Protection: 1; mode=block"
  17 => "Content-Encoding: gzip"
  18 => "X-GitHub-Request-Id: 52A1B363:1C0C1:5C23930:57434FCF"
]
```

And the requested URL is just `https://api.github.com/repos/nestordedios/bolt-theme-spatial`, so no token at all.

@Seldaek Any reasons it doesn't use the token I gave him?

**Comment by curry684** [comment]
As those are the response headers they're not really proving the token does not get sent in the request headers. I have also seen Github bug out occasionally for weird reasons when sending a lot of requests their way.

**Comment by PhillippOhlandt** [comment]
@curry684 it gets the requested URL with `file_get_contents()` so no additional headers.

**Comment by Seldaek** [comment]
@PhillippOhlandt the headers are part of the $context options. And the token is generally added in the URL but last minute before the file_get_contents() is called, so I hope you dumped it at the right point if you dumped the URL. If you look at the composer debug output, we don't show the token there to avoid leaking info.

Anyway looking at OP, it seems all you are missing in __construct is to do `$this->io->loadConfiguration($this->config)`. That should solve it.

**Comment by PhillippOhlandt** [comment]
Oh @Seldaek thanks! Now he uses the token. I hope this resolves the issue. Big Thank You!

**Comment by williamdes** [comment]
Found the solution: `rm ~/.composer/auth.json`
The token had expired.
