### ISSUE TITLE
out of memory on symfony 3 when adding FOSUserBundle (1.5GB is not enough!?)

### ISSUE THREAD

**Issue by cmroanirgo** [composer/composer#5345]
I am running a local virtual machine (ubuntu 14.04) with 1GB RAM. This is *after* increasing it from 512MB and adding a swap file. However, I still fail to run a simple command with the following composer.json:

```json
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "autoload-dev": {
        "psr-4": { "Tests\\": "tests/" }
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "symfony/assetic-bundle": "^2.8"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "platform": {
            "php": "5.5.9"
        }
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.0-dev"
        }
    }
}

```

As you can see, this is a bog-standard symfony 3 app. All I have been doing is following the Symfony 3 book (as I'm a n00b to it). I have 1GB RAM and ~500 MB swap: 

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          994M       216M       777M       6.4M        16M        80M
-/+ buffers/cache:       119M       874M
Swap:         509M       1.2M       508M
```

Php is allowed to use all memory:
/etc/php5/cli/php.ini has `memory_limit = -1`

When I run this command:

```
composer -vvv require friendsofsymfony/user-bundle "~2.0@dev"
```

I get this output:

```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/<user>/sites/main.dev): git branch --no-color --no-abbrev -v
Executing command (/home/<user>/sites/main.dev): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /home/<user>/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/<user>/sites/main.dev/vendor/composer/installed.json
Running 1.1.0 (2016-05-10 15:21:19) with PHP 5.5.9-1ubuntu4.16 on Linux / 3.13.0-24-generic
./composer.json has been updated
Reading ./composer.json
Loading config file ./composer.json
Executing command (/home/<user>/sites/main.dev): git branch --no-color --no-abbrev -v
Executing command (/home/<user>/sites/main.dev): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /home/<user>/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/<user>/sites/main.dev/vendor/composer/installed.json
Reading ./composer.lock
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/<user>/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-2015.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-2016-01.json from cache
Downloading http://packagist.org/p/provider-2016-04%2433de5a1ec268e3b2ef799248a3cf650b64a70e05bd2c6d4a7616001fcca2f855.json
Writing /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-2016-04.json into cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%2412c62381c02b968ecb3b8dfd60579737015df63d182730ee74a71fdcec11406e.json
Writing /home/<user>/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$lexer.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$annotations.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-twig$twig.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-util.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-paragonie$random-compat.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-php70.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-php56.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-mbstring.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$intl.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-intl-icu.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$icu.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-php54.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-psr$log.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$inflector.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$collections.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$cache.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$common.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-jdorn$sql-formatter.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$doctrine-bridge.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$doctrine-cache-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$dbal.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$console.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$framework-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$doctrine-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$security-acl.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$dependency-injection.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$config.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$event-dispatcher.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$http-kernel.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$filesystem.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$routing.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$stopwatch.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$templating.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$translation.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$http-foundation.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$finder.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$security-core.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$security-csrf.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$asset.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$class-loader.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$debug.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-php55.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$polyfill-apcu.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-ircmaxell$password-compat.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$instantiator.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-doctrine$orm.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$yaml.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-incenteev$composer-parameter-handler.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-sensiolabs$security-checker.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$process.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-sensio$distribution-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-sensio$framework-extra-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-monolog$monolog.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$monolog-bridge.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$monolog-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-swiftmailer$swiftmailer.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$swiftmailer-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-sensio$generator-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-kriswallsmith$assetic.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$assetic-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$symfony.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$phpunit-bridge.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$framework-standard-edition.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$swiftmailer-bridge.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-friendsofsymfony$user-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$form.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$security-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$twig-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$options-resolver.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$property-access.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$security.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$twig-bridge.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$locale.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-phpdocumentor$reflection.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$browser-kit.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$css-selector.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$debug-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$dom-crawler.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$expression-language.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$ldap.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$property-info.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$proxy-manager-bridge.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$security-guard.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$security-http.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$serializer.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$validator.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$var-dumper.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-symfony$web-profiler-bundle.json from cache
Reading /home/<user>/.composer/cache/repo/https---packagist.org/provider-kriswallsmith$spork.json from cache
Resolving dependencies through SAT
Dependency resolution completed in 0.779 seconds
Analyzed 6922 packages to resolve dependencies
Analyzed 335509 rules to resolve dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
  - Installing friendsofsymfony/user-bundle (dev-master abb35b9)
    Cloning abb35b94ed8ec78a504c9e1a2cd803d85d3ffad9
Executing command (CWD): git clone --no-checkout 'https://github.com/FriendsOfSymfony/FOSUserBundle.git' '/home/<user>/sites/main.dev/vendor/friendsofsymfony/user-bundle' && cd '/home/<user>/sites/main.dev/vendor/friendsofsymfony/user-bundle' && git remote add composer 'https://github.com/FriendsOfSymfony/FOSUserBundle.git' && git fetch composer
Failed: [ErrorException] proc_open(): fork failed - Cannot allocate memory

Installation failed, reverting ./composer.json to its original content.
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:954
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/loc...', 954, Array)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(954): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(ErrorException),  in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 954

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:954
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/loc...', 954, Array)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(954): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(ErrorException),  in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 954
```

And I expected this to happen:
Free beer ;)
What I *really* expect is that composer doesn't use gobs of memory for no discernible reason! Let's be frank: composer is a package management tool.... apt-get doesn't need 1GB RAM and swap, so why should  composer? It seems like there's an inherent architectural problem with this app.

**Comment by alcohol** [comment]
Using `@dev` and dev dependencies in general considerably grows the dependency graph that Composer has to solve. Also, it is known that Composer requires a lot of memory for solving a dependency graph. It is not an architectural problem, it is simply inherent to the language (PHP).

Keep in mind that Composer **only** needs a lot of memory when resolving dependencies (so `update`, or initial `install` without lock file). 1GB of memory is nothing for a dev box.
