### ISSUE TITLE
Composer Errors with HHVM's PHP-7 Mode - strtolower()

### ISSUE THREAD

**Issue by photodude** [composer/composer#6134]
My `composer.json`:

```json
{
    "name": "doctrine/dbal",
    "type": "library",
    "description": "Database Abstraction Layer",
    "keywords": ["dbal", "database", "persistence", "queryobject"],
    "homepage": "http://www.doctrine-project.org",
    "license": "MIT",
    "authors": [
        {"name": "Guilherme Blanco", "email": "guilhermeblanco@gmail.com"},
        {"name": "Roman Borschel", "email": "roman@code-factory.org"},
        {"name": "Benjamin Eberlei", "email": "kontakt@beberlei.de"},
        {"name": "Jonathan Wage", "email": "jonwage@gmail.com"}
    ],
    "require": {
        "php": "^7.0",
        "doctrine/common": "^2.7.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.4.6",
        "phpunit/phpunit-mock-objects": "!=3.2.4,!=3.2.5",
        "symfony/console": "2.*||^3.0"
    },
    "suggest": {
        "symfony/console": "For helpful console commands such as SQL execution and import of files."
    },
    "bin": ["bin/doctrine-dbal"],
    "autoload": {
        "psr-0": { "Doctrine\\DBAL\\": "lib/" }
    },
    "autoload-dev": {
        "psr-0": { "Doctrine\\Tests\\": "tests/" }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "2.6.x-dev"
        }
    },
    "archive": {
        "exclude": ["!vendor", "tests", "*phpunit.xml", ".travis.yml", "build.xml", "build.properties", "composer.phar"]
    }
}
```

When I run this command: 

```
composer install
```

I get the following output:
https://travis-ci.org/doctrine/dbal/jobs/198707689
```
[ErrorException]                                           
strtolower() expects parameter 1 to be string, null given 
```

And I expected this to happen:
Composer should work in HHVM php 7 mode `hhvm.php7.all = 1` note HHVM currently has the same behaviour as PHP 7 in strict mode `declare (strict_types=1)`. (see the HHVM issue, they are working to fix that issue... someday)

### related issues
- https://github.com/facebook/hhvm/issues/7198
- https://github.com/composer/composer/issues/5978

**Comment by photodude** [comment]
also note:
- `unserialize() must be an instance of string, null given`
- `ini_get_all() expects parameter 1 to be string, null given`

**Comment by stof** [comment]
Can you run the command in verbose mode, so that the stack trace of the exception is displayed in the output ?

**Comment by stof** [comment]
and if HHVM enforces the strict mode on all files, this could be an issue. In PHP, the strict mode is opt-in. HHVM should respect this

**Comment by photodude** [comment]
>and if HHVM enforces the strict mode on all files, this could be an issue. In PHP, the strict mode is opt-in. HHVM should respect this (composer does not opt-in for strict mode currently)

I believe the strict typing is being fixed with facebook/hhvm#7198

I'll see about doing a run in verbose mode and I'll post back with the results

**Comment by photodude** [comment]
@stof here is the verbose stuff

```php
Fatal error: Uncaught TypeError: Argument 1 passed to dirname() must be an instance of string, bool given in phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:141
Stack trace:
#0 (): dirname()
#1 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(141): SplFileInfo->getPath()
#2 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(117): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->isRewindable()
#3 (): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->rewind()
#4 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#5 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#6 (): RecursiveIteratorIterator->rewind()
#7 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#8 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#9 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#10 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#11 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#12 phar://composer.phar/bin/../src/../src/Composer/Cache.php(186): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#13 phar://composer.phar/bin/../src/../src/Composer/Downloader/FileDownloader.php(65): Composer\Cache->gc()
#14 phar://composer.phar/bin/../src/../src/Composer/Factory.php(485): Composer\Downloader\FileDownloader->__construct()
#15 phar://composer.phar/bin/../src/../src/Composer/Factory.php(357): Composer\Factory->createDownloadManager()
#16 phar://composer.phar/bin/../src/../src/Composer/Factory.php(569): Composer\Factory->createComposer()
#17 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(314): Composer\Factory::create()
#18 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(426): Composer\Console\Application->getComposer()
#19 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(131): Composer\Console\Application->getPluginCommands()
#20 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(124): Composer\Console\Application->doRun()
#21 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#22 phar://composer.phar/bin/composer(54): Composer\Console\Application->run()
#23 /home/travis/.phpenv/versions/hhvm-stable/bin/composer(24): include()
#24 {main}
```
exceptions in the verbose output
```
The command "composer install --verbose" failed. Retrying, 2 of 3.
Loading composer repositories with package information
                                                             
  [ErrorException]                                           
  strtolower() expects parameter 1 to be string, null given  
                                                             
Exception trace:
 () at phar://composer.phar/bin/../src/../src/Composer/Util/RemoteFilesystem.php:388
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 strtolower() at phar://composer.phar/bin/../src/../src/Composer/Util/RemoteFilesystem.php:388
 Composer\Util\RemoteFilesystem->get() at phar://composer.phar/bin/../src/../src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar://composer.phar/bin/../src/../src/Composer/Repository/ComposerRepository.php:665
 Composer\Repository\ComposerRepository->fetchFile() at phar://composer.phar/bin/../src/../src/Composer/Repository/ComposerRepository.php:479
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar://composer.phar/bin/../src/../src/Composer/Repository/ComposerRepository.php:258
 Composer\Repository\ComposerRepository->hasProviders() at phar://composer.phar/bin/../src/../src/Composer/DependencyResolver/Pool.php:99
 Composer\DependencyResolver\Pool->addRepository() at phar://composer.phar/bin/../src/../src/Composer/Installer.php:376
 Composer\Installer->doInstall() at phar://composer.phar/bin/../src/../src/Composer/Installer.php:223
 Composer\Installer->run() at phar://composer.phar/bin/../src/../src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar://composer.phar/bin/../src/../vendor/symfony/console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:850
 Symfony\Component\Console\Application->doRunCommand() at phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:227
 Composer\Console\Application->doRun() at phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://composer.phar/bin/composer:54
 include() at /home/travis/.phpenv/versions/hhvm-stable/bin/composer:24
```

**Comment by BenMorel** [comment]
Same problem here. My libraries are compatible with PHP 7 only, and I can't run my HHVM tests in PHP 7 compatibility mode on Travis because of this composer error.

I agree that HHVM should be fully compatible with PHP 7, and therefore composer should work in its current status; but still, couldn't we fix the small issues in composer that prevent it from working on the current HHVM version?

Passing `null` to `strtolower()` is not good practice anyway, and we can see this as an opportunity to improve the quality of the code base, not just as a fix to work with HHVM.

**Comment by Seldaek** [comment]
I fixed the one case that had a backtrace here.. I don't know if there are others, feel free to report new issues if you see more.

**Comment by BenMorel** [comment]
@Seldaek Thank you, there is another issue: #6230

**Comment by photodude** [comment]
Thanks @Seldaek I'll see about getting a verbose log and open a new issue for `[ErrorException] strpos() expects parameter 1 to be string, null given` https://travis-ci.org/photodude/dbal/jobs/208209738#L713

**Comment by BenMorel** [comment]
@photodude I'm not getting the `strtolower()` error anymore, it looks like this is the one @Seldaek just fixed. Did you try the latest composer snapshot?

**Comment by photodude** [comment]
@BenMorel I'm not getting the `strtolower()` error anymore. Just erroring on `strpos()` with the Doctrine DBAL repo

**Comment by BenMorel** [comment]
@photodude My bad, I misread it, I thought it was `strtolower()`. Anyway, can you test with the latest snapshot?

    wget https://getcomposer.org/composer.phar
    php composer.phar install

**Comment by photodude** [comment]
With `composer self-update` or with the latest snapshot via `wget` I get the `dirname()` issue reported in #6230
