### ISSUE TITLE
Composer Errors with HHVM's PHP-7 Mode - dirname()

### ISSUE THREAD

**Issue by BenMorel** [composer/composer#6230]
Following #6134, there is another issue when running composer on HHVM in PHP 7 compatibility mode:

> Fatal error: Uncaught TypeError: Argument 1 passed to dirname() must be an instance of string, bool given in phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:141

Stack trace:

```
#0 (): dirname()
#1 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(141): SplFileInfo->getPath()
#2 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(117): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->isRewindable()
#3 (): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->rewind()
#4 (): RecursiveIteratorIterator->rewind()
#5 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#6 phar://composer.phar/bin/../src/../src/Composer/Util/Filesystem.php(82): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#7 phar://composer.phar/bin/../src/../src/Composer/Downloader/FileDownloader.php(116): Composer\Util\Filesystem->emptyDirectory()
#8 phar://composer.phar/bin/../src/../src/Composer/Downloader/FileDownloader.php(93): Composer\Downloader\FileDownloader->doDownload()
#9 phar://composer.phar/bin/../src/../src/Composer/Downloader/ArchiveDownloader.php(36): Composer\Downloader\FileDownloader->download()
#10 phar://composer.phar/bin/../src/../src/Composer/Downloader/ZipDownloader.php(59): Composer\Downloader\ArchiveDownloader->download()
#11 phar://composer.phar/bin/../src/../src/Composer/Downloader/DownloadManager.php(213): Composer\Downloader\ZipDownloader->download()
#12 phar://composer.phar/bin/../src/../src/Composer/Installer/LibraryInstaller.php(186): Composer\Downloader\DownloadManager->download()
#13 phar://composer.phar/bin/../src/../src/Composer/Installer/LibraryInstaller.php(90): Composer\Installer\LibraryInstaller->installCode()
#14 phar://composer.phar/bin/../src/../src/Composer/Installer/InstallationManager.php(173): Composer\Installer\LibraryInstaller->install()
#15 phar://composer.phar/bin/../src/../src/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install()
#16 phar://composer.phar/bin/../src/../src/Composer/Installer.php(584): Composer\Installer\InstallationManager->execute()
#17 phar://composer.phar/bin/../src/../src/Composer/Installer.php(223): Composer\Installer->doInstall()
#18 phar://composer.phar/bin/../src/../src/Composer/Command/InstallCommand.php(119): Composer\Installer->run()
#19 phar://composer.phar/bin/../src/../vendor/symfony/console/Command/Command.php(267): Composer\Command\InstallCommand->execute()
#20 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(846): Symfony\Component\Console\Command\Command->run()
#21 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(191): Symfony\Component\Console\Application->doRunCommand()
#22 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(227): Symfony\Component\Console\Application->doRun()
#23 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(122): Composer\Console\Application->doRun()
#24 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#25 phar://composer.phar/bin/composer(54): Composer\Console\Application->run()
#26 /home/travis/build/brick/form/composer.phar(25): include()
#27 {main}
```

Full log [here](https://travis-ci.org/brick/form/jobs/208206676).

**Comment by photodude** [comment]
I am also having this issue here is my verbose output
```php
Fatal error: Uncaught TypeError: Argument 1 passed to dirname() must be an instance of string, bool given in phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:141
Stack trace:
#0 (): dirname()
#1 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(141): SplFileInfo->getPath()
#2 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(117): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->isRewindable()
#3 (): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->rewind()
#4 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#5 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#6 (): RecursiveIteratorIterator->rewind()
#7 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#8 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#9 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#10 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#11 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#12 phar://composer.phar/bin/../src/../src/Composer/Cache.php(186): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#13 phar://composer.phar/bin/../src/../src/Composer/Downloader/FileDownloader.php(65): Composer\Cache->gc()
#14 phar://composer.phar/bin/../src/../src/Composer/Downloader/RarDownloader.php(39): Composer\Downloader\FileDownloader->__construct()
#15 phar://composer.phar/bin/../src/../src/Composer/Factory.php(481): Composer\Downloader\RarDownloader->__construct()
#16 phar://composer.phar/bin/../src/../src/Composer/Factory.php(357): Composer\Factory->createDownloadManager()
#17 phar://composer.phar/bin/../src/../src/Composer/Factory.php(569): Composer\Factory->createComposer()
#18 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(314): Composer\Factory::create()
#19 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(426): Composer\Console\Application->getComposer()
#20 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(131): Composer\Console\Application->getPluginCommands()
#21 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(122): Composer\Console\Application->doRun()
#22 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#23 phar://composer.phar/bin/composer(54): Composer\Console\Application->run()
#24 /home/travis/build/photodude/dbal/composer.phar(25): include()
#25 {main}
```

**Comment by Seldaek** [comment]
I saw the second one but that one is in the symfony finder component so not much I can do about it I believe. Unless we are giving it a wrong input? Seems like the OP in this issue is also an issue in symfony rather than composer. Or perhaps it's even a bug in HHVM itself I'm not sure.. Seems to be triggered inside getPath from https://github.com/symfony/finder/blob/master/Iterator/RecursiveDirectoryIterator.php#L141 which calls the native code so if that fails I'm not sure what we can do.

**Comment by BenMorel** [comment]
That's a tricky one indeed. We would need to put a breakpoint somewhere to check what we pass to the `RecursiveDirectoryIterator` constructor: maybe a `bool` for the path? This could very well go unnoticed until this `getPath()` call.

Otherwise, it would look like an HHVM bug.

**Comment by photodude** [comment]
Technically it is a bug in HHVM...  HHVM currently has the same behavior as PHP 7 in strict mode when it's declare (strict_types=1). (see the HHVM issue, they are working to fix that issue... someday)

see https://github.com/facebook/hhvm/issues/7198

**Comment by Seldaek** [comment]
Yeah, as a workaround I'd suggest you run composer with php.. 7/7.1 are pretty fast and I doubt you will see much of a difference really (except less interop bugs..). Closing this here for now. If someone debugs it and can prove it's from our code I'll happily fix it, but given the HHVM market share I am not going to spend time on it myself sorry.

**Comment by BenMorel** [comment]
I guess we're all just using HHVM for our Travis CI test suites, to ensure that our libraries work with it. But for now, I'll happily keep it as an allowed failure.

**Comment by photodude** [comment]
I think we all had high hopes for HHVM and it's JIT implementation prior to php 7 being released so we added it to our testing platforms. Since php7.0/7.1 I've seen more and more projects abandoning HHVM support consideration at the same moment that HHVM is just starting to finally fix some blocker issues for major frameworks. It also doesn't help that very few hosts provide HHVM as an option outside of the VPS hosting arena.

**Comment by Seldaek** [comment]
Yup.. last time I checked there was less HHVM than PHP 5.3 users of composer, about 0.4% or smth IIRC, so not really worth the trouble I would say.

**Comment by BenMorel** [comment]
Just to put an end to this, I tried installing with a modified `composer.phar`, that adds the following lines to Symfony's `RecursiveDirectoryIterator` constructor:

    if (! is_string($path)) {
        var_dump($path);
        var_dump(debug_backtrace());
        die;
    }

But they weren't executed, and the same error was triggered as before. So I do believe this is a bug in HHVM, not an improper call in Composer or even in Symfony.
