### ISSUE TITLE
composer install error : No such file or directory in /var/www/vendor/composer/autoload_real.php:66

### ISSUE THREAD

**Issue by schwobr** [composer/composer#6402]
Hi, I'm running into the following issue :

My `composer.json`:

```json
{
    "name": "assurdeal/portal",
    "description": "The AssurDeal Portal.",
    "keywords": ["insurance", "broker", "porfolio", "assurdeal"],
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "doctrine/dbal": "~2.3",
        "genealabs/laravel-caffeine": "^0.4.1",
        "infyomlabs/laravel-generator": "5.3.x-dev",
        "infyomlabs/adminlte-templates": "5.3.x-dev",
        "jrean/laravel-user-verification": "^3.0",
        "kirkbushell/eloquence": "~2.0",
        "laravel/framework": "5.3.*",
        "laravelcollective/html": "5.3.*",
        "percymamedy/laravel-dev-booter": "^0.1.0",
        "predis/predis": "^1.1",
        "spatie/laravel-permission": "^1.5",
        "thomaswelton/laravel-gravatar": "^1.1",
        "spatie/laravel-menu": "^2.0",
        "mccool/laravel-auto-presenter": "^5.0",
        "waavi/translation": "~2.1",
        "mcamara/laravel-localization": "1.2.*"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.2",
        "barryvdh/laravel-debugbar": "^2.3",
        "fitztrev/query-tracer": "^1.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "rap2hpoutre/laravel-log-viewer": "^0.7.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "themsaid/laravel-mail-preview": "^1.2",
        "tightenco/mailthief": "^0.3.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "AssurDealSite\\": "app/"
        },
        "files": [
            "app/Support/helpers.php"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "extra": {
        "branch-alias": {
            "dev-master": "5.0-dev"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}



```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.infyomlabs/laravel-generator : exact version constraints (5.3.x-dev) should be avoided if the package follows semantic versioning
require.infyomlabs/adminlte-templates : exact version constraints (5.3.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.2.4 => 1.4.1)

```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
PHP Warning:  Uncaught ErrorException: require(/var/www/vendor/composer/../../app/Support/helpers.php): failed to open stream: No such file or directory in /var/www/vendor/composer/autoload_real.php:66
Stack trace:
#0 /var/www/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/var/ww...', '/var/www/vendor...', 66, Array)
#1 /var/www/vendor/composer/autoload_real.php(66): require()
#2 /var/www/vendor/composer/autoload_real.php(56): composerRequire85e6c7d88a85561dcb34f37cdac0b992('39258b87d261f8b...', '/var/www/vendor...')
#3 /var/www/vendor/autoload.php(7): ComposerAutoloaderInit85e6c7d88a85561dcb34f37cdac0b992::getLoader()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(17): require_once('/var/www/vendor...')
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(256): Illuminate\Foundation\ComposerScripts::postInstall(Object(Composer\Script\Event))
#6 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatche in /var/www/vendor/composer/autoload_real.php on line 66

Warning: Uncaught ErrorException: require(/var/www/vendor/composer/../../app/Support/helpers.php): failed to open stream: No such file or directory in /var/www/vendor/composer/autoload_real.php:66
Stack trace:
#0 /var/www/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/var/ww...', '/var/www/vendor...', 66, Array)
#1 /var/www/vendor/composer/autoload_real.php(66): require()
#2 /var/www/vendor/composer/autoload_real.php(56): composerRequire85e6c7d88a85561dcb34f37cdac0b992('39258b87d261f8b...', '/var/www/vendor...')
#3 /var/www/vendor/autoload.php(7): ComposerAutoloaderInit85e6c7d88a85561dcb34f37cdac0b992::getLoader()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(17): require_once('/var/www/vendor...')
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(256): Illuminate\Foundation\ComposerScripts::postInstall(Object(Composer\Script\Event))
#6 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatche in /var/www/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequire85e6c7d88a85561dcb34f37cdac0b992(): Failed opening required '/var/www/vendor/composer/../../app/Support/helpers.php' (include_path='.:/usr/share/php') in /var/www/vendor/composer/autoload_real.php on line 66

Fatal error: composerRequire85e6c7d88a85561dcb34f37cdac0b992(): Failed opening required '/var/www/vendor/composer/../../app/Support/helpers.php' (include_path='.:/usr/share/php') in /var/www/vendor/composer/autoload_real.php on line 66
```

And I expected this to happen:
Well, i just expect this to end without any error. I spent the whole day fighting against errors in order to install composer and start working on a project (that use docker-compose) and just as i expected it to end, i run into this one that i can't find a solution about. I saw there were some similar problems that happened to others but it was not the same file reported missing. Is it just that i searched it bad or is there a fresh solution ?

**Comment by stof** [comment]
These errors are happening in `Illuminate\Foundation\ComposerScripts::postInstall`, which is not part of Composer but of laravel/framework. Please report it there instead.

**Comment by schwobr** [comment]
Ok, sorry for the error.

**Comment by alcohol** [comment]
Not entirely sure that it the case here @stof.

Seems more related to this:

```
        "files": [
            "app/Support/helpers.php"
        ]
```

@schwobr does this file exist in your project? (case-sensitive)

**Comment by schwobr** [comment]
Actually it didn't exist, I reinstalled a new git repository and am facing new problems now. I may be facing this error again once i resolve the next ones, but I'm not sure, this subject might be closed.

**Comment by stof** [comment]
well, if you tell composer that a file must be loaded when registering the autoloader, but this file does not exist, your project is indeed broken. But it is not composer's fault.

**Comment by schwobr** [comment]
Actually i have no idea how this file disappeared, that's why it didn't even come to my mind...
