### ISSUE TITLE
whenever i try to use composer i get this source error

### ISSUE THREAD

**Issue by oaulakh** [composer/composer#6773]
When I run this command:
```
boo test $ composer init

                                            
  Welcome to the Composer config generator  
                                            


This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [boo/test]: 
Description []: 
Author [Author <abc@abc.com>, n to skip]: 
Minimum Stability []: 
Package Type (e.g. library, project, metapackage, composer-plugin) []: 
License []: 

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]? 
Search for a package: 
Would you like to define your dev dependencies (require-dev) interactively [yes]? 
Search for a package: 

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_encode() in /usr/share/php/Composer/Json/JsonFile.php:199
Stack trace:
#0 /usr/share/php/Composer/Command/InitCommand.php(119): Composer\Json\JsonFile::encode(Array)
#1 /usr/share/php/Symfony/Component/Console/Command/Command.php(259): Composer\Command\InitCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /usr/share/php/Symfony/Component/Console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/share/php/Symfony/Component/Console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InitCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/share/php/Composer/Console/Application.php(245): Symfony\Component\Console\Application->do in /usr/share/php/Composer/Json/JsonFile.php on line 199
boo test $ 
```
anyone???

**Comment by oaulakh** [comment]
http://paste.ubuntu.com/25852823/
syntax

**Comment by avant1** [comment]
Looks like your PHP installation has no `json` module enabled.
You can check it using the following command:
```bash
php -m | grep json
```

If the output is empty you should install and enable PHP `json` extension. Composer requires this extension.
