### ISSUE TITLE
Create project with a filesystem repository fails

### ISSUE THREAD

**Issue by apfelbox** [composer/composer#7038]
My `composer.json`:
–

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.2
PHP version: 7.2.1
PHP binary path: /usr/local/Cellar/php72/7.2.1_12/bin/ph
```

### Issue Description

I try to create a project from a local repository.
Create project with a `--repository-url` seems to be broken.

Reproduce case:

```
mkdir -p example/project
cd example/project
echo '{"name": "test/project"}' > composer.json
git init .
git add composer.json
git commit -m "test"
cd ..
composer create-project --repository-url=project/composer.json test/project install
```

And that last command fails with a fatal error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Composer\Package\Loader\ArrayLoader::load() must be of the type array, string given, called in phar:///usr/local/bin/composer/src/Composer/Repository/FilesystemRepository.php on line 63 and defined in phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:41
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/FilesystemRepository.php(63): Composer\Package\Loader\ArrayLoader->load('test/project')
#1 phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php(185): Composer\Repository\FilesystemRepository->initialize()
#2 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php(104): Composer\Repository\ArrayRepository->getPackages()
#3 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(290): Composer\DependencyResolver\Pool->addRepository(Object(Composer\Repository\FilesystemRepository))
#4 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(157): Comp in phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php on line 41
```

**Comment by apfelbox** [comment]
Ah, the repository url is for the packages repository, not the repository where the package is hosted.

Is there no way to `create-project` from a local repository?
