### ISSUE TITLE
Running docker exec as a Composer user defined script

### ISSUE THREAD

**Issue by RomanHodulak** [composer/composer#7110]
Hello,

has anyone ever tried running a command inside docker container from composer? I can't get it to work. Running these commands from regular terminal works.

Any hint or help is appreciated.

### From my `composer.json`:

```json
"scripts": {
    "console": "docker-compose exec -u user php /var/www/web/bin/console"
}
```
i.e. Run `/var/www/web/bin/console` on service `php` (which is `php-apache` container) as a user `user`.
 * `-u`: Run the command as this user.
### Outputs
```
> docker-compose -f docker/docker-compose.yml exec -u user php /var/www/web/bin/console
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dockerpty/pty.py", line 334, in start
    self._hijack_tty(pumps)
  File "/usr/lib/python3.6/site-packages/dockerpty/pty.py", line 367, in _hijack_tty
    read_ready, write_ready = io.select(read_pumps, write_streams, timeout=60)
  File "/usr/lib/python3.6/site-packages/dockerpty/io.py", line 59, in select
    timeout,
  File "/usr/lib/python3.6/site-packages/dockerpty/io.py", line 351, in fileno
    return self.from_stream.fileno()
  File "/usr/lib/python3.6/site-packages/dockerpty/io.py", line 103, in fileno
    return self.fd.fileno()
  File "/usr/lib/python3.6/socket.py", line 635, in fileno
    self._checkClosed()
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.18.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 124, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 467, in exec_command
    pty.start()
  File "/usr/lib/python3.6/site-packages/dockerpty/pty.py", line 338, in start
    io.set_blocking(pump, flag)
  File "/usr/lib/python3.6/site-packages/dockerpty/io.py", line 32, in set_blocking
    old_flag = fcntl.fcntl(fd, fcntl.F_GETFL)
  File "/usr/lib/python3.6/site-packages/dockerpty/io.py", line 351, in fileno
    return self.from_stream.fileno()
  File "/usr/lib/python3.6/site-packages/dockerpty/io.py", line 103, in fileno
    return self.fd.fileno()
  File "/usr/lib/python3.6/socket.py", line 635, in fileno
    self._checkClosed()
ValueError: I/O operation on closed file.
Script docker-compose -f docker/docker-compose.yml exec -u user php /var/www/web/bin/console handling the docker2 event returned with error code 1

```

### From `composer.json`:

```json
"scripts": {
    "console": "docker exec -tiu user php-apache /var/www/web/bin/console"
}
```
i.e. Run `/var/www/web/bin/console` on container `php-apache` as a user `user`. 
  * `-t`: Allocate a pseudo-TTY.
  * `-i`: Keep STDIN open even if not attached.
  * `-u`: Username or UID (format: <name|uid>[:<group|gid>]).

### Outputs
```
> docker exec -tiu user php-apache php /var/www/web/bin/console
the input device is not a TTY
Script docker exec -tiu user php-apache php /var/www/web/bin/console handling the docker event returned with error code 1
```

If I drop the -t option, then it works but I get no terminal colors.

**Comment by ferrastas** [comment]
You should use the `-T` flag to [disable the TTY allocation](https://docs.docker.com/compose/reference/exec/). 

```
"scripts":{
    "console": "/usr/local/bin/docker-compose exec -T fpm echo 'This is a test'"
},
```

```
$ composer run-script console
> /usr/local/bin/docker-compose exec -T fpm echo 'This is a test'
This is a test
```

**Comment by RomanHodulak** [comment]
@ferrastas Thank you for a nice answer. Yes, this indeed works but I would actually like to get this to work even with the TTY allocation. Would that be possible?

**Comment by Seldaek** [comment]
No that is not possible as we can not forward the TTY reliably on all platforms.

**Comment by b-hayes** [comment]
that option didn't work for me:
```
unknown shorthand flag: 'T' in -T
See 'docker exec --help'.
```

**Comment by ferrastas** [comment]
@b-hayes `-T` is an option for `docker-compose`.
```
$ docker-compose exec -h
Execute a command in a running container

Usage: exec [options] [-e KEY=VAL...] SERVICE COMMAND [ARGS...]

Options:
...
    -T                Disable pseudo-tty allocation. By default `docker-compose exec`
                      allocates a TTY.
...
```

If you want to disable TTY using `docker` command, you should use `-t`.
```
docker exec --help

Usage:	docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Run a command in a running container

Options:
  ...
  -t, --tty                  Allocate a pseudo-TTY
  ...
```
