### ISSUE TITLE
Composer Uncaught Error: Call to undefined function on create-project

### ISSUE THREAD

**Issue by MatheusRV** [composer/composer#7196]
phpbrew issue: https://github.com/phpbrew/phpbrew/issues/958

```
composer create-project --prefer-dist laravel/laravel sapiens
PHP Fatal error:  Uncaught Error: Call to undefined function JsonSchema\Uri\filter_var() in phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php:82
Stack trace:
#0 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(100): JsonSchema\Uri\UriResolver->resolve('phar:///bin/com...', 'internal://prov...')
#1 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(72): JsonSchema\SchemaStorage->expandRefs(Object(stdClass), 'internal://prov...')
#2 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(62): JsonSchema\SchemaStorage->addSchema('internal://prov...', Object(stdClass))
#3 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(82): JsonSchema\Validator->validate(Object(stdClass), Object(stdClass))
#4 phar:///bin/composer/src/Composer/Json/JsonFile.php(174): JsonSchema\Validator->check(Object(stdClass), Object(stdClass))
#5 phar:///bin/composer/src/Composer/Factory.ph in phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php on line 82

Fatal error: Uncaught Error: Call to undefined function JsonSchema\Uri\filter_var() in phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php:82
Stack trace:
#0 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(100): JsonSchema\Uri\UriResolver->resolve('phar:///bin/com...', 'internal://prov...')
#1 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(72): JsonSchema\SchemaStorage->expandRefs(Object(stdClass), 'internal://prov...')
#2 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(62): JsonSchema\SchemaStorage->addSchema('internal://prov...', Object(stdClass))
#3 phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(82): JsonSchema\Validator->validate(Object(stdClass), Object(stdClass))
#4 phar:///bin/composer/src/Composer/Json/JsonFile.php(174): JsonSchema\Validator->check(Object(stdClass), Object(stdClass))
#5 phar:///bin/composer/src/Composer/Factory.ph in phar:///bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php on line 82
```

**Comment by ryanaslett** [comment]
I had this same issue right after installing some phpbrew extensions. As soon as I closed and reopened my shell, composer behaved normally.

**Comment by alcohol** [comment]
Please provide a reproducible scenario.

Your original issue merely indicates to me that you've made a complete mess of your local environment. It does not indicate any problems actually related to Composer itself.

**Comment by alcohol** [comment]
Also, install Composer through one of the supported install methods. Brew is unsupported.

**Comment by ryanaslett** [comment]
This is definitely something related to phpbrew. I updated my old php 7.1.3 to 7.1.13 and got the same errors with composer. But Im 100% certain something with phpbrew is dorked, and nothing to do with composer other than it was the first php script I was attempting to run.

**Comment by Drupal-Infrastructure** [comment]
wow. I left a comment here 18 months ago and bumped into the same problem today upgrading to 7.2.23. Thanks for the solution !

**Comment by silentwarrior** [comment]
You are welcome :) 

I had solved this for some time and then casually saw it on a forgotten tab and decided to go investigate how I solved it to leave a straight answer behind. 

Glad I did, seems to help people 💪
