### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Composer\Autoload\ComposerStaticInit12b329b3bb5a50c8887651ad7396a012' not found in ...

### ISSUE THREAD

**Issue by narainsagar** [composer/composer#7293]
My `composer.json`:

```json
{
    "name": "root/public_html",
    "description": "SW-backend",
    "license": "MIT",
    "require": {
        "stripe/stripe-php": "~5.9.2",
        "google/recaptcha": "~1.1.3",
        "facebook/graph-sdk": "~5.6.2",
        "guzzlehttp/guzzle": "~6.3.0",
        "paragonie/random_compat": "~2.0.11",
        "hansott/pinterest-php": "~3.2.1"
    }
}
```

Output of `composer diagnose`:

```
$ php composer.phar diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.4
PHP version: 7.2.4
PHP binary path: /usr/local/bin/php
```

Hi, I've configured my Gitlab Pipeline to auto deploy files on my ftp server via `lftp` package.. Here's my `.gitlab-ci.yml` file configuration:

```code
# USERNAME, PASSWORD, HOST needs to be configured in Gitlab pipeline setting

# requiring the environment of PHP & NodeJS.
image: thecodingmachine/php:7.2-v1-cli-node8

before_script:
    # install / update required packages.
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq lftp
    - sudo apt-get --yes install zip unzip
    ## fresh installing composer (reference: https://getcomposer.org/download/)
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    # logging versions
    - php --version
    - php composer.phar --version
    - php composer.phar diagnose
    # setup / create project build (pre-deploy)
    # - php composer.phar clear-cache
    # - rm -rf vendor && rm -rf composer.lock
    - php composer.phar install
    - npm install
    - npm run build

# configuration for `staging` deployment
deploy_staging:
    stage: deploy
    script:
        - echo "Deploy to staging server"
        - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,\"$PASSWORD\" $HOST; mirror -Rev dist/ ./public_html/staging  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
    only:
        - develop

# configuration for `production` deployment
deploy_prod:
    stage: deploy
    script:
        - echo "Deploy to production server"
        - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,\"$PASSWORD\" $HOST; mirror -Rev dist/ ./public_html  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
    only:
        - master
```

You can see here that pipeline passes without any warnings / errors: 
<img width="768" alt="screen shot 2018-04-30 at 5 57 56 pm" src="https://user-images.githubusercontent.com/13800762/39428231-1c7e6830-4ca0-11e8-8a4b-834a919db6ae.png">

but when I browse over my deployed staging domain, I see following error..
```
Fatal error: Uncaught Error: Class 'Composer\Autoload\ComposerStaticInit12b329b3bb5a50c8887651ad7396a012' not found in /home/widgetsweeper/public_html/staging/vendor/composer/autoload_real.php:30 Stack trace: #0 /home/widgetsweeper/public_html/staging/vendor/autoload.php(7): ComposerAutoloaderInit12b329b3bb5a50c8887651ad7396a012::getLoader() #1 /home/widgetsweeper/public_html/staging/core/init.inc.php(57): require_once('/home/widgetswe...') #2 /home/widgetsweeper/public_html/staging/index.php(4): include('/home/widgetswe...') #3 {main} thrown in /home/widgetsweeper/public_html/staging/vendor/composer/autoload_real.php on line 30
```

I also tried with pushing local vendor/* files to server but it's not working (*same error)

Though when I run same locally it's working fine for me (not getting any error).. 

I did a lot of browsing for this issue but got no luck..

Can anybody tell me what's the issue and how it can be fixed ? Thanks.

**Comment by tomzx** [comment]
Did you make sure to delete the whole `vendor` directory when uploading your own? Might be an issue of being unable to overwrite `vendor/autoload.php`.

**Comment by narainsagar** [comment]
Hi @tomzx thanks for update - though the issue is already fixed, Yeah I remember I overwrite the whole vendors and it got fixed. Thanks for the help anyways. 👍 
I believe the issue can now be closed.

**Comment by Seldaek** [comment]
If you can't boil down your report to some smaller reproducible case I'm afraid it's gonna be hard to help.. It might be related to opcache settings or something on your production machine that makes things fail there only, I can only guess..
