### ISSUE TITLE
Update on HHVM fails due to "Seld/JsonLint: Cannot access empty property"

### ISSUE THREAD

**Issue by Krinkle** [composer/composer#7361]
The command that fails is the one that Travis CI runs by default, which is `composer self-update`.

<https://travis-ci.com/cssjanus/php-cssjanus/jobs/124698618>

```
2.73s$ composer self-update
Fatal error: Uncaught Error: Cannot access empty property in phar://composer.phar/bin/../src/../vendor/seld/jsonlint/src/Seld/JsonLint/JsonParser.php:391
Stack trace:
#0 phar://composer.phar/bin/../src/../vendor/seld/jsonlint/src/Seld/JsonLint/JsonParser.php(306): Seld\JsonLint\JsonParser->performAction()
#1 phar://composer.phar/bin/../src/../src/Composer/Factory.php(293): Seld\JsonLint\JsonParser->parse()
#2 phar://composer.phar/bin/../src/../src/Composer/Factory.php(576): Composer\Factory->createComposer()
#3 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(333): Composer\Factory::create()
#4 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(446): Composer\Console\Application->getComposer()
#5 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(149): Composer\Console\Application->getPluginCommands()
#6 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#7 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#8 phar://composer.phar/bin/composer(54): Composer\Console\Application->run()
#9 /home/travis/.phpenv/versions/hhvm-stable/bin/composer(25): include()
#10 {main}
$ php --version
HipHop VM 3.26.2 (rel)
```

The code in question is at https://github.com/Seldaek/jsonlint/blob/1.7.1/src/Seld/JsonLint/JsonParser.php#L391. Called from `JsonParser->performAction()` at https://github.com/Seldaek/jsonlint/blob/1.7.1/src/Seld/JsonLint/JsonParser.php#L360.

```php
                $yyval->token = new stdClass;
                $yyval->token->$property = $tokens[$len][1];
```

The same code is passing fine in PHP 5.5 to PHP 7.2.

**Comment by Krinkle** [comment]
I can reproduce the issue at <https://3v4l.org/iVHvG> with:
```php
<?php
$yyval = new stdClass;
$yyval->token = new stdClass;

$property = '';
$yyval->token->$property = 123;

echo $yyval->token->$property;
```

Which works PHP 4.3.0 - 5.0.4, PHP 7.1.0 - 7.2.4, but fails 5.0.5 - 5.6.30 and HHVM.

Interestingly, the JsonLint code has a check for `PHP_VERSION_ID < 70100` which should return true on HHVM, given HHVM has its default mode with PHP 7 features available whilst pretending to be PHP 5.6.99 for back-compat.

However, it seems some of the newer HHVM versions actually pretend to be PHP 7.1.99 by default.
