### ISSUE TITLE
composer -v preg_match(): JIT compilation failed: no more memory

### ISSUE THREAD

**Issue by mohamedsaqer** [composer/composer#7905]
composer -v

Fatal error: Uncaught ErrorException: preg_match(): JIT compilation failed: no more memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:767
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'preg_match(): J...', 'phar:///usr/loc...', 767, Array)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(767): preg_match('/;.(\\d+).rows;....', 'speed 9600 baud...', Array)
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(722): Symfony\Component\Console\Application->getTerminalDimensions()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(656): Symfony\Component\Console\Application->getTerminalWidth()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object(Symfony\Component\Console\Output\StreamOutput))
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(100): Symfony\Component\Console\A in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 767

mac: 10.13.6
PHP: 7.3.1

**Comment by Seldaek** [comment]
Seems like your machine ran out of memory?

**Comment by anhdq1801** [comment]
It work for me by follow steps:

    Please open you Terminal and run php --ini
    Open file php.ini in the path "Loaded Configuration File: /usr/local/php5/lib/php.ini" https://prnt.sc/p9tspy
    Find pcre.jit and change ;pcre.jit=1 to pcre.jit=0

**Comment by stof** [comment]
Note that Composer 2 should not suffer from that as much as Composer 1 anymore, because it will be able to use a newer version of symfony/console, where formatting regexes have been optimized.
