### ISSUE TITLE
Composer creates backwards symlink for path repositories during "composer update".

### ISSUE THREAD

**Issue by CameronHudson8** [composer/composer#8189]
My `composer.json`:

```json
{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "type": "project",
  "require": {
    "php": "^7.1.3",
    "barryvdh/laravel-cors": "^0.11.0",
    "doctrine/dbal": "^2.8",
    "fideloper/proxy": "^4.0",
    "guzzlehttp/guzzle": "^6.3",
    "laravel/framework": "^5.8.22",
    "laravel/tinker": "^1.0",
    "nesbot/carbon": "^2.19.2",
    "/": "*@dev"
  },
  "require-dev": {
    "filp/whoops": "^2.0",
    "fzaninotto/faker": "^1.4",
    "mockery/mockery": "^1.0",
    "nunomaduro/collision": "^3.0.1",
    "phpunit/phpunit": "^7.0"
  },
  "autoload": {
    "classmap": [
      "database/seeds",
      "database/factories"
    ],
    "psr-4": {
      "App\\": "app/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "repositories": [
    {
      "type": "path",
      "url": "lib/php-client/SwaggerClient-php"
    }
  ],
  "extra": {
    "laravel": {
      "dont-discover": []
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "@php artisan key:generate"
    ],
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover"
    ]
  },
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}
```
Contents of `composer.json` of local repository at `./lib/php-client/SwaggerClient-php`:
```json
{
    "name": "/",
    "description": "",
    "keywords": [
        "swagger",
        "php",
        "sdk",
        "api"
    ],
    "homepage": "http://swagger.io",
    "license": "proprietary",
    "authors": [
        {
            "name": "Swagger and contributors",
            "homepage": "https://github.com/swagger-api/swagger-codegen"
        }
    ],
    "require": {
        "php": ">=5.5",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "guzzlehttp/guzzle": "^6.2"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8",
        "squizlabs/php_codesniffer": "~2.6",
        "friendsofphp/php-cs-fixer": "~2.12"
    },
    "autoload": {
        "psr-4": { "Swagger\\Client\\" : "lib/" }
    },
    "autoload-dev": {
        "psr-4": { "Swagger\\Client\\" : "test/" }
    }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.6
PHP version: 7.3.6
PHP binary path: /usr/local/Cellar/php/7.3.6/bin/php
```

When I run this command:

```
composer update
```

I get the following output:

```
Deprecation warning: require./ is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 90 installs, 0 updates, 0 removals
  - Installing symfony/translation-contracts (v1.1.2): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing symfony/translation (v4.3.1): Loading from cache
  - Installing nesbot/carbon (2.19.2): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing / (dev-dev): Symlinking from lib/php-client/SwaggerClient-php
  - Installing jakub-onderka/php-console-color (v0.2): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.4): Loading from cache
  - Installing symfony/service-contracts (v1.1.2): Loading from cache
  - Installing symfony/polyfill-php73 (v1.11.0): Loading from cache
  - Installing symfony/console (v4.3.1): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.3.1): Loading from cache
  - Installing filp/whoops (2.3.1): Loading from cache
  - Installing nunomaduro/collision (v3.0.1): Loading from cache
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.11.0): Loading from cache
  - Installing symfony/mime (v4.3.1): Loading from cache
  - Installing symfony/http-foundation (v4.3.1): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.1): Loading from cache
  - Installing symfony/event-dispatcher (v4.3.1): Loading from cache
  - Installing symfony/http-kernel (v4.3.1): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing asm89/stack-cors (1.2.0): Loading from cache
  - Installing phpoption/phpoption (1.5.0): Loading from cache
  - Installing vlucas/phpdotenv (v3.4.0): Loading from cache
  - Installing symfony/css-selector (v4.3.1): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Loading from cache
  - Installing symfony/var-dumper (v4.3.1): Loading from cache
  - Installing symfony/routing (v4.3.1): Loading from cache
  - Installing symfony/process (v4.3.1): Loading from cache
  - Installing symfony/finder (v4.3.1): Loading from cache
  - Installing symfony/polyfill-iconv (v1.11.0): Loading from cache
  - Installing doctrine/lexer (1.0.2): Loading from cache
  - Installing egulias/email-validator (2.1.8): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.1): Loading from cache
  - Installing ramsey/uuid (3.8.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing opis/closure (3.3.0): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
  - Installing league/flysystem (1.0.52): Loading from cache
  - Installing erusev/parsedown (1.7.3): Loading from cache
  - Installing dragonmantank/cron-expression (v2.3.0): Loading from cache
  - Installing nikic/php-parser (v4.2.2): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing laravel/framework (v5.8.23): Loading from cache
  - Installing barryvdh/laravel-cors (v0.11.3): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/dbal (v2.9.2): Loading from cache
  - Installing fideloper/proxy (4.1.0): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing psy/psysh (v0.9.9): Loading from cache
  - Installing laravel/tinker (v1.0.8): Loading from cache
  - Installing fzaninotto/faker (v1.8.0): Loading from cache
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing mockery/mockery (1.2.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (2.0.1): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (4.2.2): Loading from cache
  - Installing sebastian/diff (3.0.2): Loading from cache
  - Installing sebastian/comparator (3.0.2): Loading from cache
  - Installing phpunit/php-timer (2.1.2): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.2): Loading from cache
  - Installing theseer/tokenizer (1.1.3): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (3.0.1): Loading from cache
  - Installing phpunit/php-code-coverage (6.1.4): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.1): Loading from cache
  - Installing phpspec/prophecy (1.8.1): Loading from cache
  - Installing phar-io/version (2.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.3): Loading from cache
  - Installing myclabs/deep-copy (1.9.1): Loading from cache
  - Installing phpunit/phpunit (7.5.12): Loading from cache
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/lock
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (^3.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (^1.0).)
laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
laravel/framework suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (^1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (^4.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (^1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (^3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (^4.2).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to use PSR-7 bridging features (^1.1).)
laravel/framework suggests installing wildbit/swiftmailer-postmark (Required to use Postmark mail driver (^3.0).)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.6.0)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Warning:  Uncaught ErrorException: require(/Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/../ralouphie/getallheaders/src/getallheaders.php): failed to open stream: No such file or directory in /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php:66
Stack trace:
#0 /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/Users/...', '/Users/cameronh...', 66, Array)
#1 /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php(66): require()
#2 /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php(56): composerRequire05ac5d5562846d77bae810e64cbbfa15('7b11c4dc42b3b30...', '/Users/cameronh...')
#3 /Users/cameronhudson/Repositories in /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php on line 66

Warning: Uncaught ErrorException: require(/Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/../ralouphie/getallheaders/src/getallheaders.php): failed to open stream: No such file or directory in /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php:66
Stack trace:
#0 /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/Users/...', '/Users/cameronh...', 66, Array)
#1 /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php(66): require()
#2 /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php(56): composerRequire05ac5d5562846d77bae810e64cbbfa15('7b11c4dc42b3b30...', '/Users/cameronh...')
#3 /Users/cameronhudson/Repositories in /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequire05ac5d5562846d77bae810e64cbbfa15(): Failed opening required '/Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/../ralouphie/getallheaders/src/getallheaders.php' (include_path='.:/usr/local/Cellar/php/7.3.6/share/php/pear') in /Users/cameronhSudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php on line 66

Fatal error: composerRequire05ac5d5562846d77bae810e64cbbfa15(): Failed opening required '/Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/../ralouphie/getallheaders/src/getallheaders.php' (include_path='.:/usr/local/Cellar/php/7.3.6/share/php/pear') in /Users/cameronhudson/Repositories/Personal/IskPrinter-Site/backend/lib/php-client/SwaggerClient-php/composer/autoload_real.php on line 66
```

And I expected this to happen:

Successful generation of optimized autoload files, which is currently failing. This is because the `ralouphie/getallheaders` dependency, as well as all other dependencies specific to the local repository, are not present when generation of optimized autoload files begins.
You can see from the output that composer does, in fact, install this dependency. However, at this line
```
  - Installing / (dev-dev): Symlinking from lib/php-client/SwaggerClient-php
```
instead of creating a symlink that points from `./lib/php-client/SwaggerClient-php/vendor` to `./vendor`, it creates a symlink that points from `./vendor` to `./lib/php-client/SwaggerClient-php`.

I suspect that when composer creates this link it overwrites a directory `./lib/php-client/SwaggerClient-php/vendor` where it had installed dependencies specific to the local repository.

What I expected to happen was for composer to install all dependencies into a central `./vendor` directory, then create a symlink that points from `./lib/php-client/SwaggerClient-php/vendor` to `./vendor`.

![composer creates backward symlink](https://user-images.githubusercontent.com/35085463/59569557-297ee700-9040-11e9-986d-f4ef332fe0b5.png)

![Screen Shot 2019-06-16 at 14 09 06](https://user-images.githubusercontent.com/35085463/59569579-634fed80-9040-11e9-820b-53c2ec6b0205.png)

My current workaround involves using using the `files` parameter in the `autoload` section of my main `./composer.json`,
```json
...
  "autoload": {
    "classmap": [
      "database/seeds",
      "database/factories"
    ],
    "psr-4": {
      "App\\": "app/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    },
    "files": [
      "lib/php-client/SwaggerClient-php/vendor/autoload.php"
    ]
  },
...
```
and installing the dependencies of the repository before installing the main dependencies.
```sh
composer update -d "./lib/php-client/SwaggerClient-php"
composer install -d "./lib/php-client/SwaggerClient-php"
composer update
composer install
```

**Comment by alcohol** [comment]
You seem to misunderstand how path repositories work. Composer would never symlink from one vendor directory to another. It will only symlink to the one specific package.

https://getcomposer.org/doc/05-repositories.md#path
