### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#8193]
I have PHP 7.4.0alpha1. When I run `composer`, the following happens:

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ComposerAutoloaderInitComposerPhar1560258186::getLoader(), 0 passed in phar:///usr/local/bin/composer/vendor/autoload.php on line 16 and exactly 0 expected in phar:///usr/local/bin/composer/vendor/composer/autoload_real.php:112
Stack trace:
#0 phar:///usr/local/bin/composer/vendor/autoload.php(16): ComposerAutoloaderInitComposerPhar1560258186::getLoader()
#1 phar:///usr/local/bin/composer/src/bootstrap.php(15): include('phar:///usr/loc...')
#2 phar:///usr/local/bin/composer/src/bootstrap.php(13): includeIfExists('phar:///usr/loc...')
#3 phar:///usr/local/bin/composer/bin/composer(8): require('phar:///usr/loc...')
#4 /usr/local/bin/composer(24): require('phar:///usr/loc...')
#5 {main}
  thrown in phar:///usr/local/bin/composer/vendor/composer/autoload_real.php on line 112
The command '/bin/sh -c composer' returned a non-zero code: 255
```

**Comment by GrahamCampbell** [comment]
In particular, it seems to be happening only when I install xdebug. When I remove it, it works correctly.

**Comment by alcohol** [comment]
Perhaps @derickr can take a look at this?

**Comment by derickr** [comment]
Works for me:

```
derick@gargleblaster:/tmp$ php -v
PHP 7.4.0-dev (cli) (built: Jun 17 2019 20:09:30) ( NTS DEBUG )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0-dev, Copyright (c), by Zend Technologies
    with Xdebug v2.8.0-dev, Copyright (c) 2002-2019, by Derick Rethans
```

```
derick@gargleblaster:/tmp$ php ~/composer.phar require zetacomponents/template
Using version ^1.5 for zetacomponents/template
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing zetacomponents/base (1.9.1): Loading from cache
  - Installing zetacomponents/template (1.5): Loading from cache
Writing lock file
Generating autoload files
```

**Comment by alcohol** [comment]
@GrahamCampbell can you provide more specific version information for both Composer and PHP, and any possible plugins you might have installed?

**Comment by GrahamCampbell** [comment]
Dockerfile:

```
FROM php:7.4-rc-cli

RUN apt-get update && apt-get -y install git libmemcached-dev libpng-dev libsqlite3-dev libxml2-dev libzip-dev unzip wget zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install bcmath gd opcache pcntl pdo pdo_sqlite soap zip

RUN git clone git://github.com/php-memcached-dev/php-memcached.git && cd php-memcached && phpize && ./configure --enable-sasl --enable-sasl-pwdb --prefix="${HOME}/cache/memcached-sasl-3" && make && make install && cd ../ && rm -rf php-memcached && docker-php-ext-enable memcached

RUN git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug && make && make install && cd ../ && rm -rf xdebug && docker-php-ext-enable xdebug

RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini && rm $PHP_INI_DIR/php.ini-development
RUN sed 's/short_open_tag=On/short_open_tag=Off/' $PHP_INI_DIR/php.ini
RUN echo "memory_limit = 2048M" >> $PHP_INI_DIR/conf.d/memory-limit.ini
RUN echo "upload_max_filesize = 128M" >> /usr/local/etc/php/conf.d/memory-limit.ini
RUN echo "post_max_size = 128M" >> /usr/local/etc/php/conf.d/memory-limit.ini

ENV COMPOSER_ALLOW_SUPERUSER 1
COPY --from=registry.gitlab.com/grahamcampbell/php:7.3 /usr/local/bin/composer /usr/local/bin/composer
```

**Comment by GrahamCampbell** [comment]
NB The composer installer crashes, which is why I copy the composer binary from another image.

To replicate the original error, build, put the above in a `Dockerfile`, then in the same directory, run:

```
docker build -t registry.gitlab.com/grahamcampbell/php:7.4 .
```

and then run:

```
docker run -it --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.4
```

This will produce the error in the OP.

---

xdebug and opcache are both installed. To see this, run:

```
docker run -it --entrypoint php registry.gitlab.com/grahamcampbell/php:7.4 -v
```

This gives me:

```
PHP 7.4.0alpha1 (cli) (built: Jun 17 2019 20:23:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0alpha1, Copyright (c), by Zend Technologies
    with Xdebug v2.8.0-dev, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by stof** [comment]
@GrahamCampbell do you have anything registered as preload file in your PHP 7.4 php.ini ? that might be a difference.

**Comment by GrahamCampbell** [comment]
Even with this more minimal configuration (without opcache), it doesn't work:

```
FROM php:7.4-rc-cli

RUN apt-get update && apt-get -y install git && rm -rf /var/lib/apt/lists/*

RUN git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug && make && make install && cd ../ && rm -rf xdebug && docker-php-ext-enable xdebug

ENV COMPOSER_ALLOW_SUPERUSER 1
COPY --from=registry.gitlab.com/grahamcampbell/php:7.3 /usr/local/bin/composer /usr/local/bin/composer
```

This produces:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function ComposerAutoloaderInitComposerPhar1560258186::getLoader(), 0 passed in phar:///usr/local/bin/composer/vendor/autoload.php on line 16 and exactly 0 expected in phar:///usr/local/bin/composer/vendor/composer/autoload_real.php on line 112

ArgumentCountError: Too few arguments to function ComposerAutoloaderInitComposerPhar1560258186::getLoader(), 0 passed in phar:///usr/local/bin/composer/vendor/autoload.php on line 16 and exactly 0 expected in phar:///usr/local/bin/composer/vendor/composer/autoload_real.php on line 112

Call Stack:
    0.0001     392016   1. {main}() /usr/local/bin/composer:0
    0.0058     636576   2. require('phar:///usr/local/bin/composer/bin/composer') /usr/local/bin/composer:24
    0.0061     639160   3. require('phar:///usr/local/bin/composer/src/bootstrap.php') phar:///usr/local/bin/composer/bin/composer:8
    0.0061     639160   4. includeIfExists() phar:///usr/local/bin/composer/src/bootstrap.php:13
    0.0062     640848   5. include('phar:///usr/local/bin/composer/vendor/autoload.php') phar:///usr/local/bin/composer/src/bootstrap.php:15
    0.0072     654224   6. ComposerAutoloaderInitComposerPhar1560258186::getLoader() phar:///usr/local/bin/composer/vendor/autoload.php:16

```

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell do you have anything registered as preload file in your PHP 7.4 php.ini ? that might be a difference.

In that minimal config, there is no php.ini file at all.

**Comment by stof** [comment]
`0 passed and exactly 0 expected`. That's indeed wonky...

**Comment by stof** [comment]
@derickr you are on 7.4.0-dev while @GrahamCampbell is on 7.4.0alpha1. could it be the reason for not reproducing the issue ?

**Comment by alcohol** [comment]
The error itself seems to have been introduced in 7.1 though, but given the context I do not understand why it would fail (0 expected, 0 passed, should be right.. feels like the check itself is off): https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.too-few-arguments-exception

**Comment by GrahamCampbell** [comment]
Hmm, looking through https://github.com/php/php-src/compare/php-7.4.0alpha1...PHP-7.4, I don't see why it would crash on 7.4.0alpha1, but not the latest 7.4 dev version.

**Comment by GrahamCampbell** [comment]
Working with the php 7.4alpha2 release. :)
