### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by frinck** [composer/composer#8214]
My `Uncaught Exception`:

```json
file_put_contents(/var/www/html/install/install.lock): failed to open stream: Permission denied
```

Output of `composer diagnose`:

```
Origin
install/routes.php on line 284
```

When I run this command:

```
when i install 
```

I get the following output:

```
Trace
#0 [internal function]: System\error::native(2, 'file_put_conten...', '/var/www/html/i...', 284, Array)
#1 /var/www/html/install/routes.php(284): file_put_contents('/var/www/html/i...', 1562410164)
#2 [internal function]: {closure}()
#3 /var/www/html/system/route.php(142): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/system/router.php(105): System\route->run()
#5 /var/www/html/system/start.php(41): System\router->dispatch()
#6 /var/www/html/install/index.php(34): require('/var/www/html/s...')
#7 {main}
```

And I expected this to happen:
install success

**Comment by alcohol** [comment]
Not a Composer issue.
