### ISSUE TITLE
`composer outdated` calls isAbandoned on my PHP-generated package extending Package class

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#8638]
I think CompletePackage implements isAbandoned.

Output of `composer diagnose`:

```
Changed current directory to /home/viktor/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.stecman/composer-bash-completion-plugin : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.9.0 => 1.9.3)
Composer version: 1.9.0
PHP version: 7.3.14
PHP binary path: /usr/bin/php7.3
```

When I run this command:

```
composer outdated
```

I get the following output:

```
PHP Fatal error:  Uncaught Error: Call to undefined method SzepeViktor\Composer\Envato\EnvatoPackage::isAbandoned() in phar:///usr/local/bin/composer/src/Composer/Command/ShowCommand.php:388

Stack trace:
#0 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\ShowCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\ShowCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(267): Symfony\Component\Con in phar:///usr/local/bin/composer/src/Composer/Command/ShowCommand.php on line 388
```

**Comment by stof** [comment]
Some code seems to expect all packages to be CompletePackage instances...

**Comment by szepeviktor** [comment]
Thanks!!
Maybe you could tame those codes.

**Comment by alcohol** [comment]
Not sure I understand the issue here. The error you are referencing is in code not maintained by us:

```
PHP Fatal error:  Uncaught Error: Call to undefined method SzepeViktor\Composer\Envato\EnvatoPackage::isAbandoned() in phar:///usr/local/bin/composer/src/Composer/Command/ShowCommand.php:388
```

**Comment by szepeviktor** [comment]
@alcohol Please reopen as @stof said above that even ArrayPackage-s are treated as CompletePackage
Thank you.

**Comment by alcohol** [comment]
I'm not sure what your point is. The code expects a `CompletePackage`. It has been like that since 2018 according to git annotations. It works for everyone, except you. But you implemented your own Package class. Just add the method you are missing?

**Comment by szepeviktor** [comment]
That is done: https://github.com/szepeviktor/composer-envato/commit/8a765da3b0dd3267bf933ad0b094d7144fd74365

I'd like Composer to work consistently.

**Comment by alcohol** [comment]
> I'd like Composer to work consistently.

Missing some context here. The outdated functionality seems to expect a `CompletePackage`, what is not consistent about that?

**Comment by szepeviktor** [comment]
> The outdated functionality seems to expect a `CompletePackage`, what is not consistent about that?

That I declare my packages as `class EnvatoPackage extends Package`

**Comment by alcohol** [comment]
Okay I am sorry but I really don't understand why you think our code should match your expectations, instead of the other way around?

**Comment by szepeviktor** [comment]
Okay.
I'm fine with the current situation.
