### ISSUE TITLE
Composer 1.10.6 downloads package, which has dependency for composer-runtime-api ^2.0

### ISSUE THREAD

**Issue by patrjam** [composer/composer#8881]
Hi,

in our project (_php >=7.1_) we use `symplify/easy-coding-standard: ^6.0`, which has dependency for `jean85/pretty-package-versions`. 

we have Dockerfile with dependency of `composer:1`, which we use in CI. From release `1.10.6` we have had problem with code style checking, it has thrown
 
```
Fatal error: Uncaught Error: Class 'Composer\InstalledVersions' not found in /usr/src/app/vendor/jean85/pretty-package-versions/src/PrettyVersions.php:13
--
07-May-2020 07:40:40 | Stack trace:
07-May-2020 07:40:40 | #0 /usr/src/app/vendor/symplify/easy-coding-standard/packages/Configuration/src/Configuration.php(110): Jean85\PrettyVersions::getVersion('symplify/easy-c...')
07-May-2020 07:40:40 | #1 /usr/src/app/vendor/symplify/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php(31): Symplify\EasyCodingStandard\Configuration\Configuration->getPrettyVersion()
07-May-2020 07:40:40 | #2 /tmp/easy_coding_standard/ContainerVwvreQQ/getEasyCodingStandardConsoleApplicationService.php(9): Symplify\EasyCodingStandard\Console\EasyCodingStandardConsoleApplication->__construct(Object(Symplify\EasyCodingStandard\Configuration\Configuration), Array)
07-May-2020 07:40:40 | #3 /tmp/easy_coding_standard/ContainerVwvreQQ/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd2f4bb9664f3631a24596df0372c1d4bd38038Container.php(150): require('/tmp/easy_codin...')
07-May-2020 07:40:40 | #4 /usr/src/app/vendor/symfony/dependency-injection/Co in /usr/src/app/vendor/jean85/pretty-package-versions/src/PrettyVersions.php on line 13
```

I found, error messages of `jean85/pretty-package-versions` are from version `1.4.0`, but it does not make sense, because this version has dependency for `composer-runtime-api ^2.0`, so it should not install for our `composer:1`. 
For `composer:1.10.5` works everything right and it downloads `jean85/pretty-package-versions 1.3.0`, but from `composer:1.10.6` it returns `jean85/pretty-package-versions 1.4.0`.

```
build	07-May-2020 07:39:58	Step 1/7 : FROM composer:1 AS build
build	07-May-2020 07:39:59	 ---> 79d01906a618
build	07-May-2020 07:39:59	Step 2/7 : COPY . /app
build	07-May-2020 07:40:00	 ---> f67146054e45
build	07-May-2020 07:40:00	Step 3/7 : RUN make clean
build	07-May-2020 07:40:00	 ---> Running in 5dbf6b4cabd1
build	07-May-2020 07:40:01	rm -rf vendor
build	07-May-2020 07:40:01	rm -f composer.lock
build	07-May-2020 07:40:01	Removing intermediate container 5dbf6b4cabd1
build	07-May-2020 07:40:01	 ---> fb6568c40408
build	07-May-2020 07:40:01	Step 4/7 : RUN composer install   --no-interaction   --no-scripts   --prefer-dist   --ignore-platform-reqs
build	07-May-2020 07:40:01	 ---> Running in 3b74cac60c19
build	07-May-2020 07:40:06	[91mLoading composer repositories with package information
build	07-May-2020 07:40:06	[0m[91mUpdating dependencies (including require-dev)
build	07-May-2020 07:40:23	[0m[91mPackage operations: 95 installs, 0 updates, 0 removals
build	07-May-2020 07:40:23	[0m[91m  - Installing ocramius/package-versions (1.8.0): [0m[91mDownloading (connecting...)[0m[91mDownloading (0%)           [0m[91mDownloading (95%)[0m[91mDownloading (100%)[0m[91m
build	07-May-2020 07:40:23	[0m[91m  - Installing psr/simple-cache (1.0.1): [0m[91mDownloading (connecting...)[0m[91mDownloading (0%)           [0m[91mDownloading (100%)[0m[91m
build	07-May-2020 07:40:24	[0m[91m  - Installing jean85/pretty-package-versions (1.4.0): [0m[91mDownloading (connecting...)[0m[91mDownloading (0%)           [0m[91mDownloading (100%)[0m[91m
```

Our actual "hack" was add `jean85/pretty-package-versions 1.3.0` to `composer.json`, but it is not solution.

So, why `composer 1.10.6` downloads dependencies for `composer-runtime-api ^2.0`?

**Comment by Seldaek** [comment]
I suspect you are not running yet with 1.10.6, because for me with that it installs jean85/pretty-package-versions 1.3.0 just fine.

**Comment by Seldaek** [comment]
Ah sorry now I see what is causing the problem you're running with `--ignore-platform-reqs`. composer-runtime-api is a platform requirement and as such ignoring it is not a great idea. Maybe use platform config instead? https://getcomposer.org/doc/06-config.md#platform
