### ISSUE TITLE
autoload_real.php on line 69

### ISSUE THREAD

**Issue by Gellish** [composer/composer#9037]
My `composer.json`:

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "codexshaper/laravel-database-manager": "^1.1",
        "consoletvs/charts": "^6.5",
        "fideloper/proxy": "^4.0",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "6.0",
        "khill/lavacharts": "^3.1",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "predis/predis": "^1.1",
        "protoqol/prequel": "v1.22.4",
        "pusher/pusher-chatkit-server": "^1.6",
        "pusher/pusher-php-server": "~4.0",
        "realrashid/sweet-alert": "^2.0",
        "spatie/laravel-analytics": "^3.10",
        "symfony/console": "4.3.4",
        "tymon/jwt-auth": "^1.0",
        "uxweb/sweet-alert": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "laravel/dusk": "^5.6",
        "laravel/telescope": "^2.1"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Library\\": "app/library/"
        },
        "files": [
            "app/Utils/helpers.php"
        ],
        "classmap": [
            "database",
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

Output of `composer diagnose`:

Checking platform settings: The Windows OneDrive folder is not supported on PHP versions below 7.2.23 and 7.3.10.
Upgrade your PHP (7.3.2) to use this location with Composer.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.0-RC => 1.10.8)
Composer version: 1.10.0-RC
PHP version: 7.3.2
PHP binary path: C:\laragon\bin\php\php-7.3.2-Win32-VC15-x64\php.exe
OpenSSL version: OpenSSL 1.1.1a  20 Nov 2018

When I run this command:

```
composer install
```

I get the following output:

```
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Generating optimized autoload files
Deprecation Notice: Class Protoqol\Prequel\App\ControllerAction located in C:/laragon/www/gellish/vendor/protoqol/prequel/src\Laravel\ControllerAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class Protoqol\Prequel\App\FactoryAction located in C:/laragon/www/gellish/vendor/protoqol/prequel/src\Laravel\FactoryAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class Protoqol\Prequel\App\MigrationAction located in C:/laragon/www/gellish/vendor/protoqol/prequel/src\Laravel\MigrationAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class Protoqol\Prequel\App\ModelAction located in C:/laragon/www/gellish/vendor/protoqol/prequel/src\Laravel\ModelAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class Protoqol\Prequel\App\ResourceAction located in C:/laragon/www/gellish/vendor/protoqol/prequel/src\Laravel\ResourceAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class Protoqol\Prequel\App\SeederAction located in C:/laragon/www/gellish/vendor/protoqol/prequel/src\Laravel\SeederAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class Khill\Lavacharts\Support\RenderableTrait located in C:/laragon/www/gellish/vendor/khill/lavacharts/src\Support\Renderable.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\FollowsController located in C:/laragon/www/gellish/app\Http\Controllers\Pages\FollowsController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\MessagesController located in C:/laragon/www/gellish/app\Http\Controllers\Pages\MessagesController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\PagesController located in C:/laragon/www/gellish/app\Http\Controllers\Pages\PagesController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\ProfilesController located in C:/laragon/www/gellish/app\Http\Controllers\Pages\ProfilesController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\Auth\ForgotPasswordController located in C:/laragon/www/gellish/app\Http\Controllers\User\Auth\ForgotPasswordController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\Auth\ResetPasswordController located in C:/laragon/www/gellish/app\Http\Controllers\User\Auth\ResetPasswordController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\Auth\VerificationController located in C:/laragon/www/gellish/app\Http\Controllers\User\Auth\VerificationController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\User\Users\HomeController located in C:/laragon/www/gellish/app\Http\Controllers\User\HomeController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Http\Controllers\ProfilesController located in C:/laragon/www/gellish/app\Http\Controllers\User\Users\ProfilesController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Warning: Ambiguous class resolution, "App\Http\Controllers\ProfilesController" was found in both "C:/laragon/www/gellish/app\Http\Controllers\Pages\ProfilesController.php" and "C:/laragon/www/gellish/app\Http\Controllers\User\Users\ProfilesController.php", the first will be used.
Deprecation Notice: Class App\Http\Controllers\Admin\UserController located in C:/laragon/www/gellish/app\Http\Controllers\UserController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Warning: Ambiguous class resolution, "App\Http\Controllers\Admin\UserController" was found in both "C:/laragon/www/gellish/app\Http\Controllers\Admin\UserController.php" and "C:/laragon/www/gellish/app\Http\Controllers\UserController.php", the first will be used.
Deprecation Notice: Class App\Libraries\GoogleAnalytics located in C:/laragon/www/gellish/app\libraries\GoogleAnalytics.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\Message located in C:/laragon/www/gellish/app\Model\admin\Message.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\blog_post located in C:/laragon/www/gellish/app\Model\user\blog_post.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class App\skills located in C:/laragon/www/gellish/app\Model\user\skills.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/laragon/bin/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185
> Illuminate\Foundation\ComposerScripts::postAutoloadDump

Warning: Uncaught ErrorException: require(C:\laragon\www\gellish\vendor\composer/../../app/Utils/helpers.php): failed to open stream: No such file or directory in C:\laragon\www\gellish\vendor\composer\autoload_real.php:69
Stack trace:
#0 C:\laragon\www\gellish\vendor\composer\autoload_real.php(69): Composer\Util\ErrorHandler::handle(2, 'require(C:\\lara...', 'C:\\laragon\\www\\...', 69, Array)
#1 C:\laragon\www\gellish\vendor\composer\autoload_real.php(69): require()
#2 C:\laragon\www\gellish\vendor\composer\autoload_real.php(59): composerRequire46a8e24d5a858e333c4365e33c329b43('737b5e887b8d94a...', 'C:\\laragon\\www\\...')
#3 C:\laragon\www\gellish\vendor\autoload.php(7): ComposerAutoloaderInit46a8e24d5a858e333c4365e33c329b43::getLoader()
#4 C:\laragon\www\gellish\vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(43): require_once('C:\\laragon\\www\\...')
#5 phar://C:/laragon/bin/composer/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(297): Illuminate\Foundation\ComposerScripts:: in C:\laragon\www\gellish\vendor\composer\autoload_real.php on line 69

Fatal error: composerRequire46a8e24d5a858e333c4365e33c329b43(): Failed opening required 'C:\laragon\www\gellish\vendor\composer/../../app/Utils/helpers.php' (include_path='.;C:/laragon/etc/php/pear') in C:\laragon\www\gellish\vendor\composer\autoload_real.php on line 69
```

**Comment by xabbuh** [comment]
The file `app/Utils/helpers.php` is referenced in the `autoload` section of your own `composer.json` file. If it doesn't exist, you will need to adapt your autoload configuration to reflect that (e.g. remove the `files` section).
