### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters

### ISSUE THREAD

**Issue by sebastianbergmann** [composer/composer#9097]
Using PHP 8.0.0-dev (`e3d06fc79db5af5dba3f4a65bd24b3712711f1ae`), I run into the following problem:

#### PHP 8.0 and Composer 1.10.9
```
$ php-80 ./tools/composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge(phpunit/phpunit: Array)
#1 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array('array_merge', Array)
#2 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages(Object(Composer\DependencyResolver\Pool), Array, Array, 'phpunit/phpunit')
#3 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall(1, Array, Array, Object(Composer\DependencyResolver\GenericRule))
#4 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat(Array)
#5 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve(Object(Composer\DependencyResolver\Request), false)
#6 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Installer.php(232): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#7 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///usr/local/src/phpunit/tools/composer/bin/composer(61): Composer\Console\Application->run()
#15 /usr/local/src/phpunit/tools/composer(24): require('phar:///usr/loc...')
#16 {main}
  thrown in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 84
```
#### PHP 8.0 and Composer 2.0.0-alpha2
```
$ php-80 ./tools/composer install
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/DefaultPolicy.php:63
Stack trace:
#0 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/DefaultPolicy.php(63): array_merge(doctrine/instantiator: Array)
#1 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Solver.php(354): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages(Object(Composer\DependencyResolver\Pool), Array, 'doctrine/instan...')
#2 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Solver.php(664): Composer\DependencyResolver\Solver->selectAndInstall(1, Array, Object(Composer\DependencyResolver\GenericRule))
#3 phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Solver.php(209): Composer\DependencyResolver\Solver->runSat()
#4 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Installer.php(411): Composer\DependencyResolver\Solver->solve(Object(Composer\DependencyResolver\Request), false)
#5 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Installer.php(249): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#6 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Command/InstallCommand.php(129): Composer\Installer->run()
#7 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Console/Application.php(287): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/local/src/phpunit/tools/composer/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///usr/local/src/phpunit/tools/composer/bin/composer(61): Composer\Console\Application->run()
#14 /usr/local/src/phpunit/tools/composer(24): require('phar:///usr/loc...')
#15 {main}
  thrown in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 63
```

The line in question is https://github.com/composer/composer/blob/1.10.9/src/Composer/DependencyResolver/DefaultPolicy.php#L84 or https://github.com/composer/composer/blob/2.0.0-alpha2/src/Composer/DependencyResolver/DefaultPolicy.php#L63, respectively.

**Comment by sebastianbergmann** [comment]
I am almost certain that this is nothing that can/should be fixed in Composer, but that this is rather an issue in PHP 8.

@nikic What do you think?

**Comment by nikic** [comment]
This has already been fixed in #9076. It's (the only) expected breakage from named parameters.

**Comment by sebastianbergmann** [comment]
Thank you, Nikita! Somehow #9076 did not show up in my search.

**Comment by jrfnl** [comment]
Was just about to report this. Glad to read it has already been fixed :+1:

**Comment by ed-mor** [comment]
I updated composer, from version 1.6 to 2.0 and everything fixed.

**Comment by ahmedatef00** [comment]
I can't upgrade  to 2.0
![Screenshot from 2021-01-28 16-50-23](https://user-images.githubusercontent.com/25952030/106155067-ef1c7c00-6188-11eb-97df-5f96c492c87d.png)

**Comment by jrfnl** [comment]
@ahmedatef00 Could you please try upgrading to the latest Composer 1.x version, `1.10.20` and then test again ?
You should be able to do so with `composer self-update --1`

**Comment by ahmedatef00** [comment]
@jrfnl  
![Screenshot from 2021-01-29 20-55-41](https://user-images.githubusercontent.com/25952030/106315768-6713a080-6274-11eb-8b58-8dce91d583cb.png)
it always gives me this error and  the documentation is so confusing about this

**Comment by jrfnl** [comment]
@ahmedatef00 Download a fresh copy of Composer 1.x and install that ? If that doesn't help, you may want to move this to a separate ticket as your problem does not seem to be related to the topic which was being discussed here.

**Comment by richard457** [comment]
updating composer solved the issue for me.

**Comment by bobdabiulder** [comment]
Issue is present in V2.0.12, running PHP 8.0 and Ubuntu 20.04 with all packages up to date.  Trying to set up Cachet 2.3.9 and running the command `composer install --no-dev -o` produces this error.

**Comment by Seldaek** [comment]
@bobdabiulder please report a new issue with all the details we ask for in the issue template if you can still reproduce this. I can't, and this issue here is closed and fixed.

**Comment by yuri2397** [comment]
I fixe the like this:

1. `sudo apt install wget php-cli php-zip unzip`
2.` php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`
3. `php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`
4. `HASH="$(wget -q -O - https://composer.github.io/installer.sig)"`
5. ` php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"`
        _Out put: **_Installer verified_**_
6. `sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer`
      _Out put:  **All settings correct for using Composer
                       Downloading...
                       Composer (version 2.0.14) successfully installed to: /usr/local/bin/composer
                        Use it: php /usr/local/bin/composer**_
### It's Okay.
You can try to tape composer.
Diadieuf

**Comment by SyedAsadRazaDevops** [comment]
i have the same issue " Fatal error: **Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84** "
and everything is fine and working on my other Linux server. I search for so long on google and StackOverflow and try different solutions, but still the same error.

**Recommendation**: *just install the latest version of the composer in Linux and define it globally and run it on the project directory and the issue is resolved.*

Composer **1.10.1** ----> to ------> Composer version **2.3.4**

**Hint**: if same then revoke the composer.lock and vendor folder and run it again.

**Comment by agm1984** [comment]
I upgraded my composer by running the following script on my Laravel Forge server (ie: made this a Recipe):

``` bash
apt-get remove composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer
```

**Comment by Elikill58** [comment]
The issue already appear even after using `composer self-update --preview`:

![image](https://user-images.githubusercontent.com/17381066/181057697-495d68f7-c89c-4dec-b91c-eb2493395de7.png)

I can't run `composer global require laravel/installer`

**Comment by SyedAsadRazaDevops** [comment]
_Error-Uncaught-ArgumentCountError-array_merge-does-not-accept-unknown-named-parameter-.php-84_

I can answer your questions and have an **example** on this **[Github repo](https://github.com/SyedAsadRazaDevops/Error-Uncaught-ArgumentCountError-array_merge-does-not-accept-unknown-named-parameter-.php-84).**
@SyedAsadRazaDevops

**Comment by Elikill58** [comment]
> _Error-Uncaught-ArgumentCountError-array_merge-does-not-accept-unknown-named-parameter-.php-84_
> 
> I can answer your questions and have an **example** on this **[Github repo](https://github.com/SyedAsadRazaDevops/Error-Uncaught-ArgumentCountError-array_merge-does-not-accept-unknown-named-parameter-.php-84).** @SyedAsadRazaDevops

I already do all tasks

**Comment by vageenko** [comment]
## Exception

```shell
user@host:~$ composer

PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Console/Helper/HelperSet.php on line 104

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Console/Helper/HelperSet.php on line 104
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/php/JsonSchema/Constraints/Constraint.php:48
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Composer/Repository/ArrayRepository.php:206
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Composer/Repository/ArrayRepository.php:206
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Composer/Repository/ArrayRepository.php:206
Deprecation Notice: Return type of Symfony\Component\Process\Process::getIterator($flags = 0) should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Process/Process.php:606
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer 1.10.1 2020-03-13 20:34:27

Usage:
  command [options] [arguments]

PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Console\Helper\mb_detect_encoding() in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:50
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Descriptor/TextDescriptor.php(329): Symfony\Component\Console\Helper\Helper::strlen()
#1 /usr/share/php/Symfony/Component/Console/Descriptor/TextDescriptor.php(97): Symfony\Component\Console\Descriptor\TextDescriptor->calculateTotalWidthForOptions()
#2 /usr/share/php/Symfony/Component/Console/Descriptor/TextDescriptor.php(197): Symfony\Component\Console\Descriptor\TextDescriptor->describeInputDefinition()
#3 /usr/share/php/Symfony/Component/Console/Descriptor/Descriptor.php(55): Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication()
#4 /usr/share/php/Symfony/Component/Console/Helper/DescriptorHelper.php(67): Symfony\Component\Console\Descriptor\Descriptor->describe()
#5 /usr/share/php/Symfony/Component/Console/Command/ListCommand.php(75): Symfony\Component\Console\Helper\DescriptorHelper->describe()
#6 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Symfony\Component\Console\Command\ListCommand->execute()
#7 /usr/share/php/Symfony/Component/Console/Application.php(934): Symfony\Component\Console\Command\Command->run()
#8 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /usr/share/php/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#10 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#11 /usr/share/php/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#12 /usr/bin/composer(62): Composer\Console\Application->run()
#13 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 50

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Console\Helper\mb_detect_encoding() in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:50
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Descriptor/TextDescriptor.php(329): Symfony\Component\Console\Helper\Helper::strlen()
#1 /usr/share/php/Symfony/Component/Console/Descriptor/TextDescriptor.php(97): Symfony\Component\Console\Descriptor\TextDescriptor->calculateTotalWidthForOptions()
#2 /usr/share/php/Symfony/Component/Console/Descriptor/TextDescriptor.php(197): Symfony\Component\Console\Descriptor\TextDescriptor->describeInputDefinition()
#3 /usr/share/php/Symfony/Component/Console/Descriptor/Descriptor.php(55): Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication()
#4 /usr/share/php/Symfony/Component/Console/Helper/DescriptorHelper.php(67): Symfony\Component\Console\Descriptor\Descriptor->describe()
#5 /usr/share/php/Symfony/Component/Console/Command/ListCommand.php(75): Symfony\Component\Console\Helper\DescriptorHelper->describe()
#6 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Symfony\Component\Console\Command\ListCommand->execute()
#7 /usr/share/php/Symfony/Component/Console/Application.php(934): Symfony\Component\Console\Command\Command->run()
#8 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /usr/share/php/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#10 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#11 /usr/share/php/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#12 /usr/bin/composer(62): Composer\Console\Application->run()
#13 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 50
```


## In my case it simply fixed by:

```
sudo apt-get install php7.2-mbstring
```

**Comment by bsam2019** [comment]
**Solved it with the following commands**

curl -sS https://getcomposer.org/installer | php 
sudo mv composer.phar /usr/bin/composer
composer --version

**Comment by maxwellsothero** [comment]
> 5\. sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

m -r 

> **Resolvi com os seguintes comandos**
> 
> curl -sS https://getcomposer.org/installer | php sudo mv composer.phar /usr/bin/composer composer --version

![image](https://user-images.githubusercontent.com/67523005/211179008-c5705730-27ba-4843-a6a9-6ec21f3f0cc0.png)

Aqui tbm deu certo.

**Comment by sbasteiro** [comment]
> **Solved it with the following commands**
> 
> curl -sS https://getcomposer.org/installer | php sudo mv composer.phar /usr/bin/composer composer --version

TY!
