### ISSUE TITLE
Still get error in alpha 3 (just in one site)

### ISSUE THREAD

**Issue by jimrome** [composer/composer#9104]
My `composer.json`:

```{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "require": {
        "composer/installers": "^1.7",
        "dompdf/dompdf": "0.8.5",
        "drupal/admin_toolbar": "^2.3",
        "drupal/backup_migrate": "^4.1",
        "drupal/block_visibility_groups": "^1.3",
        "drupal/captcha": "^1.0@beta",
        "drupal/core-composer-scaffold": "^8.8",
        "drupal/core-project-message": "^8.8",
        "drupal/core-recommended": "^8.8.4",
        "drupal/ctools": "^3.4",
        "drupal/email_confirmer": "^1.0@beta",
        "drupal/embed": "^1.4",
        "drupal/entity": "^1.1",
        "drupal/entity_browser": "^1.10",
        "drupal/entity_extra_field": "^1.0@alpha",
        "drupal/entity_print": "^2.2",
        "drupal/formblock": "^1.0@beta",
        "drupal/front": "^1.0@beta",
        "drupal/gdoc_field": "^1.1",
        "drupal/gtranslate": "^1.13",
        "drupal/honeypot": "^1.29",
        "drupal/hover_preview": "1.x-dev",
        "drupal/imce": "^2.2",
        "drupal/mailchimp": "^1.11",
        "drupal/mailing_list": "^1.0@beta",
        "drupal/mailsystem": "^4.3",
        "drupal/media_entity_actions": "^1.0@alpha",
        "drupal/media_upload": "^1.7",
        "drupal/metatag": "^1.13",
        "drupal/module_filter": "^3.1",
        "drupal/module_missing_message_fixer": "^1.1",
        "drupal/page_manager": "^4.0@beta",
        "drupal/panelizer": "^4.4",
        "drupal/path_file": "^1.0",
        "drupal/pathauto": "^1.8",
        "drupal/pdf_reader": "1.x-dev",
        "drupal/php": "^1.0",
        "drupal/search_api": "^1.16",
        "drupal/search_api_page": "^1.0@alpha",
        "drupal/smtp": "^1.0@RC",
        "drupal/spambot": "^1.0@alpha",
        "drupal/statistics_counter": "^1.0@beta",
        "drupal/superfish": "^1.4",
        "drupal/token": "^1.7",
        "drupal/upgrade_status": "^2.9",
        "drupal/video_embed_field": "^2.4",
        "drupal/views_base_url": "^1.0",
        "drupal/views_send": "^1.5",
        "drupal/views_slideshow": "^4.7",
        "drupal/webform": "^6.0",
        "drupal/webform_mailchimp": "^5.4",
        "drupal/zurb_foundation": "^5.0@beta",
        "drush/drush": "^10.3",
        "mikehaertl/phpwkhtmltopdf": "~2.1",
        "tecnickcom/tcpdf": "~6",
        "wikimedia/composer-merge-plugin": "^1.4"
    },
    "conflict": {
        "drupal/drupal": "8.8.4"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php.",
            "This file specifies the packages.drupal.org repository.",
            "You can read more about this composer repository at:",
            "https://www.drupal.org/node/2718229"
        ],
        "installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": "Drupal\\Core\\Composer\\Composer::ensureHtaccess",
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "drupal-phpunit-upgrade-check": "Drupal\\Core\\Composer\\Composer::upgradePHPUnit",
        "drupal-phpunit-upgrade": "@composer update phpunit/phpunit --with-dependencies --no-progress",
        "phpcs": "phpcs --standard=core/phpcs.xml.dist --runtime-set installed_paths $($COMPOSER_BINARY config vendor-dir)/drupal/coder/coder_sniffer --",
        "phpcbf": "phpcbf --standard=core/phpcs.xml.dist --runtime-set installed_paths $($COMPOSER_BINARY config vendor-dir)/drupal/coder/coder_sniffer --"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}
```

Output of `composer diagnose`:

```
erge-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Checking composer.json: WARNING
require.drupal/hover_preview : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/pdf_reader : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.0-alpha3 => 1.10.10)
Composer version: 2.0.0-alpha3
PHP version: 7.4.8
PHP binary path: /opt/alt/php74/usr/bin/php
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

When I run this command:

```
composer update --no-dev --with-dependencies --ignore-platform-req=composer-plugin-api
```

I get the following output:

```
Fatal error: Uncaught Error: Call to undefined method Composer\DependencyResolver\Operation\UpdateOperation::getJobType() in /home/stelnews/public_html/core/lib/Drupal/Core/Composer/Composer.php:170
Stack trace:
#0 phar:///home/stelnews/public_html/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(319): Drupal\Core\Composer\Composer::vendorTestCodeCleanup(Object(Composer\Installer\PackageEvent))
#1 phar:///home/stelnews/public_html/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(216): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Drupal\\Core\\Com...', 'vendorTestCodeC...', Object(Composer\Installer\PackageEvent))
#2 phar:///home/stelnews/public_html/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(123): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\PackageEvent))
#3 phar:///home/stelnews/public_html/composer.phar/src/Composer/Installer/InstallationManager.php(386): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent(' in /home/stelnews/public_html/core/lib/Drupal/Core/Composer/Composer.php on line 170
```

And I expected this to happen:
Should have updated my site. I have 6 similar sites, and composer 2 alpha 3 worked on them although alpha 2 did not.
composer --version
The "wikimedia/composer-merge-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Composer version 2.0.0-alpha3 2020-08-03 11:52:10

**Comment by stof** [comment]
The error happens in `Drupal\Core\Composer\Composer::vendorTestCodeCleanup`. It looks like drupal/core is not yet compatible with Composer 2.

**Comment by jimrome** [comment]
Composer 2 worked in 4 other sites, but fails in 2 of them
And by the way, when this happens, 
composer self-update --rollback
fails with the same error.
But composer _self-update_ rolls it back luckily

**Comment by jimrome** [comment]
So drupal/core does work sometimes with Composer 2. It never worked with alpha 2

**Comment by Seldaek** [comment]
This is definitely an issue in your plugin somehow, I'd report it to the Drupal repo if you are sure you are using up to date packages.
