### ISSUE TITLE
Fatal Error: "inet_pton" not found on PHP 8.0 + Windows

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#9128]
I'm getting this fatal error when running `composer update` on PHP 8 nightly + Windows:

```
2020-08-17T06:06:07.1198057Z Loading composer repositories with package information
2020-08-17T06:06:07.1217380Z PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($function) must be a valid callback, class "inet_pton" not found in phar://C:/tools/php/composer/src/Composer/Platform/Runtime.php:44
2020-08-17T06:06:07.1219569Z Stack trace:
2020-08-17T06:06:07.1220021Z #0 phar://C:/tools/php/composer/src/Composer/Platform/Runtime.php(44): call_user_func_array()
2020-08-17T06:06:07.1241154Z 
2020-08-17T06:06:07.1241611Z #1 [internal function]: Composer\Platform\Runtime->invoke()
2020-08-17T06:06:07.1242402Z Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($function) must be a valid callback, class "inet_pton" not found in phar://C:/tools/php/composer/src/Composer/Platform/Runtime.php:44
2020-08-17T06:06:07.1244029Z #2 phar://C:/tools/php/composer/src/Composer/Util/Silencer.php(68): call_user_func_array()
2020-08-17T06:06:07.1244751Z Stack trace:
2020-08-17T06:06:07.1245437Z #3 phar://C:/tools/php/composer/src/Composer/Repository/PlatformRepository.php(128): Composer\Util\Silencer::call()
2020-08-17T06:06:07.1246750Z #0 phar://C:/tools/php/composer/src/Composer/Platform/Runtime.php(44): call_user_func_array()
2020-08-17T06:06:07.1247160Z #4 phar://C:/tools/php/composer/src/Composer/Repository/ArrayRepository.php(265): Composer\Repository\PlatformRepository->initialize()
2020-08-17T06:06:07.1247473Z #1 [internal function]: Composer\Platform\Runtime->invoke()
2020-08-17T06:06:07.1247756Z #5 phar://C:/tools/php/composer/src/Composer/Installer.php(824): Composer\Repository\ArrayRepository->getPackages()
2020-08-17T06:06:07.1248111Z #2 phar://C:/tools/php/composer/src/Composer/Util/Silencer.php(68): call_user_func_array()
2020-08-17T06:06:07.1248366Z #6 phar://C:/tools/php/composer/src/Composer/Installer.php(386): Composer\Installer->createRequest()
2020-08-17T06:06:07.1248635Z #3 phar://C:/tools/php/composer/src/Composer/Repository/PlatformRepository.php(128): Composer\Util\Silencer::call()
2020-08-17T06:06:07.1250365Z #4 phar://C:/tools/php/composer/src/Composer/Repository/ArrayRepository.php(265): Composer\Repository\PlatformRepository->initialize()
2020-08-17T06:06:07.1251336Z #7 phar://C:/tools/php/composer/src/Composer/Installer.php(250): Composer\Installer->doUpdate()
2020-08-17T06:06:07.1251479Z #5 phar://C:/tools/php/composer/src/Composer/Installer.php(824): Composer\Repository\ArrayRepository->getPackages()
2020-08-17T06:06:07.1251778Z #8 phar://C:/tools/php/composer/src/Composer/Command/UpdateCommand.php(228): Composer\Installer->run()
2020-08-17T06:06:07.1251907Z #6 phar://C:/tools/php/composer/src/Composer/Installer.php(386): Composer\Installer->createRequest()
2020-08-17T06:06:07.1252180Z #9 phar://C:/tools/php/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute()
2020-08-17T06:06:07.1252311Z #7 phar://C:/tools/php/composer/src/Composer/Installer.php(250): Composer\Installer->doUpdate()
2020-08-17T06:06:07.1252773Z #10 phar://C:/tools/php/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
2020-08-17T06:06:07.1252910Z #8 phar://C:/tools/php/composer/src/Composer/Command/UpdateCommand.php(228): Composer\Installer->run()
2020-08-17T06:06:07.1253373Z #11 phar://C:/tools/php/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
2020-08-17T06:06:07.1254492Z #9 phar://C:/tools/php/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute()
2020-08-17T06:06:07.1254882Z #12 phar://C:/tools/php/composer/src/Composer/Console/Application.php(309): Symfony\Component\Console\Application->doRun()
2020-08-17T06:06:07.1255040Z #10 phar://C:/tools/php/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
2020-08-17T06:06:07.1255364Z #13 phar://C:/tools/php/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
2020-08-17T06:06:07.1255619Z #11 phar://C:/tools/php/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
2020-08-17T06:06:07.1255934Z #14 phar://C:/tools/php/composer/src/Composer/Console/Application.php(121): Symfony\Component\Console\Application->run()
2020-08-17T06:06:07.1256080Z #12 phar://C:/tools/php/composer/src/Composer/Console/Application.php(309): Symfony\Component\Console\Application->doRun()
2020-08-17T06:06:07.1256674Z #15 phar://C:/tools/php/composer/bin/composer(61): Composer\Console\Application->run()
2020-08-17T06:06:07.1256805Z #13 phar://C:/tools/php/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
2020-08-17T06:06:07.1257058Z #16 C:\tools\php\composer(25): require('...')
2020-08-17T06:06:07.1257181Z #14 phar://C:/tools/php/composer/src/Composer/Console/Application.php(121): Symfony\Component\Console\Application->run()
2020-08-17T06:06:07.1257426Z #17 {main}
2020-08-17T06:06:07.1257517Z #15 phar://C:/tools/php/composer/bin/composer(61): Composer\Console\Application->run()
2020-08-17T06:06:07.1257774Z   thrown in phar://C:/tools/php/composer/src/Composer/Platform/Runtime.php on line 44
2020-08-17T06:06:07.1257888Z #16 C:\tools\php\composer(25): require('...')
2020-08-17T06:06:07.1258136Z #17 {main}
2020-08-17T06:06:07.1258353Z   thrown in phar://C:/tools/php/composer/src/Composer/Platform/Runtime.php on line 44
2020-08-17T06:06:07.1611197Z ##[error]Process completed with exit code 1.
```

I'm not able to decipher [the offending line in PlatformRepository](https://github.com/composer/composer/blob/0eebdcf2e655f28107aa2c5c33f6d7a4c948457b/src/Composer/Repository/PlatformRepository.php#L128):

```
if ($this->runtime->hasConstant('AF_INET6') || Silencer::call(array($this->runtime, 'invoke'), array('inet_pton', '::')) !== false) {
```

But it looks like it's trying to use `inet_pton` in place of a class name, and fails.

**Comment by ondrejmirtes** [comment]
Sorry, maybe it's just that setup-php has an outdated Composer and the current version works, not sure yet.

**Comment by ondrejmirtes** [comment]
@shivammathur in https://github.com/shivammathur/setup-php/issues/273 says:

> Composer `snapshot` is same in both OS, The issue is in `composer` or `php-src`.
> The commit [composer/composer@7e1ef19](https://github.com/composer/composer/commit/7e1ef19a5a544af35a3b063652659637c711fb2a) introduced the bug.
