### ISSUE TITLE
 Argument 1 passed to Composer\Semver\Intervals::compactConstraint() must implement interface Composer\Semver\Constraint\ConstraintInterface, string given

### ISSUE THREAD

**Issue by GromNaN** [composer/composer#9245]
My `composer.json` (this is a demo app inside a symfony bundle repository):

```json
{
    "type": "project",
    "repositories": [
        {
            "type": "path",
            "url": "../",
            "options": {
                "symlink": true
            }
        }
    ],
    "require": {
        "php": ">=7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "pmd/storybook-bundle": "@dev",
        "symfony/asset": "5.1.*",
        "symfony/console": "5.1.*",
        "symfony/dotenv": "5.1.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.1.*",
        "symfony/yaml": "5.1.*"
    },
    "require-dev": {
        "symfony/debug-pack": "^1.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.1.*"
        }
    }
}
```

Parent  `../composer.json`:
```json
{
    "name": "pmd/storybook-bundle",
    "description": "",
    "type": "symfony-bundle",
    "autoload": {
        "psr-4": {
            "PMD\\Storybook\\": "./src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "PMD\\Storybook\\Tests\\": "./tests"
        }
    },
    "require": {
        "symfony/asset": "^3.4|^4.4|^5.0",
        "symfony/finder": "^3.4|^4.4|^5.0",
        "symfony/framework-bundle": "^3.4|^4.4|^5.0",
        "symfony/options-resolver": "^3.4|^4.4|^5.0",
        "symfony/twig-bundle": "^3.4|^4.4|^5.0",
        "symfony/yaml": "^3.4|^4.4|^5.0"
    },
    "require-dev": {
        "symfony/phpunit-bridge": "^5.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.pmd/storybook-bundle : unbound version constraints (@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0-dev+5df1797d20c6ab1eb606dc0f0d76a16ba57ddb7f
PHP version: 7.4.10
PHP binary path: /usr/local/Cellar/php/7.4.10/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer req debug --dev
```

I get the following output:

```
Using version ^1.0 for symfony/debug-pack
./composer.json has been updated
Running composer update symfony/debug-pack
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
40 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Composer\Semver\Intervals::compactConstraint() must implement interface Composer\Semver\Constraint\ConstraintInterface, string given, called in /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Unpacker.php on line 146 and defined in phar:///Users/jtamarel/.symfony/bin/composer/vendor/composer/semver/src/Intervals.php:139
Stack trace:
#0 /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Unpacker.php(146): Composer\Semver\Intervals::compactConstraint('^5.1')
#1 /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Command/UnpackCommand.php(79): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#2 /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Command/RequireCommand.php(63): Symfony\Flex\Co in phar:///Users/jtamarel/.symfony/bin/composer/vendor/composer/semver/src/Intervals.php on line 139

Fatal error: Uncaught TypeError: Argument 1 passed to Composer\Semver\Intervals::compactConstraint() must implement interface Composer\Semver\Constraint\ConstraintInterface, string given, called in /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Unpacker.php on line 146 and defined in phar:///Users/jtamarel/.symfony/bin/composer/vendor/composer/semver/src/Intervals.php:139
Stack trace:
#0 /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Unpacker.php(146): Composer\Semver\Intervals::compactConstraint('^5.1')
#1 /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Command/UnpackCommand.php(79): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#2 /Users/jtamarel/Code/Projects/tel-websites/programme-tv.net/vendor/pmd/storybook-bundle/demo/vendor/symfony/flex/src/Command/RequireCommand.php(63): Symfony\Flex\Co in phar:///Users/jtamarel/.symfony/bin/composer/vendor/composer/semver/src/Intervals.php on line 139
```

And I expected this to happen:

The error should not happen.

**Comment by stof** [comment]
This stack trace shows that the error happens in the `symfony/flex` plugin. And this is already tracked at https://github.com/symfony/flex/issues/678
