### ISSUE TITLE
Composer 2.0.0-RC1 why-not command error

### ISSUE THREAD

**Issue by acrobat** [composer/composer#9265]
My `composer.json`:

```json
{
    "require": {
        "doctrine/doctrine-migrations-bundle": "^1.3|^2.1"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.0-RC1 => 1.10.13)
Composer version: 2.0.0-RC1
PHP version: 7.2.31
PHP binary path: /usr/local/Cellar/php@7.2/7.2.31_1/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer why-not doctrine/doctrine-migrations-bundle 2.2.0
```

I get the following output:

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Composer\Package\Link::__construct() must implement interface Composer\Semver\Constraint\ConstraintInterface, null given, called in phar:///usr/local/bin/composer/src/Composer/Repository/InstalledRepository.php on line 202 and defined in phar:///usr/local/bin/composer/src/Composer/Package/Link.php:58
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/InstalledRepository.php(202): Composer\Package\Link->__construct('__root__', 'doctrine/migrat...', NULL, 'does not requir...', 'but v1.8.1 is i...')
#1 phar:///usr/local/bin/composer/src/Composer/Command/BaseDependencyCommand.php(126): Composer\Repository\InstalledRepository->getDependents('doctrine/doctri...', Object(Composer\Semver\Constraint\Constraint), true, false)
#2 phar:///usr/local/bin/composer/src/Composer/Command/ProhibitsCommand.php(55): Composer\Command\BaseDependencyCommand->doExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOut in phar:///usr/local/bin/composer2/src/Composer/Package/Link.php on line 58

Fatal error: Uncaught TypeError: Argument 3 passed to Composer\Package\Link::__construct() must implement interface Composer\Semver\Constraint\ConstraintInterface, null given, called in phar:///usr/local/bin/composer/src/Composer/Repository/InstalledRepository.php on line 202 and defined in phar:///usr/local/bin/composer/src/Composer/Package/Link.php:58
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/InstalledRepository.php(202): Composer\Package\Link->__construct('__root__', 'doctrine/migrat...', NULL, 'does not requir...', 'but v1.8.1 is i...')
#1 phar:///usr/local/bin/composer/src/Composer/Command/BaseDependencyCommand.php(126): Composer\Repository\InstalledRepository->getDependents('doctrine/doctri...', Object(Composer\Semver\Constraint\Constraint), true, false)
#2 phar:///usr/local/bin/composer/src/Composer/Command/ProhibitsCommand.php(55): Composer\Command\BaseDependencyCommand->doExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOut in phar:///usr/local/bin/composer2/src/Composer/Package/Link.php on line 58
```

And I expected this to happen: 

Get some info why compose didn't select version 2.2.0 of the package

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/9528ce705796a9b3b7fb541c30de8a0cba59f9b1
