### ISSUE TITLE
Composer 2.0.7 crashes my D9 update

### ISSUE THREAD

**Issue by jimrome** [composer/composer#9497]
My `composer.json`:

```json
[composer.json.zip](https://github.com/composer/composer/files/5562194/composer.json.zip)


```

Output of `composer diagnose`:

```
~/www/drupal]# composer diagnose
Checking composer.json: WARNING
require.drupal/views_slideshow : exact version constraints (4.x-dev) should be avoided if the package follows semantic versioning
require.drupal/front : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/module_filter : exact version constraints (3.x-dev) should be avoided if the package follows semantic versioning
require.drupal/uptime_widget : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/recreate_block_content : exact version constraints (2.x-dev@dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.4.12
PHP binary path: /opt/alt/php74/usr/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.71.0 libz 1.2.7 ssl OpenSSL/1.1.1d
zip extension: OK
```

When I run this command:

```
# composer update --no-dev --with-dependencies
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Package operations: 0 installs, 16 updates, 0 removals
  - Syncing drupal/audiofield (dev-1.x f4e9364) into cache
  - Upgrading drupal/core-project-message (9.0.7 => 9.0.8): Extracting archive
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup

Fatal error: Uncaught Error: Call to undefined method Composer\DependencyResolver\Operation\UpdateOperation::getJobType() in /home/jamesrom/public_html/drupal/core/lib/Drupal/Core/Composer/Composer.php:189
Stack trace:
#0 phar:///home/jamesrom/public_html/drupal/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(323): Drupal\Core\Composer\Composer::vendorTestCodeCleanup(Object(Composer\Installer\PackageEvent))
#1 phar:///home/jamesrom/public_html/drupal/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Drupal\\Core\\Com...', 'vendorTestCodeC...', Object(Composer\Installer\PackageEvent))
#2 phar:///home/jamesrom/public_html/drupal/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\PackageEvent))
#3 phar:///home/jamesrom/public_html/drupal/composer.phar/src/Composer/Installer/InstallationManager.php(426): Composer\EventDispatcher\Even in /home/jamesrom/public_html/drupal/core/lib/Drupal/Core/Composer/Composer.php on line 189
```

And I expected this to happen:
Should have update my site.
Composer 1.10.10 worked

**Comment by stof** [comment]
this should be reported to Drupal so that they make their `Drupal\Core\Composer\Composer::vendorTestCodeCleanup` compatible with Composer 2. That's not a bug in Composer. `OperationInterface::getJobType()` was replaced by `getOperationType`

**Comment by jimrome** [comment]
Thank you!
