### ISSUE TITLE
Dependencies of plugin-modifies-downloads plugins not autoloaded when using minimum-stability dev

### ISSUE THREAD

**Issue by Qrious** [composer/composer#9499]
My `composer.json`:

```json
{
    "name": "example/test",
    "repositories": [
      {
        "type": "composer",
        "url": "https://pivvenit.github.io/acf-composer-bridge/composer/v3/wordpress-plugin/"
      }
    ],
    "minimum-stability": "dev",
    "require": {
      "vlucas/phpdotenv": "^5.0",
      "advanced-custom-fields/advanced-custom-fields-pro": "^5.8.12"
    }
  }
```

Output of `composer diagnose`:

```text
composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: The Windows OneDrive folder is not supported on PHP versions below 7.2.23 and 7.3.10.
Upgrade your PHP (7.3.2) to use this location with Composer.


Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.3.2
PHP binary path: C:\Program Files\php\php.exe
OpenSSL version: OpenSSL 1.1.1a  20 Nov 2018
cURL version: 7.61.1 libz 1.2.11 ssl OpenSSL/1.1.1a
zip extension: OK
```

When I run this command:

```text
composer install
```

I get the following output:

```text
Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in /plugin/src/LicenseKey/Providers/DotEnv/DotEnvV3Adapter.php:18
Stack trace:
#0 /plugin/src/LicenseKey/Providers/DotEnv/DotEnvLicenseKeyProvider.php(27): PivvenIT\Composer\Installers\ACFPro\LicenseKey\Providers\DotEnv\DotEnvV3Adapter->load('/app')
#1 /plugin/src/LicenseKey/Providers/CompositeLicenseKeyProvider.php(29): PivvenIT\Composer\Installers\ACFPro\LicenseKey\Providers\DotEnv\DotEnvLicenseKeyProvider->provide()
#2 /plugin/src/ACFProInstallerPlugin.php(156): PivvenIT\Composer\Installers\ACFPro\LicenseKey\Providers\CompositeLicenseKeyProvider->provide()
#3 /plugin/src/ACFProInstallerPlugin.php(142): PivvenIT\Composer\Installers\ACFPro\ACFProInstallerPlugin->getLicenseKey()
#4 [internal function]: PivvenIT\Composer\Installers\ACFPro\ACFProInstallerPlugin->onPreFileDownload(Object(Composer\Plugin\PreFileDownloadEvent))
#5 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(173): call_user_func(Array, Object(Composer\Plugin\PreFileDownlo in /plugin/src/LicenseKey/Providers/DotEnv/DotEnvV3Adapter.php on line 18
```

And I expected this to happen:
The class to exist.

# My analysis so far #

It seems there is a difference in the classes that can be autoloaded when using dev or stable as minimum-stability. 
I've attached two files, in order to not make the post too long. Both files contain the verbose output of composer, with a `var_export(spl_autoload_functions(), true)` statement. the dev_output.txt used `minimum-stability: dev` while the stable_output.txt used `minimum-stability: stable` The interesting part is the following difference:

**For stable: (line 335 of stable_output.txt)**

```php
 ['prefixDirsPsr4' =>                                                                                                       
        array (                                                                                                                    
          'Symfony\\Polyfill\\Php80\\' =>                                                                                          
          array (                                                                                                                  
            0 => '/app/vendor/symfony/polyfill-php80/',                                                                            
          ),                                                                                                                       
          'Symfony\\Polyfill\\Mbstring\\' =>                                                                                       
          array (                                                                                                                  
            0 => '/app/vendor/symfony/polyfill-mbstring/',                                                                         
          ),                                                                                                                       
          'Symfony\\Polyfill\\Ctype\\' =>                                                                                          
          array (                                                                                                                  
            0 => '/app/vendor/symfony/polyfill-ctype/',                                                                            
          ),                                                                                                                       
          'PivvenIT\\Composer\\Installers\\ACFPro\\' =>                                                                            
          array (                                                                                                                  
            0 => '/app/vendor/pivvenit/acf-pro-installer/src',                                                                     
          ),                                                                                                                       
          'PhpOption\\' =>                                                                                                         
          array (                                                                                                                  
            0 => '/app/vendor/phpoption/phpoption/src/PhpOption/',                                                                 
          ),                                                                                                                       
          'GrahamCampbell\\ResultType\\' =>                                                                                        
          array (                                                                                                                  
            0 => '/app/vendor/graham-campbell/result-type/src/',                                                                   
          ),                                                                                                                       
          'Dotenv\\' =>                                                                                                            
          array (                                                                                                                  
            0 => '/app/vendor/vlucas/phpdotenv/src/',                                                                              
          ),                                                                                                                       
        )]
```

**For dev: (line 348 of dev_output.txt)**
```php
[ 'prefixDirsPsr4' =>                                                                                                       
        array (                                                                                                                    
          'PivvenIT\\Composer\\Installers\\ACFPro\\' =>                                                                            
          array (                                                                                                                  
            0 => '/app/vendor/pivvenit/acf-pro-installer/src',                                                                     
          ),                                                                                                                       
        ),]
```

I hope this provides enough input for you to triage the issue, if you need any more information from my side, feel free to ask :)

[dev_output.txt](https://github.com/composer/composer/files/5562472/dev_output.txt)
[stable_output.txt](https://github.com/composer/composer/files/5562473/stable_output.txt)

**Comment by Seldaek** [comment]
Definitely seems to be a bug on our end in the way the autoloader is created for the plugin. Investigating..

**Comment by Seldaek** [comment]
Alright, nasty bug, thanks for the report. You can check with `composer self-update --snapshot` but it seems to be fixed for me (at least it reaches a point where it complains about a missing ACF PRO license key ;)
