### ISSUE TITLE
Try to execute json_decode into namespace

### ISSUE THREAD

**Issue by joubertredrat** [composer/composer#9587]
When I try to use `compose install` does error like diagnose below. 

Output of `composer diagnose`:

```
dev@dev-VirtualBox ~/s/e/app (master)> composer diagnose
PHP Fatal error:  Uncaught Error: Call to undefined function Composer\Json\json_decode() in phar:///home/dev/bin/composer/src/Composer/Json/JsonFile.php:175
Stack trace:
#0 phar:///home/dev/bin/composer/src/Composer/Factory.php(302): Composer\Json\JsonFile->validateSchema()
#1 phar:///home/dev/bin/composer/src/Composer/Factory.php(595): Composer\Factory->createComposer()
#2 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(408): Composer\Factory::create()
#3 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(526): Composer\Console\Application->getComposer()
#4 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(187): Composer\Console\Application->getPluginCommands()
#5 phar:///home/dev/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#6 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(122): Symfony\Component\Console\Application->run()
#7 phar:///home/dev/bin/composer/bin/composer(63): Composer\Console\Application->r in phar:///home/dev/bin/composer/src/Composer/Json/JsonFile.php on line 175

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in phar:///home/dev/bin/composer/src/Composer/Json/JsonFile.php:175
Stack trace:
#0 phar:///home/dev/bin/composer/src/Composer/Factory.php(302): Composer\Json\JsonFile->validateSchema()
#1 phar:///home/dev/bin/composer/src/Composer/Factory.php(595): Composer\Factory->createComposer()
#2 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(408): Composer\Factory::create()
#3 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(526): Composer\Console\Application->getComposer()
#4 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(187): Composer\Console\Application->getPluginCommands()
#5 phar:///home/dev/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#6 phar:///home/dev/bin/composer/src/Composer/Console/Application.php(122): Symfony\Component\Console\Application->run()
#7 phar:///home/dev/bin/composer/bin/composer(63): Composer\Console\Application->r in phar:///home/dev/bin/composer/src/Composer/Json/JsonFile.php on line 175
```

Composer version is 2.0.8 and PHP is 7.4
```
dev@dev-VirtualBox ~/s/e/app (master) [255]> php -v
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

**Comment by Seldaek** [comment]
If you see this I am assuming you do not have the json extension built into PHP.. It's enabled by default tho and is a requirement to run Composer. Make sure you don't disable it when building php.

**Comment by guoyunhe** [comment]
Maybe @joubertredrat is using openSUSE Tumbleweed? The issue is that package php8 now provides php-json. And this messed up package dependencies... php8 is installed with php7, but php7-json is removed... I am working on a fix.

**Comment by evchristelis** [comment]
Any news on this?
I am in the same situation and none of the workarounds found worked.
Thank you!

**Comment by evchristelis** [comment]
Resolved it by removing composer and reinstalling.
The key was to install the PHP JSON module, even though it was there.
On CentOS 7 it worked with sudo yum install php-json.
The version that was installed was for php7.2 and it worked, even though I am having php7.4 .
