### ISSUE TITLE
Composer 2.0.9 not installing PhantomJS

### ISSUE THREAD

**Issue by JackPot777** [composer/composer#9698]
PHP 7.3-7.4

My `composer.json`:

```json
"require": {
        "jonnyw/php-phantomjs": "4.*"
    },
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    }
```

When I run this command: 

```
php7.3 composer.phar install (or php = php7.4, or update)
```

I get the following output: 

```
post-update-cmd: PhantomInstaller\Installer::installPhantomJS
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Composer\Downloader\DownloadManager::download() must implement interface Composer\Package\PackageInterface or be null, bool given, called in /my_path/vendor/jakoch/phantomjs-installer/src/PhantomInstaller/Installer.php on line 192 and defined in phar:///my_patht/composer.phar/src/Composer/Downloader/DownloadManager.php:182
Stack trace:
#0 /my_path/vendor/jakoch/phantomjs-installer/src/PhantomInstaller/Installer.php(192): Composer\Downloader\DownloadManager->download(Object(Composer\Package\Package), '/my_path...', false)
#1 /my_path/vendor/jakoch/phantomjs-installer/src/PhantomInstaller/Installer.php(121): PhantomInstaller\Installer->download('/my_path...', '2.1.1')
#2 /my_path/vendor/jakoch/phantomjs-installer/src/PhantomInstaller/Installer.php(94): PhantomInstaller\Installer->__invoke()
#3 phar:///my_path in phar:///my_path/composer.phar/src/Composer/Downloader/DownloadManager.php on line 182
```

BUT:

```
works and installs on composer 1.9
```

**Comment by stof** [comment]
Well, that should be reported to the jakoch/phantomjs-installer package, as the error says that it is passing the wrong arguments when calling the `Composer\Downloader\DownloadManager::download()` method. that's not a bug in composer.

The fact that it works with composer 1.9 is because the plugin executes different logic based on the version of composer (and the bug is probably in the code specific to composer 2).

**Comment by JackPot777** [comment]
> Well, that should be reported to the jakoch/phantomjs-installer package, as the error says that it is passing the wrong arguments when calling the `Composer\Downloader\DownloadManager::download()` method. that's not a bug in composer.
> 
> The fact that it works with composer 1.9 is because the plugin executes different logic based on the version of composer (and the bug is probably in the code specific to composer 2).

Thank. I don't know these nuances. The PhantomJS had to be installed for the first time.

**Comment by Seldaek** [comment]
You can track https://github.com/jonnnnyw/php-phantomjs/issues/288 - this is where the root issue is.

**Comment by nepohex** [comment]
Same issue
Ubuntu 22.04, Php 8.1, Composer 2.4.0

Composer.json file
```
"require": {
        "jonnyw/php-phantomjs": "4.*"
    },
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    }
```

```
root@DESKTOP-GFR1P9R:/var/www/html/phantom.js# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y

In Factory.php line 324:

  "./composer.json" does not match the expected JSON schema:
   - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]|-{1,2})?[
  a-z0-9]+)*$


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

root@DESKTOP-GFR1P9R:/var/www/html/phantom.js# mcedit composer.json

root@DESKTOP-GFR1P9R:/var/www/html/phantom.js# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 9 installs, 0 updates, 0 removals
  - Locking jakoch/phantomjs-installer (2.1.1)
  - Locking jonnyw/php-phantomjs (v4.5.1)
  - Locking psr/container (1.1.2)
  - Locking symfony/config (v3.4.47)
  - Locking symfony/dependency-injection (v3.4.47)
  - Locking symfony/filesystem (v3.4.47)
  - Locking symfony/polyfill-ctype (v1.26.0)
  - Locking symfony/yaml (v3.4.47)
  - Locking twig/twig (v1.44.6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Downloading symfony/polyfill-ctype (v1.26.0)
  - Downloading twig/twig (v1.44.6)
  - Downloading symfony/yaml (v3.4.47)
  - Downloading symfony/filesystem (v3.4.47)
  - Downloading psr/container (1.1.2)
  - Downloading symfony/dependency-injection (v3.4.47)
  - Downloading symfony/config (v3.4.47)
  - Downloading jakoch/phantomjs-installer (2.1.1)
  - Downloading jonnyw/php-phantomjs (v4.5.1)
  - Installing symfony/polyfill-ctype (v1.26.0): Extracting archive
  - Installing twig/twig (v1.44.6): Extracting archive
  - Installing symfony/yaml (v3.4.47): Extracting archive
  - Installing symfony/filesystem (v3.4.47): Extracting archive
  - Installing psr/container (1.1.2): Extracting archive
  - Installing symfony/dependency-injection (v3.4.47): Extracting archive
  - Installing symfony/config (v3.4.47): Extracting archive
  - Installing jakoch/phantomjs-installer (2.1.1): Extracting archive
  - Installing jonnyw/php-phantomjs (v4.5.1): Extracting archive
4 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> PhantomInstaller\Installer::installPhantomJS

In DownloadManager.php line 187:

  [TypeError]
  Composer\Downloader\DownloadManager::download(): Argument #3 ($prevPackage) must be of type ?Co
  mposer\Package\PackageInterface, bool given, called in /var/www/html/phantom.js/vendor/jakoch/p
  hantomjs-installer/src/PhantomInstaller/Installer.php on line 69


Exception trace:
  at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:187
 Composer\Downloader\DownloadManager->download() at /var/www/html/phantom.js/vendor/jakoch/phantomjs-installer/src/PhantomInstaller/Installer.php:69
 PhantomInstaller\Installer::download() at /var/www/html/phantom.js/vendor/jakoch/phantomjs-installer/src/PhantomInstaller/Installer.php:52
 PhantomInstaller\Installer::installPhantomJS() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:398
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:248
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:125
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:382
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:144
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1024
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:343
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:138
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
```

**Comment by nemelkiy** [comment]
Got same problem. I have Composer version 2.2.7
