### ISSUE TITLE
Composer 2.0.10 crashes on Magento 2.4.2, while 2.0.9 worked fine

### ISSUE THREAD

**Issue by hostep** [composer/composer#9717]
My `composer.json`:

```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "version": "2.4.2",
    "require": {
        "magento/product-community-edition": "2.4.2",
        "magento/composer-root-update-plugin": "~1.1"
    },
    "autoload": {
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ],
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "psr-4": {
            "Magento\\": "app/code/Magento/",
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        }
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~2.16.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": ">=0.12.3 <=0.12.23",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "~5.0.0",
        "squizlabs/php_codesniffer": "~3.5.4"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/",
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

Output of `composer diagnose`:

```
Can't run due to error
```

When I run this command:

```
composer -vvv
```

I get the following output: 

```
Reading ./composer.json (/some/path/to/project/composer.json)
Loading config file /Users/me/.composer/config.json
Loading config file /Users/me/.composer/auth.json
Loading config file ./composer.json (/some/path/to/project/composer.json)
Loading config file /some/path/to/project/auth.json
Reading /some/path/to/project/auth.json
Checked CA file /opt/local/share/curl/curl-ca-bundle.crt: valid
Failed to initialize global composer: Composer could not find the config file: /Users/me/.composer/composer.json

Reading /some/path/to/project/vendor/composer/installed.json
Loading plugin Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin
Loading plugin MagentoHackathon\Composer\Magento\Plugin
activate magento plugin
Loading plugin Magento\InventoryComposerInstaller\Plugin
Loading plugin Laminas\DependencyPlugin\DependencyRewriterPluginDelegator
Activating Laminas\DependencyPlugin\DependencyRewriterV2
PHP Fatal error:  Uncaught Error: Undefined class constant 'PRE_POOL_CREATE' in /some/path/to/project/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPluginDelegator.php:56
Stack trace:
#0 phar:///Users/me/bin/composer2.phar/src/Composer/EventDispatcher/EventDispatcher.php(381): Laminas\DependencyPlugin\DependencyRewriterPluginDelegator::getSubscribedEvents()
#1 phar:///Users/me/bin/composer2.phar/src/Composer/Plugin/PluginManager.php(331): Composer\EventDispatcher\EventDispatcher->addSubscriber(Object(Laminas\DependencyPlugin\DependencyRewriterPluginDelegator))
#2 phar:///Users/me/bin/composer2.phar/src/Composer/Plugin/PluginManager.php(232): Composer\Plugin\PluginManager->addPlugin(Object(Laminas\DependencyPlugin\DependencyRewriterPluginDelegator), false)
#3 phar:///Users/me/bin/composer2.phar/src/Composer/Plugin/PluginManager.php(395): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), false, false)
#4 phar in /some/path/to/project/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPluginDelegator.php on line 56

Fatal error: Uncaught Error: Undefined class constant 'PRE_POOL_CREATE' in /some/path/to/project/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPluginDelegator.php:56
Stack trace:
#0 phar:///Users/me/bin/composer2.phar/src/Composer/EventDispatcher/EventDispatcher.php(381): Laminas\DependencyPlugin\DependencyRewriterPluginDelegator::getSubscribedEvents()
#1 phar:///Users/me/bin/composer2.phar/src/Composer/Plugin/PluginManager.php(331): Composer\EventDispatcher\EventDispatcher->addSubscriber(Object(Laminas\DependencyPlugin\DependencyRewriterPluginDelegator))
#2 phar:///Users/me/bin/composer2.phar/src/Composer/Plugin/PluginManager.php(232): Composer\Plugin\PluginManager->addPlugin(Object(Laminas\DependencyPlugin\DependencyRewriterPluginDelegator), false)
#3 phar:///Users/me/bin/composer2.phar/src/Composer/Plugin/PluginManager.php(395): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), false, false)
#4 phar in /some/path/to/project/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPluginDelegator.php on line 56
```

And I expected this to happen:
It doesn't crash

### Further

This only started happening after upgrading composer from 2.0.9 to 2.0.10

I have the suspicion it has something to do with Magento who requires `"composer/composer": "^1.9"` in their `magento/composer` package: https://github.com/magento/composer/blob/fcc66f535d631788f2ba160ff547357086d9b2c9/composer.json#L12
And composer v1 doesn't define `PRE_POOL_CREATE`. So I think that in composer 2.0.9 the contants was found in the `composer.phar` and in 2.0.10 it's trying to find it in `vendor/composer/composer`

This sounds more like a bug in Magento itself: they should also try to require `composer/composer` v2. But since it used to work on 2.0.9 of composer, I'm not sure ...

**Comment by Seldaek** [comment]
Ok Composer 2.0.11 is out and should fix this regression, sorry for the trouble.

**Comment by hostep** [comment]
No worries, thanks for the super fast fix!
