### ISSUE TITLE
"--no-install" option should update the lock file, but not run scripts

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#9825]
Clone/checkout `git@github.com:PrestaShop/PrestaShop.git` and run:

```
composer remove --no-install friendsofphp/php-cs-fixer --dev
```

there will be error:

```
Warning: Uncaught ErrorException: require_once(/builds/mvorisek/prestashop_eshop/vendor/paragonie/random_compat/lib/random.php): failed to open stream: No such file or directory in /builds/mvorisek/prestashop_eshop/src/PrestaShopBundle/Install/Upgrade.php:30
Stack trace:
#0 /builds/mvorisek/prestashop_eshop/src/PrestaShopBundle/Install/Upgrade.php(30): Composer\Util\ErrorHandler::handle(2, 'require_once(/b...', '/builds/mvorise...', 30, Array)
#1 /builds/mvorisek/prestashop_eshop/src/PrestaShopBundle/Install/Upgrade.php(30): require_once()
#2 phar:///usr/local/bin/composer-orig/vendor/composer/ClassLoader.php(476): include('/builds/mvorise...')
#3 phar:///usr/local/bin/composer-orig/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile('src/PrestaShopB...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('PrestaShopBundl...')
#5 [internal function]: spl_autoload_call('PrestaShopBundl...')
#6 phar:///usr/local/bin/composer-orig/src/Composer/EventDispatcher/EventDispatcher.php(208): class_ in /builds/mvorisek/prestashop_eshop/src/PrestaShopBundle/Install/Upgrade.php on line 30
Fatal error: main(): Failed opening required '/builds/mvorisek/prestashop_eshop/vendor/paragonie/random_compat/lib/random.php' (include_path='.:/usr/local/lib/php') in /builds/mvorisek/prestashop_eshop/src/PrestaShopBundle/Install/Upgrade.php on line 30
```

`--no-update` implies `--no-scripts` but `--no-install` does not

**Comment by mvorisek** [comment]
I belive the correct behaviour should be:

```diff
 --no-update: Disables the automatic update of the dependencies (implies --no-install).
---no-install: Does not run the install step after updating the composer.lock file.
+--no-install: Does not run the install step after updating the composer.lock file (implies --no-scripts).
```

and code should be adjusted accordingly (eg. `--no-install` must never run scripts).

**Comment by Seldaek** [comment]
Not sure why it should imply no-scripts really, if an update occurs the scripts for post-update-cmd and co  may be needed.

**Comment by mvorisek** [comment]
But why `--no-update` does not run scripts?

**Comment by Seldaek** [comment]
Because that does not run update nor install, nothing happens there, only changing the json file.

**Comment by mvorisek** [comment]
Ok, closing, `--no-scripts` option must be used explicitly.
